schema_version: '1.0'
ip_name: x2p
cdc_paths:
- id: HLD.CDC.X2P.REQ_CDC
  name: req_cdc
  source_clock: clk_axi
  target_clock: clk_apb
  signal_type: bus
  sync_method: async_fifo
  req_ref:
  - LRS.FUNC.X2P.10.001
  - LRS.FUNC.X2P.10.002
- id: HLD.CDC.X2P.RSP_CDC
  name: rsp_cdc
  source_clock: clk_apb
  target_clock: clk_axi
  signal_type: bus
  sync_method: async_fifo
  req_ref:
  - LRS.FUNC.X2P.10.001
  - LRS.FUNC.X2P.10.002
