schema_version: '1.0'
ip_name: x2p
external_interfaces:
- id: HLD.IF.EXT.X2P.AXI_SLAVE
  name: axi_slave_if
  type: AXI
  direction: slave
  description: AXI4 / AXI4-Lite 从接口（AW/W/B/AR/R 五通道，含地址/ID/数据/保护属性/LAST/STRB）
  ports: []
  timing: {}
  req_ref:
  - LRS.INTF.X2P.01.001
  - LRS.INTF.X2P.01.002
  - LRS.FUNC.X2P.01.001
- id: HLD.IF.EXT.X2P.APB_MASTER
  name: apb_master_if
  type: APB
  direction: master
  description: APB3/APB4 主接口（PADDR/PSEL/PENABLE/PWRITE/PWDATA/PRDATA/PREADY/PSLVERR，APB4 含 PSTRB/PPROT）
  ports: []
  timing: {}
  req_ref:
  - LRS.INTF.X2P.02.001
  - LRS.INTF.X2P.02.002
  - LRS.FUNC.X2P.08.001
- id: HLD.IF.EXT.X2P.CLK_AXI
  name: clk_axi
  type: Clock
  direction: input
  description: AXI 域时钟
  ports: []
  timing: {}
  req_ref:
  - LRS.INTF.X2P.03.001
- id: HLD.IF.EXT.X2P.CLK_APB
  name: clk_apb
  type: Clock
  direction: input
  description: APB 域时钟
  ports: []
  timing: {}
  req_ref:
  - LRS.INTF.X2P.03.001
- id: HLD.IF.EXT.X2P.RST_AXI
  name: rst_axi_n
  type: Reset
  direction: input
  description: AXI 域低有效复位
  ports: []
  timing: {}
  req_ref:
  - LRS.INTF.X2P.03.002
- id: HLD.IF.EXT.X2P.RST_APB
  name: rst_apb_n
  type: Reset
  direction: input
  description: APB 域低有效复位（ASYNC 模式独立）
  ports: []
  timing: {}
  req_ref:
  - LRS.INTF.X2P.03.002
