// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef UART_REGS_H
#define UART_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - uart::CTRL
#define UART__CTRL__TX_bm 0x1
#define UART__CTRL__TX_bp 0
#define UART__CTRL__TX_bw 1
#define UART__CTRL__RX_bm 0x2
#define UART__CTRL__RX_bp 1
#define UART__CTRL__RX_bw 1
#define UART__CTRL__NF_bm 0x4
#define UART__CTRL__NF_bp 2
#define UART__CTRL__NF_bw 1
#define UART__CTRL__SLPBK_bm 0x10
#define UART__CTRL__SLPBK_bp 4
#define UART__CTRL__SLPBK_bw 1
#define UART__CTRL__LLPBK_bm 0x20
#define UART__CTRL__LLPBK_bp 5
#define UART__CTRL__LLPBK_bw 1
#define UART__CTRL__PARITY_EN_bm 0x40
#define UART__CTRL__PARITY_EN_bp 6
#define UART__CTRL__PARITY_EN_bw 1
#define UART__CTRL__PARITY_ODD_bm 0x80
#define UART__CTRL__PARITY_ODD_bp 7
#define UART__CTRL__PARITY_ODD_bw 1
#define UART__CTRL__RXBLVL_bm 0x300
#define UART__CTRL__RXBLVL_bp 8
#define UART__CTRL__RXBLVL_bw 2
#define UART__CTRL__NCO_bm 0xffff0000
#define UART__CTRL__NCO_bp 16
#define UART__CTRL__NCO_bw 16

// reg - uart::STATUS
#define UART__STATUS__TXFULL_bm 0x1
#define UART__STATUS__TXFULL_bp 0
#define UART__STATUS__TXFULL_bw 1
#define UART__STATUS__RXFULL_bm 0x2
#define UART__STATUS__RXFULL_bp 1
#define UART__STATUS__RXFULL_bw 1
#define UART__STATUS__TXEMPTY_bm 0x4
#define UART__STATUS__TXEMPTY_bp 2
#define UART__STATUS__TXEMPTY_bw 1
#define UART__STATUS__TXEMPTY_reset 0x1
#define UART__STATUS__TXIDLE_bm 0x8
#define UART__STATUS__TXIDLE_bp 3
#define UART__STATUS__TXIDLE_bw 1
#define UART__STATUS__TXIDLE_reset 0x1
#define UART__STATUS__RXIDLE_bm 0x10
#define UART__STATUS__RXIDLE_bp 4
#define UART__STATUS__RXIDLE_bw 1
#define UART__STATUS__RXIDLE_reset 0x1
#define UART__STATUS__RXEMPTY_bm 0x20
#define UART__STATUS__RXEMPTY_bp 5
#define UART__STATUS__RXEMPTY_bw 1
#define UART__STATUS__RXEMPTY_reset 0x1

// reg - uart::RDATA
#define UART__RDATA__DATA_bm 0xff
#define UART__RDATA__DATA_bp 0
#define UART__RDATA__DATA_bw 8

// reg - uart::WDATA
#define UART__WDATA__DATA_bm 0xff
#define UART__WDATA__DATA_bp 0
#define UART__WDATA__DATA_bw 8

// reg - uart::FIFO_CTRL
#define UART__FIFO_CTRL__RXRST_bm 0x1
#define UART__FIFO_CTRL__RXRST_bp 0
#define UART__FIFO_CTRL__RXRST_bw 1
#define UART__FIFO_CTRL__TXRST_bm 0x2
#define UART__FIFO_CTRL__TXRST_bp 1
#define UART__FIFO_CTRL__TXRST_bw 1
#define UART__FIFO_CTRL__RXILVL_bm 0x1c
#define UART__FIFO_CTRL__RXILVL_bp 2
#define UART__FIFO_CTRL__RXILVL_bw 3
#define UART__FIFO_CTRL__TXILVL_bm 0xe0
#define UART__FIFO_CTRL__TXILVL_bp 5
#define UART__FIFO_CTRL__TXILVL_bw 3

// reg - uart::FIFO_STATUS
#define UART__FIFO_STATUS__TXLVL_bm 0xff
#define UART__FIFO_STATUS__TXLVL_bp 0
#define UART__FIFO_STATUS__TXLVL_bw 8
#define UART__FIFO_STATUS__RXLVL_bm 0xff0000
#define UART__FIFO_STATUS__RXLVL_bp 16
#define UART__FIFO_STATUS__RXLVL_bw 8

// reg - uart::OVRD
#define UART__OVRD__TXEN_bm 0x1
#define UART__OVRD__TXEN_bp 0
#define UART__OVRD__TXEN_bw 1
#define UART__OVRD__TXVAL_bm 0x2
#define UART__OVRD__TXVAL_bp 1
#define UART__OVRD__TXVAL_bw 1

// reg - uart::VAL
#define UART__VAL__RX_bm 0xffff
#define UART__VAL__RX_bp 0
#define UART__VAL__RX_bw 16

// reg - uart::TIMEOUT_CTRL
#define UART__TIMEOUT_CTRL__VAL_bm 0xffffff
#define UART__TIMEOUT_CTRL__VAL_bp 0
#define UART__TIMEOUT_CTRL__VAL_bw 24
#define UART__TIMEOUT_CTRL__EN_bm 0x80000000
#define UART__TIMEOUT_CTRL__EN_bp 31
#define UART__TIMEOUT_CTRL__EN_bw 1

// reg - uart::INTR_STATE
#define UART__INTR_STATE__TX_EMPTY_bm 0x1
#define UART__INTR_STATE__TX_EMPTY_bp 0
#define UART__INTR_STATE__TX_EMPTY_bw 1
#define UART__INTR_STATE__RX_PARITY_ERR_bm 0x2
#define UART__INTR_STATE__RX_PARITY_ERR_bp 1
#define UART__INTR_STATE__RX_PARITY_ERR_bw 1
#define UART__INTR_STATE__RX_TIMEOUT_bm 0x4
#define UART__INTR_STATE__RX_TIMEOUT_bp 2
#define UART__INTR_STATE__RX_TIMEOUT_bw 1
#define UART__INTR_STATE__RX_BREAK_ERR_bm 0x8
#define UART__INTR_STATE__RX_BREAK_ERR_bp 3
#define UART__INTR_STATE__RX_BREAK_ERR_bw 1
#define UART__INTR_STATE__RX_FRAME_ERR_bm 0x10
#define UART__INTR_STATE__RX_FRAME_ERR_bp 4
#define UART__INTR_STATE__RX_FRAME_ERR_bw 1
#define UART__INTR_STATE__RX_OVERFLOW_bm 0x20
#define UART__INTR_STATE__RX_OVERFLOW_bp 5
#define UART__INTR_STATE__RX_OVERFLOW_bw 1
#define UART__INTR_STATE__TX_DONE_bm 0x40
#define UART__INTR_STATE__TX_DONE_bp 6
#define UART__INTR_STATE__TX_DONE_bw 1
#define UART__INTR_STATE__RX_WATERMARK_bm 0x80
#define UART__INTR_STATE__RX_WATERMARK_bp 7
#define UART__INTR_STATE__RX_WATERMARK_bw 1
#define UART__INTR_STATE__TX_WATERMARK_bm 0x100
#define UART__INTR_STATE__TX_WATERMARK_bp 8
#define UART__INTR_STATE__TX_WATERMARK_bw 1

// reg - uart::INTR_ENABLE
#define UART__INTR_ENABLE__TX_EMPTY_bm 0x1
#define UART__INTR_ENABLE__TX_EMPTY_bp 0
#define UART__INTR_ENABLE__TX_EMPTY_bw 1
#define UART__INTR_ENABLE__RX_PARITY_ERR_bm 0x2
#define UART__INTR_ENABLE__RX_PARITY_ERR_bp 1
#define UART__INTR_ENABLE__RX_PARITY_ERR_bw 1
#define UART__INTR_ENABLE__RX_TIMEOUT_bm 0x4
#define UART__INTR_ENABLE__RX_TIMEOUT_bp 2
#define UART__INTR_ENABLE__RX_TIMEOUT_bw 1
#define UART__INTR_ENABLE__RX_BREAK_ERR_bm 0x8
#define UART__INTR_ENABLE__RX_BREAK_ERR_bp 3
#define UART__INTR_ENABLE__RX_BREAK_ERR_bw 1
#define UART__INTR_ENABLE__RX_FRAME_ERR_bm 0x10
#define UART__INTR_ENABLE__RX_FRAME_ERR_bp 4
#define UART__INTR_ENABLE__RX_FRAME_ERR_bw 1
#define UART__INTR_ENABLE__RX_OVERFLOW_bm 0x20
#define UART__INTR_ENABLE__RX_OVERFLOW_bp 5
#define UART__INTR_ENABLE__RX_OVERFLOW_bw 1
#define UART__INTR_ENABLE__TX_DONE_bm 0x40
#define UART__INTR_ENABLE__TX_DONE_bp 6
#define UART__INTR_ENABLE__TX_DONE_bw 1
#define UART__INTR_ENABLE__RX_WATERMARK_bm 0x80
#define UART__INTR_ENABLE__RX_WATERMARK_bp 7
#define UART__INTR_ENABLE__RX_WATERMARK_bw 1
#define UART__INTR_ENABLE__TX_WATERMARK_bm 0x100
#define UART__INTR_ENABLE__TX_WATERMARK_bp 8
#define UART__INTR_ENABLE__TX_WATERMARK_bw 1

// reg - uart::INTR_TEST
#define UART__INTR_TEST__TX_EMPTY_bm 0x1
#define UART__INTR_TEST__TX_EMPTY_bp 0
#define UART__INTR_TEST__TX_EMPTY_bw 1
#define UART__INTR_TEST__RX_PARITY_ERR_bm 0x2
#define UART__INTR_TEST__RX_PARITY_ERR_bp 1
#define UART__INTR_TEST__RX_PARITY_ERR_bw 1
#define UART__INTR_TEST__RX_TIMEOUT_bm 0x4
#define UART__INTR_TEST__RX_TIMEOUT_bp 2
#define UART__INTR_TEST__RX_TIMEOUT_bw 1
#define UART__INTR_TEST__RX_BREAK_ERR_bm 0x8
#define UART__INTR_TEST__RX_BREAK_ERR_bp 3
#define UART__INTR_TEST__RX_BREAK_ERR_bw 1
#define UART__INTR_TEST__RX_FRAME_ERR_bm 0x10
#define UART__INTR_TEST__RX_FRAME_ERR_bp 4
#define UART__INTR_TEST__RX_FRAME_ERR_bw 1
#define UART__INTR_TEST__RX_OVERFLOW_bm 0x20
#define UART__INTR_TEST__RX_OVERFLOW_bp 5
#define UART__INTR_TEST__RX_OVERFLOW_bw 1
#define UART__INTR_TEST__TX_DONE_bm 0x40
#define UART__INTR_TEST__TX_DONE_bp 6
#define UART__INTR_TEST__TX_DONE_bw 1
#define UART__INTR_TEST__RX_WATERMARK_bm 0x80
#define UART__INTR_TEST__RX_WATERMARK_bp 7
#define UART__INTR_TEST__RX_WATERMARK_bw 1
#define UART__INTR_TEST__TX_WATERMARK_bm 0x100
#define UART__INTR_TEST__TX_WATERMARK_bp 8
#define UART__INTR_TEST__TX_WATERMARK_bw 1

// reg - uart::INTR_STATUS
#define UART__INTR_STATUS__TX_EMPTY_bm 0x1
#define UART__INTR_STATUS__TX_EMPTY_bp 0
#define UART__INTR_STATUS__TX_EMPTY_bw 1
#define UART__INTR_STATUS__RX_PARITY_ERR_bm 0x2
#define UART__INTR_STATUS__RX_PARITY_ERR_bp 1
#define UART__INTR_STATUS__RX_PARITY_ERR_bw 1
#define UART__INTR_STATUS__RX_TIMEOUT_bm 0x4
#define UART__INTR_STATUS__RX_TIMEOUT_bp 2
#define UART__INTR_STATUS__RX_TIMEOUT_bw 1
#define UART__INTR_STATUS__RX_BREAK_ERR_bm 0x8
#define UART__INTR_STATUS__RX_BREAK_ERR_bp 3
#define UART__INTR_STATUS__RX_BREAK_ERR_bw 1
#define UART__INTR_STATUS__RX_FRAME_ERR_bm 0x10
#define UART__INTR_STATUS__RX_FRAME_ERR_bp 4
#define UART__INTR_STATUS__RX_FRAME_ERR_bw 1
#define UART__INTR_STATUS__RX_OVERFLOW_bm 0x20
#define UART__INTR_STATUS__RX_OVERFLOW_bp 5
#define UART__INTR_STATUS__RX_OVERFLOW_bw 1
#define UART__INTR_STATUS__TX_DONE_bm 0x40
#define UART__INTR_STATUS__TX_DONE_bp 6
#define UART__INTR_STATUS__TX_DONE_bw 1
#define UART__INTR_STATUS__RX_WATERMARK_bm 0x80
#define UART__INTR_STATUS__RX_WATERMARK_bp 7
#define UART__INTR_STATUS__RX_WATERMARK_bw 1
#define UART__INTR_STATUS__TX_WATERMARK_bm 0x100
#define UART__INTR_STATUS__TX_WATERMARK_bp 8
#define UART__INTR_STATUS__TX_WATERMARK_bw 1

// reg - uart::ALERT_TEST
#define UART__ALERT_TEST__FATAL_FAULT_bm 0x1
#define UART__ALERT_TEST__FATAL_FAULT_bp 0
#define UART__ALERT_TEST__FATAL_FAULT_bw 1

// addrmap - uart
typedef struct __attribute__ ((__packed__)) {
    uint32_t CTRL;
    uint32_t STATUS;
    uint32_t RDATA;
    uint32_t WDATA;
    uint32_t FIFO_CTRL;
    uint32_t FIFO_STATUS;
    uint32_t OVRD;
    uint32_t VAL;
    uint32_t TIMEOUT_CTRL;
    uint32_t INTR_STATE;
    uint32_t INTR_ENABLE;
    uint32_t INTR_TEST;
    uint32_t INTR_STATUS;
    uint32_t ALERT_TEST;
} uart_t;


static_assert(sizeof(uart_t) == 0x38, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* UART_REGS_H */
