[library.ip_uart]
location = /home/eda/workspace/aixsilicon_ip_repo/ip_uart
sync-uri = /home/eda/workspace/aixsilicon_ip_repo/ip_uart
sync-type = local
auto-sync = true

[library.lowrisc_libs]
location = /home/eda/workspace/aixsilicon_ip_repo/ips/lowrisc
sync-uri = /home/eda/workspace/aixsilicon_ip_repo/ips/lowrisc
sync-type = local
auto-sync = true
