
// This file was autogenerated by PeakRDL-uvm
package pqc_ral_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - pqc_csr::ID_VERSION
    class pqc_csr__ID_VERSION extends uvm_reg;
        rand uvm_reg_field ip_minor;
        rand uvm_reg_field ip_major;
        rand uvm_reg_field abi_version;
        rand uvm_reg_field ucode_version;

        function new(string name = "pqc_csr__ID_VERSION");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ip_minor = new("ip_minor");
            this.ip_minor.configure(this, 8, 0, "RO", 0, 'h1, 1, 1, 0);
            this.ip_major = new("ip_major");
            this.ip_major.configure(this, 8, 8, "RO", 0, 'h0, 1, 1, 0);
            this.abi_version = new("abi_version");
            this.abi_version.configure(this, 8, 16, "RO", 0, 'h10, 1, 1, 0);
            this.ucode_version = new("ucode_version");
            this.ucode_version.configure(this, 8, 24, "RO", 0, 'h1, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__ID_VERSION

    // reg - pqc_csr::CAPABILITY0
    class pqc_csr__CAPABILITY0 extends uvm_reg;
        rand uvm_reg_field algo_mask;
        rand uvm_reg_field kem_supported;
        rand uvm_reg_field dsa_supported;
        rand uvm_reg_field ntt_lanes;
        rand uvm_reg_field keccak_rounds;
        rand uvm_reg_field sca_level;
        rand uvm_reg_field hash_ml_dsa;
        rand uvm_reg_field sg_supported;
        rand uvm_reg_field pure_ml_dsa;
        rand uvm_reg_field deterministic_mode;
        rand uvm_reg_field hedged_mode;
        rand uvm_reg_field multi_queue;

        function new(string name = "pqc_csr__CAPABILITY0");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.algo_mask = new("algo_mask");
            this.algo_mask.configure(this, 6, 0, "RO", 1, 'h3f, 1, 1, 0);
            this.kem_supported = new("kem_supported");
            this.kem_supported.configure(this, 1, 6, "RO", 1, 'h1, 1, 1, 0);
            this.dsa_supported = new("dsa_supported");
            this.dsa_supported.configure(this, 1, 7, "RO", 1, 'h1, 1, 1, 0);
            this.ntt_lanes = new("ntt_lanes");
            this.ntt_lanes.configure(this, 2, 8, "RO", 1, 'h2, 1, 1, 0);
            this.keccak_rounds = new("keccak_rounds");
            this.keccak_rounds.configure(this, 2, 10, "RO", 1, 'h2, 1, 1, 0);
            this.sca_level = new("sca_level");
            this.sca_level.configure(this, 2, 12, "RO", 1, 'h1, 1, 1, 0);
            this.hash_ml_dsa = new("hash_ml_dsa");
            this.hash_ml_dsa.configure(this, 1, 14, "RO", 1, 'h0, 1, 1, 0);
            this.sg_supported = new("sg_supported");
            this.sg_supported.configure(this, 1, 15, "RO", 1, 'h0, 1, 1, 0);
            this.pure_ml_dsa = new("pure_ml_dsa");
            this.pure_ml_dsa.configure(this, 1, 16, "RO", 1, 'h1, 1, 1, 0);
            this.deterministic_mode = new("deterministic_mode");
            this.deterministic_mode.configure(this, 1, 17, "RO", 1, 'h1, 1, 1, 0);
            this.hedged_mode = new("hedged_mode");
            this.hedged_mode.configure(this, 1, 18, "RO", 1, 'h1, 1, 1, 0);
            this.multi_queue = new("multi_queue");
            this.multi_queue.configure(this, 1, 19, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__CAPABILITY0

    // reg - pqc_csr::CAPABILITY1
    class pqc_csr__CAPABILITY1 extends uvm_reg;
        rand uvm_reg_field local_sram_kib;
        rand uvm_reg_field dma_data_width;
        rand uvm_reg_field key_slot_num;
        rand uvm_reg_field pio_enabled;
        rand uvm_reg_field ecc_enabled;
        rand uvm_reg_field abi_minor;

        function new(string name = "pqc_csr__CAPABILITY1");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.local_sram_kib = new("local_sram_kib");
            this.local_sram_kib.configure(this, 8, 0, "RO", 1, 'h40, 1, 1, 0);
            this.dma_data_width = new("dma_data_width");
            this.dma_data_width.configure(this, 8, 8, "RO", 1, 'h80, 1, 1, 0);
            this.key_slot_num = new("key_slot_num");
            this.key_slot_num.configure(this, 8, 16, "RO", 1, 'h8, 1, 1, 0);
            this.pio_enabled = new("pio_enabled");
            this.pio_enabled.configure(this, 1, 24, "RO", 1, 'h1, 1, 1, 0);
            this.ecc_enabled = new("ecc_enabled");
            this.ecc_enabled.configure(this, 1, 25, "RO", 1, 'h1, 1, 1, 0);
            this.abi_minor = new("abi_minor");
            this.abi_minor.configure(this, 6, 26, "RO", 1, 'h1, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__CAPABILITY1

    // reg - pqc_csr::CTRL
    class pqc_csr__CTRL extends uvm_reg;
        rand uvm_reg_field enable;
        rand uvm_reg_field abort;
        rand uvm_reg_field zeroize;
        rand uvm_reg_field self_test;

        function new(string name = "pqc_csr__CTRL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.enable = new("enable");
            this.enable.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.abort = new("abort");
            this.abort.configure(this, 1, 1, "RW", 1, 'h0, 1, 1, 0);
            this.zeroize = new("zeroize");
            this.zeroize.configure(this, 1, 2, "RW", 1, 'h0, 1, 1, 0);
            this.self_test = new("self_test");
            this.self_test.configure(this, 1, 3, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__CTRL

    // reg - pqc_csr::STATUS
    class pqc_csr__STATUS extends uvm_reg;
        rand uvm_reg_field idle;
        rand uvm_reg_field busy;
        rand uvm_reg_field done;
        rand uvm_reg_field error;
        rand uvm_reg_field locked;

        function new(string name = "pqc_csr__STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.idle = new("idle");
            this.idle.configure(this, 1, 0, "RO", 1, 'h1, 1, 1, 0);
            this.busy = new("busy");
            this.busy.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            this.done = new("done");
            this.done.configure(this, 1, 2, "RO", 1, 'h0, 1, 1, 0);
            this.error = new("error");
            this.error.configure(this, 1, 3, "RO", 1, 'h0, 1, 1, 0);
            this.locked = new("locked");
            this.locked.configure(this, 1, 4, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__STATUS

    // reg - pqc_csr::COMMAND
    class pqc_csr__COMMAND extends uvm_reg;
        rand uvm_reg_field opcode;
        rand uvm_reg_field parameter_set;
        rand uvm_reg_field flags;
        rand uvm_reg_field abi;

        function new(string name = "pqc_csr__COMMAND");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.opcode = new("opcode");
            this.opcode.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
            this.parameter_set = new("parameter_set");
            this.parameter_set.configure(this, 4, 8, "RW", 0, 'h0, 1, 1, 0);
            this.flags = new("flags");
            this.flags.configure(this, 12, 12, "RW", 0, 'h0, 1, 1, 0);
            this.abi = new("abi");
            this.abi.configure(this, 8, 24, "RW", 0, 'h1, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__COMMAND

    // reg - pqc_csr::SRC0_ADDR_LO
    class pqc_csr__SRC0_ADDR_LO extends uvm_reg;
        rand uvm_reg_field src0_addr_lo;

        function new(string name = "pqc_csr__SRC0_ADDR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.src0_addr_lo = new("src0_addr_lo");
            this.src0_addr_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__SRC0_ADDR_LO

    // reg - pqc_csr::SRC0_ADDR_HI
    class pqc_csr__SRC0_ADDR_HI extends uvm_reg;
        rand uvm_reg_field src0_addr_hi;

        function new(string name = "pqc_csr__SRC0_ADDR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.src0_addr_hi = new("src0_addr_hi");
            this.src0_addr_hi.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__SRC0_ADDR_HI

    // reg - pqc_csr::SRC0_LEN_LO
    class pqc_csr__SRC0_LEN_LO extends uvm_reg;
        rand uvm_reg_field src0_len_lo;

        function new(string name = "pqc_csr__SRC0_LEN_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.src0_len_lo = new("src0_len_lo");
            this.src0_len_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__SRC0_LEN_LO

    // reg - pqc_csr::SRC0_LEN_HI
    class pqc_csr__SRC0_LEN_HI extends uvm_reg;
        rand uvm_reg_field src0_len_hi;

        function new(string name = "pqc_csr__SRC0_LEN_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.src0_len_hi = new("src0_len_hi");
            this.src0_len_hi.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__SRC0_LEN_HI

    // reg - pqc_csr::SRC1_ADDR_LO
    class pqc_csr__SRC1_ADDR_LO extends uvm_reg;
        rand uvm_reg_field src1_addr_lo;

        function new(string name = "pqc_csr__SRC1_ADDR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.src1_addr_lo = new("src1_addr_lo");
            this.src1_addr_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__SRC1_ADDR_LO

    // reg - pqc_csr::SRC1_ADDR_HI
    class pqc_csr__SRC1_ADDR_HI extends uvm_reg;
        rand uvm_reg_field src1_addr_hi;

        function new(string name = "pqc_csr__SRC1_ADDR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.src1_addr_hi = new("src1_addr_hi");
            this.src1_addr_hi.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__SRC1_ADDR_HI

    // reg - pqc_csr::SRC1_LEN_LO
    class pqc_csr__SRC1_LEN_LO extends uvm_reg;
        rand uvm_reg_field src1_len_lo;

        function new(string name = "pqc_csr__SRC1_LEN_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.src1_len_lo = new("src1_len_lo");
            this.src1_len_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__SRC1_LEN_LO

    // reg - pqc_csr::SRC1_LEN_HI
    class pqc_csr__SRC1_LEN_HI extends uvm_reg;
        rand uvm_reg_field src1_len_hi;

        function new(string name = "pqc_csr__SRC1_LEN_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.src1_len_hi = new("src1_len_hi");
            this.src1_len_hi.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__SRC1_LEN_HI

    // reg - pqc_csr::CONTEXT_ADDR_LO
    class pqc_csr__CONTEXT_ADDR_LO extends uvm_reg;
        rand uvm_reg_field context_addr_lo;

        function new(string name = "pqc_csr__CONTEXT_ADDR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.context_addr_lo = new("context_addr_lo");
            this.context_addr_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__CONTEXT_ADDR_LO

    // reg - pqc_csr::CONTEXT_ADDR_HI
    class pqc_csr__CONTEXT_ADDR_HI extends uvm_reg;
        rand uvm_reg_field context_addr_hi;

        function new(string name = "pqc_csr__CONTEXT_ADDR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.context_addr_hi = new("context_addr_hi");
            this.context_addr_hi.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__CONTEXT_ADDR_HI

    // reg - pqc_csr::ENTROPY_POLICY
    class pqc_csr__ENTROPY_POLICY extends uvm_reg;
        rand uvm_reg_field entropy_policy;

        function new(string name = "pqc_csr__ENTROPY_POLICY");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.entropy_policy = new("entropy_policy");
            this.entropy_policy.configure(this, 2, 0, "RW", 0, 'h2, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__ENTROPY_POLICY

    // reg - pqc_csr::DST0_ADDR_LO
    class pqc_csr__DST0_ADDR_LO extends uvm_reg;
        rand uvm_reg_field dst0_addr_lo;

        function new(string name = "pqc_csr__DST0_ADDR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dst0_addr_lo = new("dst0_addr_lo");
            this.dst0_addr_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DST0_ADDR_LO

    // reg - pqc_csr::DST0_ADDR_HI
    class pqc_csr__DST0_ADDR_HI extends uvm_reg;
        rand uvm_reg_field dst0_addr_hi;

        function new(string name = "pqc_csr__DST0_ADDR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dst0_addr_hi = new("dst0_addr_hi");
            this.dst0_addr_hi.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DST0_ADDR_HI

    // reg - pqc_csr::DST0_CAPACITY_LO
    class pqc_csr__DST0_CAPACITY_LO extends uvm_reg;
        rand uvm_reg_field dst0_capacity_lo;

        function new(string name = "pqc_csr__DST0_CAPACITY_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dst0_capacity_lo = new("dst0_capacity_lo");
            this.dst0_capacity_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DST0_CAPACITY_LO

    // reg - pqc_csr::DST0_CAPACITY_HI
    class pqc_csr__DST0_CAPACITY_HI extends uvm_reg;
        rand uvm_reg_field dst0_capacity_hi;

        function new(string name = "pqc_csr__DST0_CAPACITY_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dst0_capacity_hi = new("dst0_capacity_hi");
            this.dst0_capacity_hi.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DST0_CAPACITY_HI

    // reg - pqc_csr::DST1_ADDR_LO
    class pqc_csr__DST1_ADDR_LO extends uvm_reg;
        rand uvm_reg_field dst1_addr_lo;

        function new(string name = "pqc_csr__DST1_ADDR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dst1_addr_lo = new("dst1_addr_lo");
            this.dst1_addr_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DST1_ADDR_LO

    // reg - pqc_csr::DST1_ADDR_HI
    class pqc_csr__DST1_ADDR_HI extends uvm_reg;
        rand uvm_reg_field dst1_addr_hi;

        function new(string name = "pqc_csr__DST1_ADDR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dst1_addr_hi = new("dst1_addr_hi");
            this.dst1_addr_hi.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DST1_ADDR_HI

    // reg - pqc_csr::DST1_CAPACITY_LO
    class pqc_csr__DST1_CAPACITY_LO extends uvm_reg;
        rand uvm_reg_field dst1_capacity_lo;

        function new(string name = "pqc_csr__DST1_CAPACITY_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dst1_capacity_lo = new("dst1_capacity_lo");
            this.dst1_capacity_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DST1_CAPACITY_LO

    // reg - pqc_csr::DST1_CAPACITY_HI
    class pqc_csr__DST1_CAPACITY_HI extends uvm_reg;
        rand uvm_reg_field dst1_capacity_hi;

        function new(string name = "pqc_csr__DST1_CAPACITY_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dst1_capacity_hi = new("dst1_capacity_hi");
            this.dst1_capacity_hi.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DST1_CAPACITY_HI

    // reg - pqc_csr::COMPLETION_ADDR_LO
    class pqc_csr__COMPLETION_ADDR_LO extends uvm_reg;
        rand uvm_reg_field completion_addr_lo;

        function new(string name = "pqc_csr__COMPLETION_ADDR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.completion_addr_lo = new("completion_addr_lo");
            this.completion_addr_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__COMPLETION_ADDR_LO

    // reg - pqc_csr::COMPLETION_ADDR_HI
    class pqc_csr__COMPLETION_ADDR_HI extends uvm_reg;
        rand uvm_reg_field completion_addr_hi;

        function new(string name = "pqc_csr__COMPLETION_ADDR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.completion_addr_hi = new("completion_addr_hi");
            this.completion_addr_hi.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__COMPLETION_ADDR_HI

    // reg - pqc_csr::TIMEOUT_HINT
    class pqc_csr__TIMEOUT_HINT extends uvm_reg;
        rand uvm_reg_field timeout_hint;

        function new(string name = "pqc_csr__TIMEOUT_HINT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.timeout_hint = new("timeout_hint");
            this.timeout_hint.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__TIMEOUT_HINT

    // reg - pqc_csr::DESCRIPTOR_CRC
    class pqc_csr__DESCRIPTOR_CRC extends uvm_reg;
        rand uvm_reg_field descriptor_crc;

        function new(string name = "pqc_csr__DESCRIPTOR_CRC");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.descriptor_crc = new("descriptor_crc");
            this.descriptor_crc.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DESCRIPTOR_CRC

    // reg - pqc_csr::KEY_HANDLE
    class pqc_csr__KEY_HANDLE extends uvm_reg;
        rand uvm_reg_field slot_id;
        rand uvm_reg_field owner;
        rand uvm_reg_field generation;

        function new(string name = "pqc_csr__KEY_HANDLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_id = new("slot_id");
            this.slot_id.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
            this.owner = new("owner");
            this.owner.configure(this, 8, 8, "RW", 0, 'h0, 1, 1, 0);
            this.generation = new("generation");
            this.generation.configure(this, 16, 16, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__KEY_HANDLE

    // reg - pqc_csr::CONTEXT_LEN
    class pqc_csr__CONTEXT_LEN extends uvm_reg;
        rand uvm_reg_field context_len;

        function new(string name = "pqc_csr__CONTEXT_LEN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.context_len = new("context_len");
            this.context_len.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__CONTEXT_LEN

    // reg - pqc_csr::RESULT
    class pqc_csr__RESULT extends uvm_reg;
        rand uvm_reg_field verify_valid;
        rand uvm_reg_field verify_done;
        rand uvm_reg_field completion_tag;

        function new(string name = "pqc_csr__RESULT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.verify_valid = new("verify_valid");
            this.verify_valid.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.verify_done = new("verify_done");
            this.verify_done.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            this.completion_tag = new("completion_tag");
            this.completion_tag.configure(this, 30, 2, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__RESULT

    // reg - pqc_csr::ERROR_CODE
    class pqc_csr__ERROR_CODE extends uvm_reg;
        rand uvm_reg_field error_code;
        rand uvm_reg_field last_cmd_failed;

        function new(string name = "pqc_csr__ERROR_CODE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.error_code = new("error_code");
            this.error_code.configure(this, 6, 0, "RO", 1, 'h0, 1, 1, 0);
            this.last_cmd_failed = new("last_cmd_failed");
            this.last_cmd_failed.configure(this, 1, 6, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__ERROR_CODE

    // reg - pqc_csr::INTR_STATE
    class pqc_csr__INTR_STATE extends uvm_reg;
        rand uvm_reg_field done;
        rand uvm_reg_field error;
        rand uvm_reg_field rng_fault;
        rand uvm_reg_field tamper;
        rand uvm_reg_field self_test_fail;

        function new(string name = "pqc_csr__INTR_STATE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.done = new("done");
            this.done.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            this.error = new("error");
            this.error.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
            this.rng_fault = new("rng_fault");
            this.rng_fault.configure(this, 1, 2, "W1C", 1, 'h0, 1, 1, 0);
            this.tamper = new("tamper");
            this.tamper.configure(this, 1, 3, "W1C", 1, 'h0, 1, 1, 0);
            this.self_test_fail = new("self_test_fail");
            this.self_test_fail.configure(this, 1, 4, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__INTR_STATE

    // reg - pqc_csr::INTR_ENABLE
    class pqc_csr__INTR_ENABLE extends uvm_reg;
        rand uvm_reg_field done_en;
        rand uvm_reg_field error_en;
        rand uvm_reg_field rng_fault_en;
        rand uvm_reg_field tamper_en;
        rand uvm_reg_field self_test_fail_en;

        function new(string name = "pqc_csr__INTR_ENABLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.done_en = new("done_en");
            this.done_en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.error_en = new("error_en");
            this.error_en.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.rng_fault_en = new("rng_fault_en");
            this.rng_fault_en.configure(this, 1, 2, "RW", 0, 'h0, 1, 1, 0);
            this.tamper_en = new("tamper_en");
            this.tamper_en.configure(this, 1, 3, "RW", 0, 'h0, 1, 1, 0);
            this.self_test_fail_en = new("self_test_fail_en");
            this.self_test_fail_en.configure(this, 1, 4, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__INTR_ENABLE

    // reg - pqc_csr::INTR_TEST
    class pqc_csr__INTR_TEST extends uvm_reg;
        rand uvm_reg_field done_test;
        rand uvm_reg_field error_test;
        rand uvm_reg_field rng_fault_test;
        rand uvm_reg_field tamper_test;
        rand uvm_reg_field self_test_fail_test;

        function new(string name = "pqc_csr__INTR_TEST");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.done_test = new("done_test");
            this.done_test.configure(this, 1, 0, "RW", 1, 'h0, 1, 1, 0);
            this.error_test = new("error_test");
            this.error_test.configure(this, 1, 1, "RW", 1, 'h0, 1, 1, 0);
            this.rng_fault_test = new("rng_fault_test");
            this.rng_fault_test.configure(this, 1, 2, "RW", 1, 'h0, 1, 1, 0);
            this.tamper_test = new("tamper_test");
            this.tamper_test.configure(this, 1, 3, "RW", 1, 'h0, 1, 1, 0);
            this.self_test_fail_test = new("self_test_fail_test");
            this.self_test_fail_test.configure(this, 1, 4, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__INTR_TEST

    // reg - pqc_csr::ALERT_RECOVERABLE
    class pqc_csr__ALERT_RECOVERABLE extends uvm_reg;
        rand uvm_reg_field ecc_ded;
        rand uvm_reg_field dma_retry;
        rand uvm_reg_field perf_saturated;

        function new(string name = "pqc_csr__ALERT_RECOVERABLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ecc_ded = new("ecc_ded");
            this.ecc_ded.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            this.dma_retry = new("dma_retry");
            this.dma_retry.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
            this.perf_saturated = new("perf_saturated");
            this.perf_saturated.configure(this, 1, 2, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__ALERT_RECOVERABLE

    // reg - pqc_csr::ALERT_FATAL
    class pqc_csr__ALERT_FATAL extends uvm_reg;
        rand uvm_reg_field ecc_ued;
        rand uvm_reg_field tamper_fatal;
        rand uvm_reg_field selftest_fatal;
        rand uvm_reg_field integrity_fatal;
        rand uvm_reg_field retry_exhausted;

        function new(string name = "pqc_csr__ALERT_FATAL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ecc_ued = new("ecc_ued");
            this.ecc_ued.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            this.tamper_fatal = new("tamper_fatal");
            this.tamper_fatal.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
            this.selftest_fatal = new("selftest_fatal");
            this.selftest_fatal.configure(this, 1, 2, "W1C", 1, 'h0, 1, 1, 0);
            this.integrity_fatal = new("integrity_fatal");
            this.integrity_fatal.configure(this, 1, 3, "W1C", 1, 'h0, 1, 1, 0);
            this.retry_exhausted = new("retry_exhausted");
            this.retry_exhausted.configure(this, 1, 4, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__ALERT_FATAL

    // reg - pqc_csr::PERF_TOTAL_CYCLES
    class pqc_csr__PERF_TOTAL_CYCLES extends uvm_reg;
        rand uvm_reg_field total_cycles;

        function new(string name = "pqc_csr__PERF_TOTAL_CYCLES");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.total_cycles = new("total_cycles");
            this.total_cycles.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__PERF_TOTAL_CYCLES

    // reg - pqc_csr::PERF_KECCAK_CYCLES
    class pqc_csr__PERF_KECCAK_CYCLES extends uvm_reg;
        rand uvm_reg_field keccak_cycles;

        function new(string name = "pqc_csr__PERF_KECCAK_CYCLES");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.keccak_cycles = new("keccak_cycles");
            this.keccak_cycles.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__PERF_KECCAK_CYCLES

    // reg - pqc_csr::PERF_NTT_CYCLES
    class pqc_csr__PERF_NTT_CYCLES extends uvm_reg;
        rand uvm_reg_field ntt_cycles;

        function new(string name = "pqc_csr__PERF_NTT_CYCLES");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ntt_cycles = new("ntt_cycles");
            this.ntt_cycles.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__PERF_NTT_CYCLES

    // reg - pqc_csr::PERF_DMA_STALL
    class pqc_csr__PERF_DMA_STALL extends uvm_reg;
        rand uvm_reg_field dma_stall_cycles;

        function new(string name = "pqc_csr__PERF_DMA_STALL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dma_stall_cycles = new("dma_stall_cycles");
            this.dma_stall_cycles.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__PERF_DMA_STALL

    // reg - pqc_csr::PERF_CMD_COUNT
    class pqc_csr__PERF_CMD_COUNT extends uvm_reg;
        rand uvm_reg_field kem_ops;
        rand uvm_reg_field dsa_ops;

        function new(string name = "pqc_csr__PERF_CMD_COUNT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.kem_ops = new("kem_ops");
            this.kem_ops.configure(this, 16, 0, "RW", 1, 'h0, 1, 1, 0);
            this.dsa_ops = new("dsa_ops");
            this.dsa_ops.configure(this, 16, 16, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__PERF_CMD_COUNT

    // reg - pqc_csr::COMPLETION_COMMAND_ID
    class pqc_csr__COMPLETION_COMMAND_ID extends uvm_reg;
        rand uvm_reg_field command_id;

        function new(string name = "pqc_csr__COMPLETION_COMMAND_ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.command_id = new("command_id");
            this.command_id.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__COMPLETION_COMMAND_ID

    // reg - pqc_csr::COMPLETION_STATUS
    class pqc_csr__COMPLETION_STATUS extends uvm_reg;
        rand uvm_reg_field status;
        rand uvm_reg_field verify_valid;
        rand uvm_reg_field output0_len;

        function new(string name = "pqc_csr__COMPLETION_STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.status = new("status");
            this.status.configure(this, 3, 0, "RO", 1, 'h0, 1, 1, 0);
            this.verify_valid = new("verify_valid");
            this.verify_valid.configure(this, 1, 3, "RO", 1, 'h0, 1, 1, 0);
            this.output0_len = new("output0_len");
            this.output0_len.configure(this, 28, 4, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__COMPLETION_STATUS

    // reg - pqc_csr::COMPLETION_OUT_LEN
    class pqc_csr__COMPLETION_OUT_LEN extends uvm_reg;
        rand uvm_reg_field output1_len;

        function new(string name = "pqc_csr__COMPLETION_OUT_LEN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.output1_len = new("output1_len");
            this.output1_len.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__COMPLETION_OUT_LEN

    // reg - pqc_csr::COMPLETION_INFO
    class pqc_csr__COMPLETION_INFO extends uvm_reg;
        rand uvm_reg_field error_info;
        rand uvm_reg_field cycles_quantized;

        function new(string name = "pqc_csr__COMPLETION_INFO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.error_info = new("error_info");
            this.error_info.configure(this, 6, 0, "RO", 1, 'h0, 1, 1, 0);
            this.cycles_quantized = new("cycles_quantized");
            this.cycles_quantized.configure(this, 26, 6, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__COMPLETION_INFO

    // reg - pqc_csr::DOORBELL
    class pqc_csr__DOORBELL extends uvm_reg;
        rand uvm_reg_field doorbell;

        function new(string name = "pqc_csr__DOORBELL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.doorbell = new("doorbell");
            this.doorbell.configure(this, 1, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DOORBELL

    // reg - pqc_csr::DESC_ADDR_LO
    class pqc_csr__DESC_ADDR_LO extends uvm_reg;
        rand uvm_reg_field desc_addr_lo;

        function new(string name = "pqc_csr__DESC_ADDR_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.desc_addr_lo = new("desc_addr_lo");
            this.desc_addr_lo.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DESC_ADDR_LO

    // reg - pqc_csr::DESC_ADDR_HI
    class pqc_csr__DESC_ADDR_HI extends uvm_reg;
        rand uvm_reg_field desc_addr_hi;

        function new(string name = "pqc_csr__DESC_ADDR_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.desc_addr_hi = new("desc_addr_hi");
            this.desc_addr_hi.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__DESC_ADDR_HI

    // reg - pqc_csr::KEY_SLOT_CTRL
    class pqc_csr__KEY_SLOT_CTRL extends uvm_reg;
        rand uvm_reg_field slot_index;
        rand uvm_reg_field key_type;
        rand uvm_reg_field import_req;
        rand uvm_reg_field destroy_req;
        rand uvm_reg_field export_req;
        rand uvm_reg_field lock_req;

        function new(string name = "pqc_csr__KEY_SLOT_CTRL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_index = new("slot_index");
            this.slot_index.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
            this.key_type = new("key_type");
            this.key_type.configure(this, 3, 8, "RW", 0, 'h0, 1, 1, 0);
            this.import_req = new("import_req");
            this.import_req.configure(this, 1, 11, "RW", 1, 'h0, 1, 1, 0);
            this.destroy_req = new("destroy_req");
            this.destroy_req.configure(this, 1, 12, "RW", 1, 'h0, 1, 1, 0);
            this.export_req = new("export_req");
            this.export_req.configure(this, 1, 13, "RW", 1, 'h0, 1, 1, 0);
            this.lock_req = new("lock_req");
            this.lock_req.configure(this, 1, 14, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__KEY_SLOT_CTRL

    // reg - pqc_csr::KEY_SLOT_META
    class pqc_csr__KEY_SLOT_META extends uvm_reg;
        rand uvm_reg_field owner;
        rand uvm_reg_field algorithm;
        rand uvm_reg_field parameter_set;
        rand uvm_reg_field usage_mask;
        rand uvm_reg_field exportable;
        rand uvm_reg_field valid;
        rand uvm_reg_field locked;
        rand uvm_reg_field version;

        function new(string name = "pqc_csr__KEY_SLOT_META");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.owner = new("owner");
            this.owner.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
            this.algorithm = new("algorithm");
            this.algorithm.configure(this, 3, 8, "RO", 1, 'h0, 1, 1, 0);
            this.parameter_set = new("parameter_set");
            this.parameter_set.configure(this, 4, 11, "RO", 1, 'h0, 1, 1, 0);
            this.usage_mask = new("usage_mask");
            this.usage_mask.configure(this, 8, 15, "RO", 1, 'h0, 1, 1, 0);
            this.exportable = new("exportable");
            this.exportable.configure(this, 1, 23, "RO", 1, 'h0, 1, 1, 0);
            this.valid = new("valid");
            this.valid.configure(this, 1, 24, "RO", 1, 'h0, 1, 1, 0);
            this.locked = new("locked");
            this.locked.configure(this, 1, 25, "RO", 1, 'h0, 1, 1, 0);
            this.version = new("version");
            this.version.configure(this, 6, 26, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__KEY_SLOT_META

    // reg - pqc_csr::KEY_SLOT_GEN
    class pqc_csr__KEY_SLOT_GEN extends uvm_reg;
        rand uvm_reg_field generation;

        function new(string name = "pqc_csr__KEY_SLOT_GEN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.generation = new("generation");
            this.generation.configure(this, 16, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__KEY_SLOT_GEN

    // reg - pqc_csr::KEY_SLOT_DOMAIN
    class pqc_csr__KEY_SLOT_DOMAIN extends uvm_reg;
        rand uvm_reg_field domain;

        function new(string name = "pqc_csr__KEY_SLOT_DOMAIN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.domain = new("domain");
            this.domain.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__KEY_SLOT_DOMAIN

    // reg - pqc_csr::KEY_SLOT_MIRROR
    class pqc_csr__KEY_SLOT_MIRROR extends uvm_reg;
        rand uvm_reg_field slot_owner;
        rand uvm_reg_field slot_valid;

        function new(string name = "pqc_csr__KEY_SLOT_MIRROR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.slot_owner = new("slot_owner");
            this.slot_owner.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
            this.slot_valid = new("slot_valid");
            this.slot_valid.configure(this, 1, 8, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : pqc_csr__KEY_SLOT_MIRROR

    // addrmap - pqc_csr
    class pqc_csr extends uvm_reg_block;
        rand pqc_csr__ID_VERSION ID_VERSION;
        rand pqc_csr__CAPABILITY0 CAPABILITY0;
        rand pqc_csr__CAPABILITY1 CAPABILITY1;
        rand pqc_csr__CTRL CTRL;
        rand pqc_csr__STATUS STATUS;
        rand pqc_csr__COMMAND COMMAND;
        rand pqc_csr__SRC0_ADDR_LO SRC0_ADDR_LO;
        rand pqc_csr__SRC0_ADDR_HI SRC0_ADDR_HI;
        rand pqc_csr__SRC0_LEN_LO SRC0_LEN_LO;
        rand pqc_csr__SRC0_LEN_HI SRC0_LEN_HI;
        rand pqc_csr__SRC1_ADDR_LO SRC1_ADDR_LO;
        rand pqc_csr__SRC1_ADDR_HI SRC1_ADDR_HI;
        rand pqc_csr__SRC1_LEN_LO SRC1_LEN_LO;
        rand pqc_csr__SRC1_LEN_HI SRC1_LEN_HI;
        rand pqc_csr__CONTEXT_ADDR_LO CONTEXT_ADDR_LO;
        rand pqc_csr__CONTEXT_ADDR_HI CONTEXT_ADDR_HI;
        rand pqc_csr__ENTROPY_POLICY ENTROPY_POLICY;
        rand pqc_csr__DST0_ADDR_LO DST0_ADDR_LO;
        rand pqc_csr__DST0_ADDR_HI DST0_ADDR_HI;
        rand pqc_csr__DST0_CAPACITY_LO DST0_CAPACITY_LO;
        rand pqc_csr__DST0_CAPACITY_HI DST0_CAPACITY_HI;
        rand pqc_csr__DST1_ADDR_LO DST1_ADDR_LO;
        rand pqc_csr__DST1_ADDR_HI DST1_ADDR_HI;
        rand pqc_csr__DST1_CAPACITY_LO DST1_CAPACITY_LO;
        rand pqc_csr__DST1_CAPACITY_HI DST1_CAPACITY_HI;
        rand pqc_csr__COMPLETION_ADDR_LO COMPLETION_ADDR_LO;
        rand pqc_csr__COMPLETION_ADDR_HI COMPLETION_ADDR_HI;
        rand pqc_csr__TIMEOUT_HINT TIMEOUT_HINT;
        rand pqc_csr__DESCRIPTOR_CRC DESCRIPTOR_CRC;
        rand pqc_csr__KEY_HANDLE KEY_HANDLE;
        rand pqc_csr__CONTEXT_LEN CONTEXT_LEN;
        rand pqc_csr__RESULT RESULT;
        rand pqc_csr__ERROR_CODE ERROR_CODE;
        rand pqc_csr__INTR_STATE INTR_STATE;
        rand pqc_csr__INTR_ENABLE INTR_ENABLE;
        rand pqc_csr__INTR_TEST INTR_TEST;
        rand pqc_csr__ALERT_RECOVERABLE ALERT_RECOVERABLE;
        rand pqc_csr__ALERT_FATAL ALERT_FATAL;
        rand pqc_csr__PERF_TOTAL_CYCLES PERF_TOTAL_CYCLES;
        rand pqc_csr__PERF_KECCAK_CYCLES PERF_KECCAK_CYCLES;
        rand pqc_csr__PERF_NTT_CYCLES PERF_NTT_CYCLES;
        rand pqc_csr__PERF_DMA_STALL PERF_DMA_STALL;
        rand pqc_csr__PERF_CMD_COUNT PERF_CMD_COUNT;
        rand pqc_csr__COMPLETION_COMMAND_ID COMPLETION_COMMAND_ID;
        rand pqc_csr__COMPLETION_STATUS COMPLETION_STATUS;
        rand pqc_csr__COMPLETION_OUT_LEN COMPLETION_OUT_LEN;
        rand pqc_csr__COMPLETION_INFO COMPLETION_INFO;
        rand pqc_csr__DOORBELL DOORBELL;
        rand pqc_csr__DESC_ADDR_LO DESC_ADDR_LO;
        rand pqc_csr__DESC_ADDR_HI DESC_ADDR_HI;
        rand pqc_csr__KEY_SLOT_CTRL KEY_SLOT_CTRL;
        rand pqc_csr__KEY_SLOT_META KEY_SLOT_META;
        rand pqc_csr__KEY_SLOT_GEN KEY_SLOT_GEN;
        rand pqc_csr__KEY_SLOT_DOMAIN KEY_SLOT_DOMAIN;
        rand pqc_csr__KEY_SLOT_MIRROR KEY_SLOT_MIRROR[32];

        function new(string name = "pqc_csr");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.ID_VERSION = new("ID_VERSION");
            this.ID_VERSION.configure(this);

            this.ID_VERSION.build();
            this.default_map.add_reg(this.ID_VERSION, 'h0);
            this.CAPABILITY0 = new("CAPABILITY0");
            this.CAPABILITY0.configure(this);

            this.CAPABILITY0.build();
            this.default_map.add_reg(this.CAPABILITY0, 'h4);
            this.CAPABILITY1 = new("CAPABILITY1");
            this.CAPABILITY1.configure(this);

            this.CAPABILITY1.build();
            this.default_map.add_reg(this.CAPABILITY1, 'h8);
            this.CTRL = new("CTRL");
            this.CTRL.configure(this);

            this.CTRL.build();
            this.default_map.add_reg(this.CTRL, 'h10);
            this.STATUS = new("STATUS");
            this.STATUS.configure(this);

            this.STATUS.build();
            this.default_map.add_reg(this.STATUS, 'h14);
            this.COMMAND = new("COMMAND");
            this.COMMAND.configure(this);

            this.COMMAND.build();
            this.default_map.add_reg(this.COMMAND, 'h18);
            this.SRC0_ADDR_LO = new("SRC0_ADDR_LO");
            this.SRC0_ADDR_LO.configure(this);

            this.SRC0_ADDR_LO.build();
            this.default_map.add_reg(this.SRC0_ADDR_LO, 'h20);
            this.SRC0_ADDR_HI = new("SRC0_ADDR_HI");
            this.SRC0_ADDR_HI.configure(this);

            this.SRC0_ADDR_HI.build();
            this.default_map.add_reg(this.SRC0_ADDR_HI, 'h24);
            this.SRC0_LEN_LO = new("SRC0_LEN_LO");
            this.SRC0_LEN_LO.configure(this);

            this.SRC0_LEN_LO.build();
            this.default_map.add_reg(this.SRC0_LEN_LO, 'h28);
            this.SRC0_LEN_HI = new("SRC0_LEN_HI");
            this.SRC0_LEN_HI.configure(this);

            this.SRC0_LEN_HI.build();
            this.default_map.add_reg(this.SRC0_LEN_HI, 'h2c);
            this.SRC1_ADDR_LO = new("SRC1_ADDR_LO");
            this.SRC1_ADDR_LO.configure(this);

            this.SRC1_ADDR_LO.build();
            this.default_map.add_reg(this.SRC1_ADDR_LO, 'h30);
            this.SRC1_ADDR_HI = new("SRC1_ADDR_HI");
            this.SRC1_ADDR_HI.configure(this);

            this.SRC1_ADDR_HI.build();
            this.default_map.add_reg(this.SRC1_ADDR_HI, 'h34);
            this.SRC1_LEN_LO = new("SRC1_LEN_LO");
            this.SRC1_LEN_LO.configure(this);

            this.SRC1_LEN_LO.build();
            this.default_map.add_reg(this.SRC1_LEN_LO, 'h38);
            this.SRC1_LEN_HI = new("SRC1_LEN_HI");
            this.SRC1_LEN_HI.configure(this);

            this.SRC1_LEN_HI.build();
            this.default_map.add_reg(this.SRC1_LEN_HI, 'h3c);
            this.CONTEXT_ADDR_LO = new("CONTEXT_ADDR_LO");
            this.CONTEXT_ADDR_LO.configure(this);

            this.CONTEXT_ADDR_LO.build();
            this.default_map.add_reg(this.CONTEXT_ADDR_LO, 'h40);
            this.CONTEXT_ADDR_HI = new("CONTEXT_ADDR_HI");
            this.CONTEXT_ADDR_HI.configure(this);

            this.CONTEXT_ADDR_HI.build();
            this.default_map.add_reg(this.CONTEXT_ADDR_HI, 'h44);
            this.ENTROPY_POLICY = new("ENTROPY_POLICY");
            this.ENTROPY_POLICY.configure(this);

            this.ENTROPY_POLICY.build();
            this.default_map.add_reg(this.ENTROPY_POLICY, 'h48);
            this.DST0_ADDR_LO = new("DST0_ADDR_LO");
            this.DST0_ADDR_LO.configure(this);

            this.DST0_ADDR_LO.build();
            this.default_map.add_reg(this.DST0_ADDR_LO, 'h4c);
            this.DST0_ADDR_HI = new("DST0_ADDR_HI");
            this.DST0_ADDR_HI.configure(this);

            this.DST0_ADDR_HI.build();
            this.default_map.add_reg(this.DST0_ADDR_HI, 'h50);
            this.DST0_CAPACITY_LO = new("DST0_CAPACITY_LO");
            this.DST0_CAPACITY_LO.configure(this);

            this.DST0_CAPACITY_LO.build();
            this.default_map.add_reg(this.DST0_CAPACITY_LO, 'h54);
            this.DST0_CAPACITY_HI = new("DST0_CAPACITY_HI");
            this.DST0_CAPACITY_HI.configure(this);

            this.DST0_CAPACITY_HI.build();
            this.default_map.add_reg(this.DST0_CAPACITY_HI, 'h58);
            this.DST1_ADDR_LO = new("DST1_ADDR_LO");
            this.DST1_ADDR_LO.configure(this);

            this.DST1_ADDR_LO.build();
            this.default_map.add_reg(this.DST1_ADDR_LO, 'h5c);
            this.DST1_ADDR_HI = new("DST1_ADDR_HI");
            this.DST1_ADDR_HI.configure(this);

            this.DST1_ADDR_HI.build();
            this.default_map.add_reg(this.DST1_ADDR_HI, 'h60);
            this.DST1_CAPACITY_LO = new("DST1_CAPACITY_LO");
            this.DST1_CAPACITY_LO.configure(this);

            this.DST1_CAPACITY_LO.build();
            this.default_map.add_reg(this.DST1_CAPACITY_LO, 'h64);
            this.DST1_CAPACITY_HI = new("DST1_CAPACITY_HI");
            this.DST1_CAPACITY_HI.configure(this);

            this.DST1_CAPACITY_HI.build();
            this.default_map.add_reg(this.DST1_CAPACITY_HI, 'h68);
            this.COMPLETION_ADDR_LO = new("COMPLETION_ADDR_LO");
            this.COMPLETION_ADDR_LO.configure(this);

            this.COMPLETION_ADDR_LO.build();
            this.default_map.add_reg(this.COMPLETION_ADDR_LO, 'h6c);
            this.COMPLETION_ADDR_HI = new("COMPLETION_ADDR_HI");
            this.COMPLETION_ADDR_HI.configure(this);

            this.COMPLETION_ADDR_HI.build();
            this.default_map.add_reg(this.COMPLETION_ADDR_HI, 'h70);
            this.TIMEOUT_HINT = new("TIMEOUT_HINT");
            this.TIMEOUT_HINT.configure(this);

            this.TIMEOUT_HINT.build();
            this.default_map.add_reg(this.TIMEOUT_HINT, 'h74);
            this.DESCRIPTOR_CRC = new("DESCRIPTOR_CRC");
            this.DESCRIPTOR_CRC.configure(this);

            this.DESCRIPTOR_CRC.build();
            this.default_map.add_reg(this.DESCRIPTOR_CRC, 'h78);
            this.KEY_HANDLE = new("KEY_HANDLE");
            this.KEY_HANDLE.configure(this);

            this.KEY_HANDLE.build();
            this.default_map.add_reg(this.KEY_HANDLE, 'h7c);
            this.CONTEXT_LEN = new("CONTEXT_LEN");
            this.CONTEXT_LEN.configure(this);

            this.CONTEXT_LEN.build();
            this.default_map.add_reg(this.CONTEXT_LEN, 'h80);
            this.RESULT = new("RESULT");
            this.RESULT.configure(this);

            this.RESULT.build();
            this.default_map.add_reg(this.RESULT, 'h84);
            this.ERROR_CODE = new("ERROR_CODE");
            this.ERROR_CODE.configure(this);

            this.ERROR_CODE.build();
            this.default_map.add_reg(this.ERROR_CODE, 'h88);
            this.INTR_STATE = new("INTR_STATE");
            this.INTR_STATE.configure(this);

            this.INTR_STATE.build();
            this.default_map.add_reg(this.INTR_STATE, 'h90);
            this.INTR_ENABLE = new("INTR_ENABLE");
            this.INTR_ENABLE.configure(this);

            this.INTR_ENABLE.build();
            this.default_map.add_reg(this.INTR_ENABLE, 'h94);
            this.INTR_TEST = new("INTR_TEST");
            this.INTR_TEST.configure(this);

            this.INTR_TEST.build();
            this.default_map.add_reg(this.INTR_TEST, 'h98);
            this.ALERT_RECOVERABLE = new("ALERT_RECOVERABLE");
            this.ALERT_RECOVERABLE.configure(this);

            this.ALERT_RECOVERABLE.build();
            this.default_map.add_reg(this.ALERT_RECOVERABLE, 'ha0);
            this.ALERT_FATAL = new("ALERT_FATAL");
            this.ALERT_FATAL.configure(this);

            this.ALERT_FATAL.build();
            this.default_map.add_reg(this.ALERT_FATAL, 'ha4);
            this.PERF_TOTAL_CYCLES = new("PERF_TOTAL_CYCLES");
            this.PERF_TOTAL_CYCLES.configure(this);

            this.PERF_TOTAL_CYCLES.build();
            this.default_map.add_reg(this.PERF_TOTAL_CYCLES, 'h100);
            this.PERF_KECCAK_CYCLES = new("PERF_KECCAK_CYCLES");
            this.PERF_KECCAK_CYCLES.configure(this);

            this.PERF_KECCAK_CYCLES.build();
            this.default_map.add_reg(this.PERF_KECCAK_CYCLES, 'h104);
            this.PERF_NTT_CYCLES = new("PERF_NTT_CYCLES");
            this.PERF_NTT_CYCLES.configure(this);

            this.PERF_NTT_CYCLES.build();
            this.default_map.add_reg(this.PERF_NTT_CYCLES, 'h108);
            this.PERF_DMA_STALL = new("PERF_DMA_STALL");
            this.PERF_DMA_STALL.configure(this);

            this.PERF_DMA_STALL.build();
            this.default_map.add_reg(this.PERF_DMA_STALL, 'h10c);
            this.PERF_CMD_COUNT = new("PERF_CMD_COUNT");
            this.PERF_CMD_COUNT.configure(this);

            this.PERF_CMD_COUNT.build();
            this.default_map.add_reg(this.PERF_CMD_COUNT, 'h110);
            this.COMPLETION_COMMAND_ID = new("COMPLETION_COMMAND_ID");
            this.COMPLETION_COMMAND_ID.configure(this);

            this.COMPLETION_COMMAND_ID.build();
            this.default_map.add_reg(this.COMPLETION_COMMAND_ID, 'h1c0);
            this.COMPLETION_STATUS = new("COMPLETION_STATUS");
            this.COMPLETION_STATUS.configure(this);

            this.COMPLETION_STATUS.build();
            this.default_map.add_reg(this.COMPLETION_STATUS, 'h1c4);
            this.COMPLETION_OUT_LEN = new("COMPLETION_OUT_LEN");
            this.COMPLETION_OUT_LEN.configure(this);

            this.COMPLETION_OUT_LEN.build();
            this.default_map.add_reg(this.COMPLETION_OUT_LEN, 'h1c8);
            this.COMPLETION_INFO = new("COMPLETION_INFO");
            this.COMPLETION_INFO.configure(this);

            this.COMPLETION_INFO.build();
            this.default_map.add_reg(this.COMPLETION_INFO, 'h1cc);
            this.DOORBELL = new("DOORBELL");
            this.DOORBELL.configure(this);

            this.DOORBELL.build();
            this.default_map.add_reg(this.DOORBELL, 'h1d0);
            this.DESC_ADDR_LO = new("DESC_ADDR_LO");
            this.DESC_ADDR_LO.configure(this);

            this.DESC_ADDR_LO.build();
            this.default_map.add_reg(this.DESC_ADDR_LO, 'h1d4);
            this.DESC_ADDR_HI = new("DESC_ADDR_HI");
            this.DESC_ADDR_HI.configure(this);

            this.DESC_ADDR_HI.build();
            this.default_map.add_reg(this.DESC_ADDR_HI, 'h1d8);
            this.KEY_SLOT_CTRL = new("KEY_SLOT_CTRL");
            this.KEY_SLOT_CTRL.configure(this);

            this.KEY_SLOT_CTRL.build();
            this.default_map.add_reg(this.KEY_SLOT_CTRL, 'h200);
            this.KEY_SLOT_META = new("KEY_SLOT_META");
            this.KEY_SLOT_META.configure(this);

            this.KEY_SLOT_META.build();
            this.default_map.add_reg(this.KEY_SLOT_META, 'h204);
            this.KEY_SLOT_GEN = new("KEY_SLOT_GEN");
            this.KEY_SLOT_GEN.configure(this);

            this.KEY_SLOT_GEN.build();
            this.default_map.add_reg(this.KEY_SLOT_GEN, 'h208);
            this.KEY_SLOT_DOMAIN = new("KEY_SLOT_DOMAIN");
            this.KEY_SLOT_DOMAIN.configure(this);

            this.KEY_SLOT_DOMAIN.build();
            this.default_map.add_reg(this.KEY_SLOT_DOMAIN, 'h20c);
            foreach(this.KEY_SLOT_MIRROR[i0]) begin
                this.KEY_SLOT_MIRROR[i0] = new($sformatf("KEY_SLOT_MIRROR[%0d]", i0));
                this.KEY_SLOT_MIRROR[i0].configure(this);
                
                this.KEY_SLOT_MIRROR[i0].build();
                this.default_map.add_reg(this.KEY_SLOT_MIRROR[i0], 'h210 + i0*'h4);
            end
        endfunction : build
    endclass : pqc_csr

endpackage: pqc_ral_pkg
