schema_version: '2.0'
ip_name: apb_demux
interfaces:
- id: HLD.IF.EXT.APB_DEMUX.UPSTREAM
  name: s_apb
  scope: external
  protocol: APB4
  role: slave
  owner_module: HLD.MOD.L1.APB_DEMUX.TOP
  clock_domain: CLK_APB
  reset_domain: RST_APB_N
  req_ref:
  - LRS.INTF.APB_DEMUX.01.001
  - LRS.INTF.APB_DEMUX.01.002
  applicability:
    expr: 'true'
- id: HLD.IF.EXT.APB_DEMUX.DOWNSTREAM
  name: m_apb[N]
  scope: external
  protocol: APB4
  role: master
  owner_module: HLD.MOD.L1.APB_DEMUX.TOP
  clock_domain: CLK_APB
  reset_domain: RST_APB_N
  req_ref:
  - LRS.INTF.APB_DEMUX.02.001
  - LRS.INTF.APB_DEMUX.02.002
  applicability:
    expr: 'true'
