// Dedicated outbound custody for a key generated by the current command.
// start is internal-only; imported material cannot launch this controller.
module pqc_key_custody #(parameter int unsigned MAX_CYCLES=1000000)(
  input logic clk,rst_n,clear,start,
  input logic [31:0] transaction,epoch,handle,
  input logic [7:0] owner,domain,
  input logic [3:0] algo,pset,
  input logic [15:0] bytes,
  output logic busy,done,error,
  output logic header_valid,input logic header_ready,
  output logic [31:0] out_transaction,out_epoch,out_handle,
  output logic [7:0] out_owner,out_domain,
  output logic [3:0] out_algo,out_pset,
  output logic [15:0] out_bytes,
  output logic word_valid,input logic word_ready,
  output logic [31:0] word_data,output logic word_last,
  input logic ack_valid,output logic ack_ready,
  input logic [31:0] ack_transaction,ack_epoch,ack_handle,
  input logic [7:0] ack_owner,ack_domain,
  input logic [15:0] ack_bytes,input logic ack_success,
  output logic read_req,output logic [15:0] read_word,
  input logic read_valid,read_error,input logic [31:0] read_data
);
  typedef enum logic[3:0] {IDLE,HEADER,REQUEST,WAIT_DATA,STREAM,ACK,COMPLETE,FAILED} state_t;
  state_t state;
  logic [31:0] data_q,cycles;
  logic [15:0] index;
  logic ack_matches,enabled;
  assign enabled=rst_n && !clear;
  assign busy=state!=IDLE && state!=COMPLETE && state!=FAILED;
  assign done=enabled && state==COMPLETE;
  assign error=enabled && state==FAILED;
  assign header_valid=enabled && state==HEADER;
  assign word_valid=enabled && state==STREAM;
  assign word_data=word_valid ? data_q : 32'd0;
  assign word_last=word_valid && (32'(index)+1)*4==out_bytes;
  assign ack_ready=enabled && state==ACK;
  assign read_req=enabled && state==REQUEST;
  assign read_word=index;
  assign ack_matches=ack_transaction==out_transaction && ack_epoch==out_epoch &&
    ack_handle==out_handle && ack_owner==out_owner && ack_domain==out_domain && ack_bytes==out_bytes;
  always_ff @(posedge clk or negedge rst_n) begin
    if(!rst_n) begin
      state<=IDLE;data_q<=0;cycles<=0;index<=0;
      out_transaction<=0;out_epoch<=0;out_handle<=0;out_owner<=0;out_domain<=0;
      out_algo<=0;out_pset<=0;out_bytes<=0;
    end else if(clear) begin
      state<=IDLE;data_q<=0;cycles<=0;index<=0;
      out_transaction<=0;out_epoch<=0;out_handle<=0;out_owner<=0;out_domain<=0;
      out_algo<=0;out_pset<=0;out_bytes<=0;
    end else begin
      if(busy) cycles<=cycles+1'b1;
      if(busy && cycles>=MAX_CYCLES-1) begin state<=FAILED;data_q<=0;end
      else case(state)
        IDLE:if(start) begin
          out_transaction<=transaction;out_epoch<=epoch;out_handle<=handle;out_owner<=owner;out_domain<=domain;
          out_algo<=algo;out_pset<=pset;out_bytes<=bytes;cycles<=0;index<=0;
          state<=(bytes!=0 && bytes[1:0]==0) ? HEADER : FAILED;
        end
        HEADER:if(header_ready) state<=REQUEST;
        REQUEST:state<=WAIT_DATA;
        WAIT_DATA:if(read_error) begin data_q<=0;state<=FAILED;end
          else if(read_valid) begin data_q<=read_data;state<=STREAM;end
        STREAM:if(word_ready) begin
          data_q<=0;
          if(word_last) state<=ACK;else begin index<=index+1'b1;state<=REQUEST;end
        end
        // Wrong identity is drained without advancing; timeout still applies.
        ACK:if(ack_valid && ack_matches) state<=ack_success ? COMPLETE : FAILED;
        COMPLETE:state<=IDLE;
        FAILED:begin state<=FAILED;data_q<=0;end
        default:begin state<=FAILED;data_q<=0;end
      endcase
    end
  end
endmodule
