set: negative
configs:
- config_id: cfg_addr_width7_data_width32_slice_mode2_resp_stages1
  parameters:
    ADDR_WIDTH: 7
    DATA_WIDTH: 32
    SLICE_MODE: 2
    RESP_STAGES: 1
- config_id: cfg_addr_width33_data_width32_slice_mode2_resp_stages1
  parameters:
    ADDR_WIDTH: 33
    DATA_WIDTH: 32
    SLICE_MODE: 2
    RESP_STAGES: 1
- config_id: cfg_addr_width16_data_width7_slice_mode2_resp_stages1
  parameters:
    ADDR_WIDTH: 16
    DATA_WIDTH: 7
    SLICE_MODE: 2
    RESP_STAGES: 1
- config_id: cfg_addr_width16_data_width65_slice_mode2_resp_stages1
  parameters:
    ADDR_WIDTH: 16
    DATA_WIDTH: 65
    SLICE_MODE: 2
    RESP_STAGES: 1
- config_id: cfg_addr_width16_data_width32_slice_mode3_resp_stages1
  parameters:
    ADDR_WIDTH: 16
    DATA_WIDTH: 32
    SLICE_MODE: 3
    RESP_STAGES: 1
- config_id: cfg_addr_width16_data_width32_slice_mode2_resp_stages0
  parameters:
    ADDR_WIDTH: 16
    DATA_WIDTH: 32
    SLICE_MODE: 2
    RESP_STAGES: 0
- config_id: cfg_addr_width16_data_width32_slice_mode2_resp_stages3
  parameters:
    ADDR_WIDTH: 16
    DATA_WIDTH: 32
    SLICE_MODE: 2
    RESP_STAGES: 3
