schema_version: "1.0"
ip_name: x2p
links:
  - source_id: LLD.MOD.X2P.FE
    target_id: RTL.FILE.rtl/x2p_axi_frontend.sv
  - source_id: LLD.MOD.X2P.QB
    target_id: RTL.FILE.rtl/x2p_req_mgr.sv
  - source_id: LLD.MOD.X2P.SCH
    target_id: RTL.FILE.rtl/x2p_scheduler.sv
  - source_id: LLD.MOD.X2P.TE
    target_id: RTL.FILE.rtl/x2p_transfer_engine.sv
  - source_id: LLD.MOD.X2P.CDC
    target_id: RTL.FILE.rtl/x2p_cdc.sv
  - source_id: LLD.MOD.X2P.APB
    target_id: RTL.FILE.rtl/x2p_apb_engine.sv
  - source_id: LLD.MOD.X2P.RSP
    target_id: RTL.FILE.rtl/x2p_rsp_mgr.sv