// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef SPI_MASTER_REGS_H
#define SPI_MASTER_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - spi_master::ip_version
#define SPI_MASTER__IP_VERSION__VALUE_bm 0xffffffff
#define SPI_MASTER__IP_VERSION__VALUE_bp 0
#define SPI_MASTER__IP_VERSION__VALUE_bw 32
#define SPI_MASTER__IP_VERSION__VALUE_reset 0x10000

// reg - spi_master::capability
#define SPI_MASTER__CAPABILITY__VALUE_bm 0xffffff
#define SPI_MASTER__CAPABILITY__VALUE_bp 0
#define SPI_MASTER__CAPABILITY__VALUE_bw 24

// reg - spi_master::ctrl
#define SPI_MASTER__CTRL__ENABLE_bm 0x1
#define SPI_MASTER__CTRL__ENABLE_bp 0
#define SPI_MASTER__CTRL__ENABLE_bw 1
#define SPI_MASTER__CTRL__ENABLE_reset 0x0

// reg - spi_master::action
#define SPI_MASTER__ACTION__VALUE_bm 0x3f
#define SPI_MASTER__ACTION__VALUE_bp 0
#define SPI_MASTER__ACTION__VALUE_bw 6
#define SPI_MASTER__ACTION__VALUE_reset 0x0

// reg - spi_master::status
#define SPI_MASTER__STATUS__VALUE_bm 0x7fff
#define SPI_MASTER__STATUS__VALUE_bp 0
#define SPI_MASTER__STATUS__VALUE_bw 15

// reg - spi_master::fifo_level
#define SPI_MASTER__FIFO_LEVEL__VALUE_bm 0x7fffff
#define SPI_MASTER__FIFO_LEVEL__VALUE_bp 0
#define SPI_MASTER__FIFO_LEVEL__VALUE_bw 23

// reg - spi_master::watermark
#define SPI_MASTER__WATERMARK__TX_bm 0x1ff
#define SPI_MASTER__WATERMARK__TX_bp 0
#define SPI_MASTER__WATERMARK__TX_bw 9
#define SPI_MASTER__WATERMARK__TX_reset 0x0
#define SPI_MASTER__WATERMARK__RX_bm 0x3fe00
#define SPI_MASTER__WATERMARK__RX_bp 9
#define SPI_MASTER__WATERMARK__RX_bw 9
#define SPI_MASTER__WATERMARK__RX_reset 0x1

// reg - spi_master::wait_timeout
#define SPI_MASTER__WAIT_TIMEOUT__VALUE_bm 0xffffffff
#define SPI_MASTER__WAIT_TIMEOUT__VALUE_bp 0
#define SPI_MASTER__WAIT_TIMEOUT__VALUE_bw 32
#define SPI_MASTER__WAIT_TIMEOUT__VALUE_reset 0x0

// reg - spi_master::irq_state
#define SPI_MASTER__IRQ_STATE__SEG_DONE_bm 0x1
#define SPI_MASTER__IRQ_STATE__SEG_DONE_bp 0
#define SPI_MASTER__IRQ_STATE__SEG_DONE_bw 1
#define SPI_MASTER__IRQ_STATE__SEG_DONE_reset 0x0
#define SPI_MASTER__IRQ_STATE__XFER_DONE_bm 0x2
#define SPI_MASTER__IRQ_STATE__XFER_DONE_bp 1
#define SPI_MASTER__IRQ_STATE__XFER_DONE_bw 1
#define SPI_MASTER__IRQ_STATE__XFER_DONE_reset 0x0
#define SPI_MASTER__IRQ_STATE__ABORT_DONE_bm 0x4
#define SPI_MASTER__IRQ_STATE__ABORT_DONE_bp 2
#define SPI_MASTER__IRQ_STATE__ABORT_DONE_bw 1
#define SPI_MASTER__IRQ_STATE__ABORT_DONE_reset 0x0

// reg - spi_master::irq_enable
#define SPI_MASTER__IRQ_ENABLE__VALUE_bm 0x3f
#define SPI_MASTER__IRQ_ENABLE__VALUE_bp 0
#define SPI_MASTER__IRQ_ENABLE__VALUE_bw 6
#define SPI_MASTER__IRQ_ENABLE__VALUE_reset 0x0

// reg - spi_master::irq_raw
#define SPI_MASTER__IRQ_RAW__VALUE_bm 0x3f
#define SPI_MASTER__IRQ_RAW__VALUE_bp 0
#define SPI_MASTER__IRQ_RAW__VALUE_bw 6

// reg - spi_master::error_status
#define SPI_MASTER__ERROR_STATUS__APB_ACCESS_bm 0x1
#define SPI_MASTER__ERROR_STATUS__APB_ACCESS_bp 0
#define SPI_MASTER__ERROR_STATUS__APB_ACCESS_bw 1
#define SPI_MASTER__ERROR_STATUS__APB_ACCESS_reset 0x0
#define SPI_MASTER__ERROR_STATUS__TX_FULL_WRITE_bm 0x2
#define SPI_MASTER__ERROR_STATUS__TX_FULL_WRITE_bp 1
#define SPI_MASTER__ERROR_STATUS__TX_FULL_WRITE_bw 1
#define SPI_MASTER__ERROR_STATUS__TX_FULL_WRITE_reset 0x0
#define SPI_MASTER__ERROR_STATUS__RX_EMPTY_READ_bm 0x4
#define SPI_MASTER__ERROR_STATUS__RX_EMPTY_READ_bp 2
#define SPI_MASTER__ERROR_STATUS__RX_EMPTY_READ_bw 1
#define SPI_MASTER__ERROR_STATUS__RX_EMPTY_READ_reset 0x0
#define SPI_MASTER__ERROR_STATUS__CMD_FULL_PUSH_bm 0x8
#define SPI_MASTER__ERROR_STATUS__CMD_FULL_PUSH_bp 3
#define SPI_MASTER__ERROR_STATUS__CMD_FULL_PUSH_bw 1
#define SPI_MASTER__ERROR_STATUS__CMD_FULL_PUSH_reset 0x0
#define SPI_MASTER__ERROR_STATUS__CMD_INVALID_bm 0x10
#define SPI_MASTER__ERROR_STATUS__CMD_INVALID_bp 4
#define SPI_MASTER__ERROR_STATUS__CMD_INVALID_bw 1
#define SPI_MASTER__ERROR_STATUS__CMD_INVALID_reset 0x0
#define SPI_MASTER__ERROR_STATUS__CONFIG_WRITE_bm 0x20
#define SPI_MASTER__ERROR_STATUS__CONFIG_WRITE_bp 5
#define SPI_MASTER__ERROR_STATUS__CONFIG_WRITE_bw 1
#define SPI_MASTER__ERROR_STATUS__CONFIG_WRITE_reset 0x0
#define SPI_MASTER__ERROR_STATUS__TX_RESOURCE_bm 0x40
#define SPI_MASTER__ERROR_STATUS__TX_RESOURCE_bp 6
#define SPI_MASTER__ERROR_STATUS__TX_RESOURCE_bw 1
#define SPI_MASTER__ERROR_STATUS__TX_RESOURCE_reset 0x0
#define SPI_MASTER__ERROR_STATUS__RX_RESOURCE_bm 0x80
#define SPI_MASTER__ERROR_STATUS__RX_RESOURCE_bp 7
#define SPI_MASTER__ERROR_STATUS__RX_RESOURCE_bw 1
#define SPI_MASTER__ERROR_STATUS__RX_RESOURCE_reset 0x0
#define SPI_MASTER__ERROR_STATUS__WAIT_TIMEOUT_bm 0x100
#define SPI_MASTER__ERROR_STATUS__WAIT_TIMEOUT_bp 8
#define SPI_MASTER__ERROR_STATUS__WAIT_TIMEOUT_bw 1
#define SPI_MASTER__ERROR_STATUS__WAIT_TIMEOUT_reset 0x0
#define SPI_MASTER__ERROR_STATUS__CS_MISMATCH_bm 0x200
#define SPI_MASTER__ERROR_STATUS__CS_MISMATCH_bp 9
#define SPI_MASTER__ERROR_STATUS__CS_MISMATCH_bw 1
#define SPI_MASTER__ERROR_STATUS__CS_MISMATCH_reset 0x0

// reg - spi_master::txdata
#define SPI_MASTER__TXDATA__VALUE_bm 0xffffffff
#define SPI_MASTER__TXDATA__VALUE_bp 0
#define SPI_MASTER__TXDATA__VALUE_bw 32
#define SPI_MASTER__TXDATA__VALUE_reset 0x0

// reg - spi_master::rxdata
#define SPI_MASTER__RXDATA__VALUE_bm 0xffffffff
#define SPI_MASTER__RXDATA__VALUE_bp 0
#define SPI_MASTER__RXDATA__VALUE_bw 32

// reg - spi_master::cmd_cfg
#define SPI_MASTER__CMD_CFG__CSID_bm 0x7
#define SPI_MASTER__CMD_CFG__CSID_bp 0
#define SPI_MASTER__CMD_CFG__CSID_bw 3
#define SPI_MASTER__CMD_CFG__CSID_reset 0x0
#define SPI_MASTER__CMD_CFG__OP_bm 0x70
#define SPI_MASTER__CMD_CFG__OP_bp 4
#define SPI_MASTER__CMD_CFG__OP_bw 3
#define SPI_MASTER__CMD_CFG__OP_reset 0x0
#define SPI_MASTER__CMD_CFG__FRAME_BITS_bm 0x3f00
#define SPI_MASTER__CMD_CFG__FRAME_BITS_bp 8
#define SPI_MASTER__CMD_CFG__FRAME_BITS_bw 6
#define SPI_MASTER__CMD_CFG__FRAME_BITS_reset 0x8
#define SPI_MASTER__CMD_CFG__KEEP_CS_bm 0x10000
#define SPI_MASTER__CMD_CFG__KEEP_CS_bp 16
#define SPI_MASTER__CMD_CFG__KEEP_CS_bw 1
#define SPI_MASTER__CMD_CFG__KEEP_CS_reset 0x0
#define SPI_MASTER__CMD_CFG__ALLOW_STALL_bm 0x20000
#define SPI_MASTER__CMD_CFG__ALLOW_STALL_bp 17
#define SPI_MASTER__CMD_CFG__ALLOW_STALL_bw 1
#define SPI_MASTER__CMD_CFG__ALLOW_STALL_reset 0x0

// reg - spi_master::cmd_len
#define SPI_MASTER__CMD_LEN__VALUE_bm 0xffff
#define SPI_MASTER__CMD_LEN__VALUE_bp 0
#define SPI_MASTER__CMD_LEN__VALUE_bw 16
#define SPI_MASTER__CMD_LEN__VALUE_reset 0x1

// reg - spi_master::cmd_tag
#define SPI_MASTER__CMD_TAG__VALUE_bm 0xffff
#define SPI_MASTER__CMD_TAG__VALUE_bp 0
#define SPI_MASTER__CMD_TAG__VALUE_bw 16
#define SPI_MASTER__CMD_TAG__VALUE_reset 0x0

// reg - spi_master::cmd_push
#define SPI_MASTER__CMD_PUSH__VALUE_bm 0x1
#define SPI_MASTER__CMD_PUSH__VALUE_bp 0
#define SPI_MASTER__CMD_PUSH__VALUE_bw 1
#define SPI_MASTER__CMD_PUSH__VALUE_reset 0x0

// reg - spi_master::active_tag
#define SPI_MASTER__ACTIVE_TAG__VALUE_bm 0xffff
#define SPI_MASTER__ACTIVE_TAG__VALUE_bp 0
#define SPI_MASTER__ACTIVE_TAG__VALUE_bw 16

// reg - spi_master::progress
#define SPI_MASTER__PROGRESS__VALUE_bm 0xffff
#define SPI_MASTER__PROGRESS__VALUE_bp 0
#define SPI_MASTER__PROGRESS__VALUE_bw 16

// reg - spi_master::last_done_tag
#define SPI_MASTER__LAST_DONE_TAG__VALUE_bm 0xffff
#define SPI_MASTER__LAST_DONE_TAG__VALUE_bp 0
#define SPI_MASTER__LAST_DONE_TAG__VALUE_bw 16

// reg - spi_master::done_count
#define SPI_MASTER__DONE_COUNT__VALUE_bm 0xffffffff
#define SPI_MASTER__DONE_COUNT__VALUE_bp 0
#define SPI_MASTER__DONE_COUNT__VALUE_bw 32

// reg - spi_master::active_info
#define SPI_MASTER__ACTIVE_INFO__CSID_bm 0x7
#define SPI_MASTER__ACTIVE_INFO__CSID_bp 0
#define SPI_MASTER__ACTIVE_INFO__CSID_bw 3
#define SPI_MASTER__ACTIVE_INFO__OP_bm 0x70
#define SPI_MASTER__ACTIVE_INFO__OP_bp 4
#define SPI_MASTER__ACTIVE_INFO__OP_bw 3
#define SPI_MASTER__ACTIVE_INFO__VALID_bm 0x100
#define SPI_MASTER__ACTIVE_INFO__VALID_bp 8
#define SPI_MASTER__ACTIVE_INFO__VALID_bw 1

// reg - spi_master::cs_slot::cfg
#define SPI_MASTER__CS_SLOT__CFG__CPOL_bm 0x1
#define SPI_MASTER__CS_SLOT__CFG__CPOL_bp 0
#define SPI_MASTER__CS_SLOT__CFG__CPOL_bw 1
#define SPI_MASTER__CS_SLOT__CFG__CPOL_reset 0x0
#define SPI_MASTER__CS_SLOT__CFG__CPHA_bm 0x2
#define SPI_MASTER__CS_SLOT__CFG__CPHA_bp 1
#define SPI_MASTER__CS_SLOT__CFG__CPHA_bw 1
#define SPI_MASTER__CS_SLOT__CFG__CPHA_reset 0x0
#define SPI_MASTER__CS_SLOT__CFG__LSB_FIRST_bm 0x4
#define SPI_MASTER__CS_SLOT__CFG__LSB_FIRST_bp 2
#define SPI_MASTER__CS_SLOT__CFG__LSB_FIRST_bw 1
#define SPI_MASTER__CS_SLOT__CFG__LSB_FIRST_reset 0x0
#define SPI_MASTER__CS_SLOT__CFG__LOOPBACK_bm 0x8
#define SPI_MASTER__CS_SLOT__CFG__LOOPBACK_bp 3
#define SPI_MASTER__CS_SLOT__CFG__LOOPBACK_bw 1
#define SPI_MASTER__CS_SLOT__CFG__LOOPBACK_reset 0x0

// reg - spi_master::cs_slot::clkdiv
#define SPI_MASTER__CS_SLOT__CLKDIV__VALUE_bm 0xffff
#define SPI_MASTER__CS_SLOT__CLKDIV__VALUE_bp 0
#define SPI_MASTER__CS_SLOT__CLKDIV__VALUE_bw 16
#define SPI_MASTER__CS_SLOT__CLKDIV__VALUE_reset 0x1

// reg - spi_master::cs_slot::timing0
#define SPI_MASTER__CS_SLOT__TIMING0__SETUP_bm 0xffff
#define SPI_MASTER__CS_SLOT__TIMING0__SETUP_bp 0
#define SPI_MASTER__CS_SLOT__TIMING0__SETUP_bw 16
#define SPI_MASTER__CS_SLOT__TIMING0__SETUP_reset 0x0
#define SPI_MASTER__CS_SLOT__TIMING0__HOLD_TIME_bm 0xffff0000
#define SPI_MASTER__CS_SLOT__TIMING0__HOLD_TIME_bp 16
#define SPI_MASTER__CS_SLOT__TIMING0__HOLD_TIME_bw 16
#define SPI_MASTER__CS_SLOT__TIMING0__HOLD_TIME_reset 0x0

// reg - spi_master::cs_slot::timing1
#define SPI_MASTER__CS_SLOT__TIMING1__IDLE_bm 0xffff
#define SPI_MASTER__CS_SLOT__TIMING1__IDLE_bp 0
#define SPI_MASTER__CS_SLOT__TIMING1__IDLE_bw 16
#define SPI_MASTER__CS_SLOT__TIMING1__IDLE_reset 0x0
#define SPI_MASTER__CS_SLOT__TIMING1__FRAME_GAP_bm 0xffff0000
#define SPI_MASTER__CS_SLOT__TIMING1__FRAME_GAP_bp 16
#define SPI_MASTER__CS_SLOT__TIMING1__FRAME_GAP_bw 16
#define SPI_MASTER__CS_SLOT__TIMING1__FRAME_GAP_reset 0x0

// reg - spi_master::cs_slot::dummy
#define SPI_MASTER__CS_SLOT__DUMMY__VALUE_bm 0xffffffff
#define SPI_MASTER__CS_SLOT__DUMMY__VALUE_bp 0
#define SPI_MASTER__CS_SLOT__DUMMY__VALUE_bw 32
#define SPI_MASTER__CS_SLOT__DUMMY__VALUE_reset 0xffffffff

// regfile - spi_master::cs_slot
typedef struct __attribute__ ((__packed__)) {
    uint32_t cfg;
    uint32_t clkdiv;
    uint32_t timing0;
    uint32_t timing1;
    uint32_t dummy;
    uint8_t RESERVED_14_1f[0xc];
} spi_master__cs_slot__stride20_t;

// addrmap - spi_master
typedef struct __attribute__ ((__packed__)) {
    uint32_t ip_version;
    uint32_t capability;
    uint32_t ctrl;
    uint32_t action;
    uint32_t status;
    uint32_t fifo_level;
    uint32_t watermark;
    uint32_t wait_timeout;
    uint32_t irq_state;
    uint32_t irq_enable;
    uint32_t irq_raw;
    uint32_t error_status;
    uint32_t txdata;
    uint32_t rxdata;
    uint32_t cmd_cfg;
    uint32_t cmd_len;
    uint32_t cmd_tag;
    uint32_t cmd_push;
    uint32_t active_tag;
    uint32_t progress;
    uint32_t last_done_tag;
    uint32_t done_count;
    uint32_t active_info;
    uint8_t RESERVED_5c_ff[0xa4];
    spi_master__cs_slot__stride20_t cs[8];
} spi_master_t;


static_assert(sizeof(spi_master_t) == 0x200, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* SPI_MASTER_REGS_H */
