schema_version: '2.0'
ip_name: apb_demux
trace_type: req_to_test
links:
- source_id: LRS.CFG.APB_DEMUX.01.001
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CFG.APB_DEMUX.01.002
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CFG.APB_DEMUX.01.003
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CFG.APB_DEMUX.02.001
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CFG.APB_DEMUX.02.002
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CFG.APB_DEMUX.03.001
  target_id: TC.FUNC.APB_DEMUX.06.001.REMAP
  status: linked
  confidence: high
- source_id: LRS.CFG.APB_DEMUX.03.002
  target_id: TC.FUNC.APB_DEMUX.07.001.TOUT
  status: linked
  confidence: high
- source_id: LRS.CFG.APB_DEMUX.03.003
  target_id: TC.FUNC.APB_DEMUX.07.001.TOUT
  status: linked
  confidence: high
- source_id: LRS.CFG.APB_DEMUX.03.004
  target_id: TC.FUNC.APB_DEMUX.08.001.OREG
  status: linked
  confidence: high
- source_id: LRS.CFG.APB_DEMUX.04.001
  target_id: TC.INTF.APB_DEMUX.01.001.SAN
  status: linked
  confidence: high
- source_id: LRS.CFG.APB_DEMUX.04.001
  target_id: TC.INTF.APB_DEMUX.01.002.APB4
  status: linked
  confidence: high
- source_id: LRS.CONS.APB_DEMUX.01.001
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CONS.APB_DEMUX.01.002
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CONS.APB_DEMUX.01.003
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CONS.APB_DEMUX.01.004
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CONS.APB_DEMUX.01.005
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CONS.APB_DEMUX.01.006
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CONS.APB_DEMUX.02.001
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.CONS.APB_DEMUX.02.002
  target_id: TC.FUNC.APB_DEMUX.01.002.PARAM
  status: linked
  confidence: high
- source_id: LRS.DFX.APB_DEMUX.01.001
  target_id: TC.DFX.APB_DEMUX.01.001.ASSERT
  status: linked
  confidence: high
- source_id: LRS.DFX.APB_DEMUX.01.002
  target_id: TC.DFX.APB_DEMUX.01.001.ASSERT
  status: linked
  confidence: high
- source_id: LRS.DFX.APB_DEMUX.01.003
  target_id: TC.DFX.APB_DEMUX.01.001.ASSERT
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.01.001
  target_id: ASR.APB_DEMUX.01.003
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.01.001
  target_id: TC.FUNC.APB_DEMUX.01.001.DEC
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.01.002
  target_id: ASR.APB_DEMUX.01.003
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.01.002
  target_id: TC.FUNC.APB_DEMUX.01.001.DEC
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.01.003
  target_id: ASR.APB_DEMUX.01.003
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.01.003
  target_id: TC.FUNC.APB_DEMUX.01.001.DEC
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.01.004
  target_id: ASR.APB_DEMUX.01.003
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.01.004
  target_id: TC.FUNC.APB_DEMUX.01.001.DEC
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.01.005
  target_id: ASR.APB_DEMUX.01.003
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.01.005
  target_id: TC.FUNC.APB_DEMUX.01.001.DEC
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.02.001
  target_id: ASR.APB_DEMUX.01.001
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.02.001
  target_id: ASR.APB_DEMUX.01.005
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.02.001
  target_id: TC.FUNC.APB_DEMUX.02.001.PSEL
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.02.002
  target_id: ASR.APB_DEMUX.01.001
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.02.002
  target_id: ASR.APB_DEMUX.01.005
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.02.002
  target_id: TC.FUNC.APB_DEMUX.02.001.PSEL
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.02.003
  target_id: ASR.APB_DEMUX.01.001
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.02.003
  target_id: ASR.APB_DEMUX.01.005
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.02.003
  target_id: TC.FUNC.APB_DEMUX.02.001.PSEL
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.03.001
  target_id: ASR.APB_DEMUX.01.002
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.03.001
  target_id: TC.FUNC.APB_DEMUX.03.001.WAIT
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.03.002
  target_id: ASR.APB_DEMUX.01.002
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.03.002
  target_id: TC.FUNC.APB_DEMUX.03.001.WAIT
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.04.001
  target_id: TC.FUNC.APB_DEMUX.04.001.ERR
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.04.002
  target_id: TC.FUNC.APB_DEMUX.04.001.ERR
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.05.001
  target_id: ASR.APB_DEMUX.01.004
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.05.001
  target_id: TC.FUNC.APB_DEMUX.05.001.MISS
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.05.002
  target_id: ASR.APB_DEMUX.01.004
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.05.002
  target_id: TC.FUNC.APB_DEMUX.05.001.MISS
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.05.003
  target_id: ASR.APB_DEMUX.01.004
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.05.003
  target_id: TC.FUNC.APB_DEMUX.05.001.MISS
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.06.001
  target_id: TC.FUNC.APB_DEMUX.06.001.REMAP
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.06.002
  target_id: TC.FUNC.APB_DEMUX.06.001.REMAP
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.07.001
  target_id: TC.FUNC.APB_DEMUX.07.001.TOUT
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.07.002
  target_id: TC.FUNC.APB_DEMUX.07.001.TOUT
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.08.001
  target_id: TC.FUNC.APB_DEMUX.08.001.OREG
  status: linked
  confidence: high
- source_id: LRS.FUNC.APB_DEMUX.08.002
  target_id: TC.FUNC.APB_DEMUX.08.001.OREG
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.01.001
  target_id: TC.INTF.APB_DEMUX.01.001.SAN
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.01.001
  target_id: TC.INTF.APB_DEMUX.01.002.APB4
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.01.002
  target_id: TC.INTF.APB_DEMUX.01.001.SAN
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.01.002
  target_id: TC.INTF.APB_DEMUX.01.002.APB4
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.02.001
  target_id: TC.INTF.APB_DEMUX.01.001.SAN
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.02.001
  target_id: TC.INTF.APB_DEMUX.01.002.APB4
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.02.002
  target_id: TC.INTF.APB_DEMUX.01.001.SAN
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.02.002
  target_id: TC.INTF.APB_DEMUX.01.002.APB4
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.03.001
  target_id: TC.INTF.APB_DEMUX.01.001.SAN
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.03.001
  target_id: TC.INTF.APB_DEMUX.01.002.APB4
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.03.002
  target_id: TC.INTF.APB_DEMUX.01.001.SAN
  status: linked
  confidence: high
- source_id: LRS.INTF.APB_DEMUX.03.002
  target_id: TC.INTF.APB_DEMUX.01.002.APB4
  status: linked
  confidence: high
- source_id: LRS.PERF.APB_DEMUX.01.001
  target_id: ASR.APB_DEMUX.01.002
  status: linked
  confidence: high
- source_id: LRS.PERF.APB_DEMUX.01.001
  target_id: TC.FUNC.APB_DEMUX.03.001.WAIT
  status: linked
  confidence: high
- source_id: LRS.PERF.APB_DEMUX.02.001
  target_id: TC.DFX.APB_DEMUX.01.001.ASSERT
  status: linked
  confidence: high
- source_id: LRS.PERF.APB_DEMUX.03.001
  target_id: TC.DFX.APB_DEMUX.01.001.ASSERT
  status: linked
  confidence: high
- source_id: LRS.RESET.APB_DEMUX.01.001
  target_id: ASR.APB_DEMUX.01.006
  status: linked
  confidence: high
- source_id: LRS.RESET.APB_DEMUX.01.001
  target_id: TC.RESET.APB_DEMUX.01.001.RST
  status: linked
  confidence: high
- source_id: LRS.RESET.APB_DEMUX.02.001
  target_id: ASR.APB_DEMUX.01.006
  status: linked
  confidence: high
- source_id: LRS.RESET.APB_DEMUX.02.001
  target_id: TC.RESET.APB_DEMUX.01.001.RST
  status: linked
  confidence: high
- source_id: LRS.RESET.APB_DEMUX.02.002
  target_id: ASR.APB_DEMUX.01.006
  status: linked
  confidence: high
- source_id: LRS.RESET.APB_DEMUX.02.002
  target_id: TC.RESET.APB_DEMUX.01.001.RST
  status: linked
  confidence: high
- source_id: LRS.RESET.APB_DEMUX.02.003
  target_id: ASR.APB_DEMUX.01.006
  status: linked
  confidence: high
- source_id: LRS.RESET.APB_DEMUX.02.003
  target_id: TC.RESET.APB_DEMUX.01.001.RST
  status: linked
  confidence: high
gap_analysis:
  unlinked_sources: []
  unlinked_targets: []
