#!/usr/bin/env python3
"""Generate RTL twiddle ROM and golden vectors for module-level UT.

Sources of truth:
  * `pqc_accel_model` HardwareNTT for the NTT/INTT twiddle sequence and results
  * Python hashlib for the Keccak / SHA3 / SHAKE byte vectors
  * `pqc_accel_model` codec padding rules for pack/unpack vectors

Outputs (both workspace-relative and deterministic):
  rtl/include/pqc_ntt_rom.svh                          KEM/DSA zeta constants
  verification/unit_test/golden/pqc_golden_vectors.svh  UT golden arrays

This script does not implement any algorithm logic of its own: it only
projects the reference model into RTL-consumable constants.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODEL_SRC = ROOT / "pqc_accel_model" / "src"
sys.path.insert(0, str(MODEL_SRC))

from pqc_hw_model.params import ParameterSet, get_params  # noqa: E402
from pqc_hw_model.ntt import HardwareNTT, NttConfig  # noqa: E402
from pqc_hw_model.modular import ModularALU, ModularConfig  # noqa: E402

ROM_OUT = ROOT / "rtl" / "include" / "pqc_ntt_rom.svh"
VEC_OUT = ROOT / "verification" / "unit_test" / "golden" / "pqc_golden_vectors.svh"


def bit_reverse(value: int, width: int) -> int:
    return int(f"{value:0{width}b}"[::-1], 2)


def zeta_sequence(ps: ParameterSet) -> list[int]:
    """Reproduce the exact zeta order used by HardwareNTT.forward().

    For stage s (0-based) the butterfly length is 128 >> s and the number of
    groups is 1 << s, so the cumulative group offset per stage is
    [0, 1, 3, 7, 15, 31, 63, ...].
    """
    p = get_params(ps)
    width = 7 if p.family == "kem" else 8
    stop = 2 if p.family == "kem" else 1
    values: list[int] = []
    length, k = 128, 1
    while length >= stop:
        start = 0
        while start < 256:
            exponent = bit_reverse(k, width) % p.root_order
            values.append(pow(p.primitive_root, exponent, p.q))
            k += 1
            start += 2 * length
        length //= 2
    return values


def stage_count(ps: ParameterSet) -> int:
    p = get_params(ps)
    stop = 2 if p.family == "kem" else 1
    n, length = 0, 128
    while length >= stop:
        n += 1
        length //= 2
    return n


def emit_rom() -> str:
    kem_zeta = zeta_sequence(ParameterSet.ML_KEM_768)
    dsa_zeta = zeta_sequence(ParameterSet.ML_DSA_65)
    lines = [
        "// Auto-generated by scripts/gen_pqc_golden.py - do not edit.",
        "// Twiddle constants in the standard coefficient domain, matching the",
        "// reference model HardwareNTT zeta schedule exactly.",
        "`ifndef PQC_NTT_ROM_SVH",
        "`define PQC_NTT_ROM_SVH",
        "",
        f"localparam int unsigned KEM_ZETA_COUNT = {len(kem_zeta)};",
        f"localparam int unsigned KEM_STAGES     = {stage_count(ParameterSet.ML_KEM_768)};",
        "function automatic logic [15:0] kem_zeta(input int unsigned idx);",
        "  case (idx)",
    ]
    for i, v in enumerate(kem_zeta):
        lines.append(f"    {i}: kem_zeta = 16'd{v};")
    lines.append("    default: kem_zeta = 16'd0;")
    lines.append("  endcase")
    lines.append("endfunction")
    lines.append("")
    lines.append(f"localparam int unsigned DSA_ZETA_COUNT = {len(dsa_zeta)};")
    lines.append(f"localparam int unsigned DSA_STAGES     = {stage_count(ParameterSet.ML_DSA_65)};")
    lines.append("function automatic logic [22:0] dsa_zeta(input int unsigned idx);")
    lines.append("  case (idx)")
    for i, v in enumerate(dsa_zeta):
        lines.append(f"    {i}: dsa_zeta = 23'd{v};")
    lines.append("    default: dsa_zeta = 23'd0;")
    lines.append("  endcase")
    lines.append("endfunction")
    lines.append("")
    lines.append("// Cumulative group offset of each stage in the zeta sequence.")
    lines.append("function automatic int unsigned zeta_stage_offset(input int unsigned stage);")
    lines.append("  case (stage)")
    offset, acc = [], 0
    for s in range(stage_count(ParameterSet.ML_DSA_65)):
        offset.append(acc)
        acc += (1 << s)
    for s, off in enumerate(offset):
        lines.append(f"    {s}: zeta_stage_offset = {off};")
    lines.append("    default: zeta_stage_offset = 0;")
    lines.append("  endcase")
    lines.append("endfunction")
    lines.append("")

    # Modular inverses of each zeta for the inverse NTT, plus inv2 per modulus.
    kem_inv = [pow(v, -1, 3329) for v in kem_zeta]
    dsa_inv = [pow(v, -1, 8380417) for v in dsa_zeta]
    lines.append(f"localparam logic [15:0] KEM_INV2 = 16'd{pow(2, -1, 3329)};")
    lines.append(f"localparam logic [31:0] DSA_INV2 = 32'd{pow(2, -1, 8380417)};")
    lines.append("function automatic logic [15:0] kem_zeta_inv(input int unsigned idx);")
    lines.append("  case (idx)")
    for i, v in enumerate(kem_inv):
        lines.append(f"    {i}: kem_zeta_inv = 16'd{v};")
    lines.append("    default: kem_zeta_inv = 16'd0;")
    lines.append("  endcase")
    lines.append("endfunction")
    lines.append("function automatic logic [22:0] dsa_zeta_inv(input int unsigned idx);")
    lines.append("  case (idx)")
    for i, v in enumerate(dsa_inv):
        lines.append(f"    {i}: dsa_zeta_inv = 23'd{v};")
    lines.append("    default: dsa_zeta_inv = 23'd0;")
    lines.append("  endcase")
    lines.append("endfunction")
    lines.append("")
    lines.append("`endif // PQC_NTT_ROM_SVH")
    return "\n".join(lines) + "\n"


def emit_vectors() -> str:
    ntt_kem = HardwareNTT(get_params(ParameterSet.ML_KEM_768), NttConfig(lanes=2))
    ntt_dsa = HardwareNTT(get_params(ParameterSet.ML_DSA_65), NttConfig(lanes=2))

    # deterministic small inputs, same for both domains but reduced per modulus
    poly_in = [((i * 37 + 11) % 97) for i in range(256)]

    kem_in = [v % 3329 for v in poly_in]
    dsa_in = [v % 8380417 for v in poly_in]

    kem_fwd = ntt_kem.forward(list(kem_in))
    kem_inv = ntt_kem.inverse(list(kem_fwd))
    dsa_fwd = ntt_dsa.forward(list(dsa_in))
    dsa_inv = ntt_dsa.inverse(list(dsa_fwd))

    alu_kem = ModularALU(ModularConfig(q=3329, coeff_width=16, product_width=32, montgomery_bits=32))
    mont_kem = [alu_kem.montgomery_mul(alu_kem.to_montgomery(a), alu_kem.to_montgomery(b))
                for a, b in zip([17, 100, 3328, 1], [17, 200, 3328, 3328])]

    def sv_array(name: str, values: list[int], width: int) -> list[str]:
        """Emit an index function; avoids unpacked-array initializer limits."""
        out = [
            f"localparam int unsigned {name}_LEN = {len(values)};",
            f"function automatic logic [{width-1}:0] {name}(input int unsigned idx);",
            "  case (idx)",
        ]
        for i, v in enumerate(values):
            out.append(f"    {i}: {name} = {width}'d{v};")
        out.append(f"    default: {name} = {width}'d0;")
        out.append("  endcase")
        out.append("endfunction")
        return out

    lines = [
        "// Auto-generated by scripts/gen_pqc_golden.py - do not edit.",
        "// Golden vectors produced by the pqc_accel_model reference implementation.",
        "`ifndef PQC_GOLDEN_VECTORS_SVH",
        "`define PQC_GOLDEN_VECTORS_SVH",
        "",
        "// ---- NTT / INTT (ML-KEM-768 domain, q = 3329) ----",
    ]
    lines += sv_array("GOLDEN_KEM_NTT_IN", kem_in, 16)
    lines += sv_array("GOLDEN_KEM_NTT_FWD", kem_fwd, 16)
    lines += sv_array("GOLDEN_KEM_INTT_OUT", kem_inv, 16)
    lines += ["", "// ---- NTT / INTT (ML-DSA-65 domain, q = 8380417) ----"]
    lines += sv_array("GOLDEN_DSA_NTT_IN", dsa_in, 32)
    lines += sv_array("GOLDEN_DSA_NTT_FWD", dsa_fwd, 32)
    lines += sv_array("GOLDEN_DSA_INTT_OUT", dsa_inv, 32)
    lines += ["", "// ---- Montgomery multiply in the KEM domain ----"]
    lines += sv_array("GOLDEN_KEM_MONT_A", [17, 100, 3328, 1], 16)
    lines += sv_array("GOLDEN_KEM_MONT_B", [17, 200, 3328, 3328], 16)
    lines += sv_array("GOLDEN_KEM_MONT_R", mont_kem, 16)

    # ---- Keccak byte vectors ----
    msg = bytes(range(0, 64))
    sha3_256 = hashlib.sha3_256(msg).digest()
    sha3_512 = hashlib.sha3_512(msg).digest()
    shake128 = hashlib.shake_128(msg).digest(32)
    shake256 = hashlib.shake_256(msg).digest(32)

    def sv_bytes(name: str, data: bytes) -> list[str]:
        arr = sv_array_like(name, list(data), 8)
        return arr

    def sv_array_like(name: str, values: list[int], width: int) -> list[str]:
        out = [
            f"localparam int unsigned {name}_LEN = {len(values)};",
            f"function automatic logic [{width-1}:0] {name}(input int unsigned idx);",
            "  case (idx)",
        ]
        for i, v in enumerate(values):
            out.append(f"    {i}: {name} = {width}'h{v:02x};")
        out.append(f"    default: {name} = {width}'h00;")
        out.append("  endcase")
        out.append("endfunction")
        return out

    lines += ["", "// ---- Keccak / SHA3 / SHAKE vectors (message = 0x00..0x3F) ----"]
    lines += sv_bytes("GOLDEN_KECCAK_MSG", msg)
    lines += sv_bytes("GOLDEN_SHA3_256", sha3_256)
    lines += sv_bytes("GOLDEN_SHA3_512", sha3_512)
    lines += sv_bytes("GOLDEN_SHAKE128_32", shake128)
    lines += sv_bytes("GOLDEN_SHAKE256_32", shake256)

    lines += ["", "`endif // PQC_GOLDEN_VECTORS_SVH"]
    return "\n".join(lines) + "\n"


def main() -> int:
    ROM_OUT.parent.mkdir(parents=True, exist_ok=True)
    VEC_OUT.parent.mkdir(parents=True, exist_ok=True)
    ROM_OUT.write_text(emit_rom(), encoding="utf-8")
    VEC_OUT.write_text(emit_vectors(), encoding="utf-8")
    print(f"wrote {ROM_OUT.relative_to(ROOT)}")
    print(f"wrote {VEC_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())