// Generated by scripts/regenerate_native_csr.py; do not edit.
module gpio_csr_checks(input logic clk, arst_n, external_wr_ack, external_rd_ack,
                       external_pending, decoded_req_is_external);
  always @(posedge clk) begin
    if (arst_n) begin
                assert_bad_ext_wr_ack: assert(!external_wr_ack || (external_pending | decoded_req_is_external))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert(!external_rd_ack || (external_pending | decoded_req_is_external))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
    end
  end
endmodule
bind gpio_csr gpio_csr_checks u_gpio_csr_checks(.*);
