// UART dependency closure over unified-repo common libs
../ips/lowrisc/top/0.1.0/rtl/top_pkg.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_pkg.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_mubi_pkg.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_util_pkg.sv
../ips/lowrisc/tlul/0.1.0/rtl/tlul_pkg.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_subreg_pkg.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_alert_pkg.sv
../ips/lowrisc/top/0.1.0/rtl/top_racl_pkg.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_count_pkg.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_alert_receiver.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_alert_sender.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_buf.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_cdc_rand_delay.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_count.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_diff_decode.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_fifo_sync.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_fifo_sync_cnt.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_flop.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_flop_2sync.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_intr_hw.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_onehot_check.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_onehot_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_reg_we_check.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_sec_anchor_buf.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_sec_anchor_flop.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_22_16_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_22_16_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_28_22_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_28_22_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_39_32_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_39_32_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_64_57_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_64_57_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_72_64_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_72_64_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_hamming_22_16_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_hamming_22_16_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_hamming_39_32_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_hamming_39_32_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_hamming_72_64_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_hamming_72_64_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_hamming_76_68_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_hamming_76_68_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_22_16_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_22_16_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_28_22_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_28_22_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_39_32_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_39_32_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_64_57_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_64_57_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_72_64_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_72_64_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_hamming_22_16_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_hamming_22_16_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_hamming_39_32_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_hamming_39_32_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_hamming_72_64_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_hamming_72_64_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_hamming_76_68_dec.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_secded_inv_hamming_76_68_enc.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_subreg.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_subreg_arb.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_subreg_ext.sv
../ips/lowrisc/prim/0.1.0/rtl/prim_xnor2.sv
../ips/lowrisc/tlul/0.1.0/rtl/tlul_adapter_reg.sv
../ips/lowrisc/tlul/0.1.0/rtl/tlul_assert.sv
../ips/lowrisc/tlul/0.1.0/rtl/tlul_cmd_intg_chk.sv
../ips/lowrisc/tlul/0.1.0/rtl/tlul_data_integ_dec.sv
../ips/lowrisc/tlul/0.1.0/rtl/tlul_data_integ_enc.sv
../ips/lowrisc/tlul/0.1.0/rtl/tlul_err.sv
../ips/lowrisc/tlul/0.1.0/rtl/tlul_rsp_intg_gen.sv
