
// This file was autogenerated by PeakRDL-uvm
package spi_master_ral;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - spi_master::ip_version
    class spi_master__ip_version extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__ip_version");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 0, 'h10000, 1, 1, 0);
        endfunction : build
    endclass : spi_master__ip_version

    // reg - spi_master::capability
    class spi_master__capability extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__capability");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 24, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : spi_master__capability

    // reg - spi_master::ctrl
    class spi_master__ctrl extends uvm_reg;
        rand uvm_reg_field enable;

        function new(string name = "spi_master__ctrl");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.enable = new("enable");
            this.enable.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__ctrl

    // reg - spi_master::action
    class spi_master__action extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__action");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 6, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__action

    // reg - spi_master::status
    class spi_master__status extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__status");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 15, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : spi_master__status

    // reg - spi_master::fifo_level
    class spi_master__fifo_level extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__fifo_level");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 23, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : spi_master__fifo_level

    // reg - spi_master::watermark
    class spi_master__watermark extends uvm_reg;
        rand uvm_reg_field tx;
        rand uvm_reg_field rx;

        function new(string name = "spi_master__watermark");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.tx = new("tx");
            this.tx.configure(this, 9, 0, "RW", 0, 'h0, 1, 1, 0);
            this.rx = new("rx");
            this.rx.configure(this, 9, 9, "RW", 0, 'h1, 1, 1, 0);
        endfunction : build
    endclass : spi_master__watermark

    // reg - spi_master::wait_timeout
    class spi_master__wait_timeout extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__wait_timeout");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__wait_timeout

    // reg - spi_master::irq_state
    class spi_master__irq_state extends uvm_reg;
        rand uvm_reg_field seg_done;
        rand uvm_reg_field xfer_done;
        rand uvm_reg_field abort_done;

        function new(string name = "spi_master__irq_state");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.seg_done = new("seg_done");
            this.seg_done.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            this.xfer_done = new("xfer_done");
            this.xfer_done.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
            this.abort_done = new("abort_done");
            this.abort_done.configure(this, 1, 2, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__irq_state

    // reg - spi_master::irq_enable
    class spi_master__irq_enable extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__irq_enable");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 6, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__irq_enable

    // reg - spi_master::irq_raw
    class spi_master__irq_raw extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__irq_raw");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 6, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : spi_master__irq_raw

    // reg - spi_master::error_status
    class spi_master__error_status extends uvm_reg;
        rand uvm_reg_field apb_access;
        rand uvm_reg_field tx_full_write;
        rand uvm_reg_field rx_empty_read;
        rand uvm_reg_field cmd_full_push;
        rand uvm_reg_field cmd_invalid;
        rand uvm_reg_field config_write;
        rand uvm_reg_field tx_resource;
        rand uvm_reg_field rx_resource;
        rand uvm_reg_field wait_timeout;
        rand uvm_reg_field cs_mismatch;

        function new(string name = "spi_master__error_status");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.apb_access = new("apb_access");
            this.apb_access.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            this.tx_full_write = new("tx_full_write");
            this.tx_full_write.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
            this.rx_empty_read = new("rx_empty_read");
            this.rx_empty_read.configure(this, 1, 2, "W1C", 1, 'h0, 1, 1, 0);
            this.cmd_full_push = new("cmd_full_push");
            this.cmd_full_push.configure(this, 1, 3, "W1C", 1, 'h0, 1, 1, 0);
            this.cmd_invalid = new("cmd_invalid");
            this.cmd_invalid.configure(this, 1, 4, "W1C", 1, 'h0, 1, 1, 0);
            this.config_write = new("config_write");
            this.config_write.configure(this, 1, 5, "W1C", 1, 'h0, 1, 1, 0);
            this.tx_resource = new("tx_resource");
            this.tx_resource.configure(this, 1, 6, "W1C", 1, 'h0, 1, 1, 0);
            this.rx_resource = new("rx_resource");
            this.rx_resource.configure(this, 1, 7, "W1C", 1, 'h0, 1, 1, 0);
            this.wait_timeout = new("wait_timeout");
            this.wait_timeout.configure(this, 1, 8, "W1C", 1, 'h0, 1, 1, 0);
            this.cs_mismatch = new("cs_mismatch");
            this.cs_mismatch.configure(this, 1, 9, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__error_status

    // reg - spi_master::txdata
    class spi_master__txdata extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__txdata");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__txdata

    // reg - spi_master::rxdata
    class spi_master__rxdata extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__rxdata");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : spi_master__rxdata

    // reg - spi_master::cmd_cfg
    class spi_master__cmd_cfg extends uvm_reg;
        rand uvm_reg_field csid;
        rand uvm_reg_field op;
        rand uvm_reg_field frame_bits;
        rand uvm_reg_field keep_cs;
        rand uvm_reg_field allow_stall;

        function new(string name = "spi_master__cmd_cfg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.csid = new("csid");
            this.csid.configure(this, 3, 0, "RW", 0, 'h0, 1, 1, 0);
            this.op = new("op");
            this.op.configure(this, 3, 4, "RW", 0, 'h0, 1, 1, 0);
            this.frame_bits = new("frame_bits");
            this.frame_bits.configure(this, 6, 8, "RW", 0, 'h8, 1, 1, 0);
            this.keep_cs = new("keep_cs");
            this.keep_cs.configure(this, 1, 16, "RW", 0, 'h0, 1, 1, 0);
            this.allow_stall = new("allow_stall");
            this.allow_stall.configure(this, 1, 17, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__cmd_cfg

    // reg - spi_master::cmd_len
    class spi_master__cmd_len extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__cmd_len");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RW", 0, 'h1, 1, 1, 0);
        endfunction : build
    endclass : spi_master__cmd_len

    // reg - spi_master::cmd_tag
    class spi_master__cmd_tag extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__cmd_tag");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__cmd_tag

    // reg - spi_master::cmd_push
    class spi_master__cmd_push extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__cmd_push");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__cmd_push

    // reg - spi_master::active_tag
    class spi_master__active_tag extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__active_tag");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : spi_master__active_tag

    // reg - spi_master::progress
    class spi_master__progress extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__progress");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : spi_master__progress

    // reg - spi_master::last_done_tag
    class spi_master__last_done_tag extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__last_done_tag");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : spi_master__last_done_tag

    // reg - spi_master::done_count
    class spi_master__done_count extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__done_count");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : spi_master__done_count

    // reg - spi_master::active_info
    class spi_master__active_info extends uvm_reg;
        rand uvm_reg_field csid;
        rand uvm_reg_field op;
        rand uvm_reg_field valid;

        function new(string name = "spi_master__active_info");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.csid = new("csid");
            this.csid.configure(this, 3, 0, "RO", 1, 'h0, 0, 1, 0);
            this.op = new("op");
            this.op.configure(this, 3, 4, "RO", 1, 'h0, 0, 1, 0);
            this.valid = new("valid");
            this.valid.configure(this, 1, 8, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : spi_master__active_info

    // reg - spi_master::cs_slot::cfg
    class spi_master__cs_slot__cfg extends uvm_reg;
        rand uvm_reg_field cpol;
        rand uvm_reg_field cpha;
        rand uvm_reg_field lsb_first;
        rand uvm_reg_field loopback;

        function new(string name = "spi_master__cs_slot__cfg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.cpol = new("cpol");
            this.cpol.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.cpha = new("cpha");
            this.cpha.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.lsb_first = new("lsb_first");
            this.lsb_first.configure(this, 1, 2, "RW", 0, 'h0, 1, 1, 0);
            this.loopback = new("loopback");
            this.loopback.configure(this, 1, 3, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__cs_slot__cfg

    // reg - spi_master::cs_slot::clkdiv
    class spi_master__cs_slot__clkdiv extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__cs_slot__clkdiv");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RW", 0, 'h1, 1, 1, 0);
        endfunction : build
    endclass : spi_master__cs_slot__clkdiv

    // reg - spi_master::cs_slot::timing0
    class spi_master__cs_slot__timing0 extends uvm_reg;
        rand uvm_reg_field setup;
        rand uvm_reg_field hold_time;

        function new(string name = "spi_master__cs_slot__timing0");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.setup = new("setup");
            this.setup.configure(this, 16, 0, "RW", 0, 'h0, 1, 1, 0);
            this.hold_time = new("hold_time");
            this.hold_time.configure(this, 16, 16, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__cs_slot__timing0

    // reg - spi_master::cs_slot::timing1
    class spi_master__cs_slot__timing1 extends uvm_reg;
        rand uvm_reg_field idle;
        rand uvm_reg_field frame_gap;

        function new(string name = "spi_master__cs_slot__timing1");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.idle = new("idle");
            this.idle.configure(this, 16, 0, "RW", 0, 'h0, 1, 1, 0);
            this.frame_gap = new("frame_gap");
            this.frame_gap.configure(this, 16, 16, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : spi_master__cs_slot__timing1

    // reg - spi_master::cs_slot::dummy
    class spi_master__cs_slot__dummy extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "spi_master__cs_slot__dummy");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 0, 'hffffffff, 1, 1, 0);
        endfunction : build
    endclass : spi_master__cs_slot__dummy

    // regfile - spi_master::cs_slot
    class spi_master__cs_slot extends uvm_reg_block;
        rand spi_master__cs_slot__cfg cfg;
        rand spi_master__cs_slot__clkdiv clkdiv;
        rand spi_master__cs_slot__timing0 timing0;
        rand spi_master__cs_slot__timing1 timing1;
        rand spi_master__cs_slot__dummy dummy;

        function new(string name = "spi_master__cs_slot");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.cfg = new("cfg");
            this.cfg.configure(this);

            this.cfg.build();
            this.default_map.add_reg(this.cfg, 'h0);
            this.clkdiv = new("clkdiv");
            this.clkdiv.configure(this);

            this.clkdiv.build();
            this.default_map.add_reg(this.clkdiv, 'h4);
            this.timing0 = new("timing0");
            this.timing0.configure(this);

            this.timing0.build();
            this.default_map.add_reg(this.timing0, 'h8);
            this.timing1 = new("timing1");
            this.timing1.configure(this);

            this.timing1.build();
            this.default_map.add_reg(this.timing1, 'hc);
            this.dummy = new("dummy");
            this.dummy.configure(this);

            this.dummy.build();
            this.default_map.add_reg(this.dummy, 'h10);
        endfunction : build
    endclass : spi_master__cs_slot

    // addrmap - spi_master
    class spi_master extends uvm_reg_block;
        rand spi_master__ip_version ip_version;
        rand spi_master__capability capability;
        rand spi_master__ctrl ctrl;
        rand spi_master__action action;
        rand spi_master__status status;
        rand spi_master__fifo_level fifo_level;
        rand spi_master__watermark watermark;
        rand spi_master__wait_timeout wait_timeout;
        rand spi_master__irq_state irq_state;
        rand spi_master__irq_enable irq_enable;
        rand spi_master__irq_raw irq_raw;
        rand spi_master__error_status error_status;
        rand spi_master__txdata txdata;
        rand spi_master__rxdata rxdata;
        rand spi_master__cmd_cfg cmd_cfg;
        rand spi_master__cmd_len cmd_len;
        rand spi_master__cmd_tag cmd_tag;
        rand spi_master__cmd_push cmd_push;
        rand spi_master__active_tag active_tag;
        rand spi_master__progress progress;
        rand spi_master__last_done_tag last_done_tag;
        rand spi_master__done_count done_count;
        rand spi_master__active_info active_info;
        rand spi_master__cs_slot cs[8];

        function new(string name = "spi_master");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.ip_version = new("ip_version");
            this.ip_version.configure(this);

            this.ip_version.build();
            this.default_map.add_reg(this.ip_version, 'h0);
            this.capability = new("capability");
            this.capability.configure(this);

            this.capability.build();
            this.default_map.add_reg(this.capability, 'h4);
            this.ctrl = new("ctrl");
            this.ctrl.configure(this);

            this.ctrl.build();
            this.default_map.add_reg(this.ctrl, 'h8);
            this.action = new("action");
            this.action.configure(this);

            this.action.build();
            this.default_map.add_reg(this.action, 'hc);
            this.status = new("status");
            this.status.configure(this);

            this.status.build();
            this.default_map.add_reg(this.status, 'h10);
            this.fifo_level = new("fifo_level");
            this.fifo_level.configure(this);

            this.fifo_level.build();
            this.default_map.add_reg(this.fifo_level, 'h14);
            this.watermark = new("watermark");
            this.watermark.configure(this);

            this.watermark.build();
            this.default_map.add_reg(this.watermark, 'h18);
            this.wait_timeout = new("wait_timeout");
            this.wait_timeout.configure(this);

            this.wait_timeout.build();
            this.default_map.add_reg(this.wait_timeout, 'h1c);
            this.irq_state = new("irq_state");
            this.irq_state.configure(this);

            this.irq_state.build();
            this.default_map.add_reg(this.irq_state, 'h20);
            this.irq_enable = new("irq_enable");
            this.irq_enable.configure(this);

            this.irq_enable.build();
            this.default_map.add_reg(this.irq_enable, 'h24);
            this.irq_raw = new("irq_raw");
            this.irq_raw.configure(this);

            this.irq_raw.build();
            this.default_map.add_reg(this.irq_raw, 'h28);
            this.error_status = new("error_status");
            this.error_status.configure(this);

            this.error_status.build();
            this.default_map.add_reg(this.error_status, 'h2c);
            this.txdata = new("txdata");
            this.txdata.configure(this);

            this.txdata.build();
            this.default_map.add_reg(this.txdata, 'h30);
            this.rxdata = new("rxdata");
            this.rxdata.configure(this);

            this.rxdata.build();
            this.default_map.add_reg(this.rxdata, 'h34);
            this.cmd_cfg = new("cmd_cfg");
            this.cmd_cfg.configure(this);

            this.cmd_cfg.build();
            this.default_map.add_reg(this.cmd_cfg, 'h38);
            this.cmd_len = new("cmd_len");
            this.cmd_len.configure(this);

            this.cmd_len.build();
            this.default_map.add_reg(this.cmd_len, 'h3c);
            this.cmd_tag = new("cmd_tag");
            this.cmd_tag.configure(this);

            this.cmd_tag.build();
            this.default_map.add_reg(this.cmd_tag, 'h40);
            this.cmd_push = new("cmd_push");
            this.cmd_push.configure(this);

            this.cmd_push.build();
            this.default_map.add_reg(this.cmd_push, 'h44);
            this.active_tag = new("active_tag");
            this.active_tag.configure(this);

            this.active_tag.build();
            this.default_map.add_reg(this.active_tag, 'h48);
            this.progress = new("progress");
            this.progress.configure(this);

            this.progress.build();
            this.default_map.add_reg(this.progress, 'h4c);
            this.last_done_tag = new("last_done_tag");
            this.last_done_tag.configure(this);

            this.last_done_tag.build();
            this.default_map.add_reg(this.last_done_tag, 'h50);
            this.done_count = new("done_count");
            this.done_count.configure(this);

            this.done_count.build();
            this.default_map.add_reg(this.done_count, 'h54);
            this.active_info = new("active_info");
            this.active_info.configure(this);

            this.active_info.build();
            this.default_map.add_reg(this.active_info, 'h58);
            foreach(this.cs[i0]) begin
                this.cs[i0] = new($sformatf("cs[%0d]", i0));
                this.cs[i0].configure(this);
                this.cs[i0].build();
                this.default_map.add_submap(this.cs[i0].default_map, 'h100 + i0*'h20);
            end
        endfunction : build
    endclass : spi_master

endpackage: spi_master_ral
