// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef GPIO_REGS_H
#define GPIO_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - gpio_regs::IP_ID
#define GPIO_REGS__IP_ID__VALUE_bm 0xffffffff
#define GPIO_REGS__IP_ID__VALUE_bp 0
#define GPIO_REGS__IP_ID__VALUE_bw 32
#define GPIO_REGS__IP_ID__VALUE_reset 0x4750494f

// reg - gpio_regs::VERSION
#define GPIO_REGS__VERSION__VALUE_bm 0xffffffff
#define GPIO_REGS__VERSION__VALUE_bp 0
#define GPIO_REGS__VERSION__VALUE_bw 32
#define GPIO_REGS__VERSION__VALUE_reset 0x10000

// reg - gpio_regs::FEATURE
#define GPIO_REGS__FEATURE__FEATURES_bm 0xff
#define GPIO_REGS__FEATURE__FEATURES_bp 0
#define GPIO_REGS__FEATURE__FEATURES_bw 8
#define GPIO_REGS__FEATURE__FEATURES_reset 0x0

// reg - gpio_regs::GEOMETRY
#define GPIO_REGS__GEOMETRY__N_GPIO_bm 0xff
#define GPIO_REGS__GEOMETRY__N_GPIO_bp 0
#define GPIO_REGS__GEOMETRY__N_GPIO_bw 8
#define GPIO_REGS__GEOMETRY__N_GPIO_reset 0x80
#define GPIO_REGS__GEOMETRY__N_BANK_bm 0xff00
#define GPIO_REGS__GEOMETRY__N_BANK_bp 8
#define GPIO_REGS__GEOMETRY__N_BANK_bw 8
#define GPIO_REGS__GEOMETRY__N_BANK_reset 0x4
#define GPIO_REGS__GEOMETRY__N_IRQ_GROUPS_bm 0xff0000
#define GPIO_REGS__GEOMETRY__N_IRQ_GROUPS_bp 16
#define GPIO_REGS__GEOMETRY__N_IRQ_GROUPS_bw 8
#define GPIO_REGS__GEOMETRY__N_IRQ_GROUPS_reset 0x1
#define GPIO_REGS__GEOMETRY__SYNC_STAGES_bm 0xff000000
#define GPIO_REGS__GEOMETRY__SYNC_STAGES_bp 24
#define GPIO_REGS__GEOMETRY__SYNC_STAGES_bw 8
#define GPIO_REGS__GEOMETRY__SYNC_STAGES_reset 0x2

// reg - gpio_regs::GLOBAL_LOCK
#define GPIO_REGS__GLOBAL_LOCK__LOCKED_bm 0x1
#define GPIO_REGS__GLOBAL_LOCK__LOCKED_bp 0
#define GPIO_REGS__GLOBAL_LOCK__LOCKED_bw 1
#define GPIO_REGS__GLOBAL_LOCK__LOCKED_reset 0x0

// reg - gpio_regs::ACCESS_CFG
#define GPIO_REGS__ACCESS_CFG__SECURE_ONLY_bm 0x1
#define GPIO_REGS__ACCESS_CFG__SECURE_ONLY_bp 0
#define GPIO_REGS__ACCESS_CFG__SECURE_ONLY_bw 1
#define GPIO_REGS__ACCESS_CFG__SECURE_ONLY_reset 0x1
#define GPIO_REGS__ACCESS_CFG__PRIV_ONLY_bm 0x2
#define GPIO_REGS__ACCESS_CFG__PRIV_ONLY_bp 1
#define GPIO_REGS__ACCESS_CFG__PRIV_ONLY_bw 1
#define GPIO_REGS__ACCESS_CFG__PRIV_ONLY_reset 0x1

// reg - gpio_regs::FAULT_STATUS
#define GPIO_REGS__FAULT_STATUS__SOURCES_bm 0xff
#define GPIO_REGS__FAULT_STATUS__SOURCES_bp 0
#define GPIO_REGS__FAULT_STATUS__SOURCES_bw 8
#define GPIO_REGS__FAULT_STATUS__SOURCES_reset 0x0

// reg - gpio_regs::FAULT_CLEAR
#define GPIO_REGS__FAULT_CLEAR__CLEAR_bm 0xff
#define GPIO_REGS__FAULT_CLEAR__CLEAR_bp 0
#define GPIO_REGS__FAULT_CLEAR__CLEAR_bw 8
#define GPIO_REGS__FAULT_CLEAR__CLEAR_reset 0x0

// reg - gpio_regs::FAULT_IRQ_ENABLE
#define GPIO_REGS__FAULT_IRQ_ENABLE__ENABLE_bm 0xff
#define GPIO_REGS__FAULT_IRQ_ENABLE__ENABLE_bp 0
#define GPIO_REGS__FAULT_IRQ_ENABLE__ENABLE_bw 8
#define GPIO_REGS__FAULT_IRQ_ENABLE__ENABLE_reset 0x0

// reg - gpio_regs::ACCESS_FIRST
#define GPIO_REGS__ACCESS_FIRST__ADDRESS_bm 0x3fff
#define GPIO_REGS__ACCESS_FIRST__ADDRESS_bp 0
#define GPIO_REGS__ACCESS_FIRST__ADDRESS_bw 14
#define GPIO_REGS__ACCESS_FIRST__ADDRESS_reset 0x0
#define GPIO_REGS__ACCESS_FIRST__PPROT_bm 0x70000
#define GPIO_REGS__ACCESS_FIRST__PPROT_bp 16
#define GPIO_REGS__ACCESS_FIRST__PPROT_bw 3
#define GPIO_REGS__ACCESS_FIRST__PPROT_reset 0x0
#define GPIO_REGS__ACCESS_FIRST__WRITE_bm 0x80000
#define GPIO_REGS__ACCESS_FIRST__WRITE_bp 19
#define GPIO_REGS__ACCESS_FIRST__WRITE_bw 1
#define GPIO_REGS__ACCESS_FIRST__WRITE_reset 0x0
#define GPIO_REGS__ACCESS_FIRST__VALID_bm 0x80000000
#define GPIO_REGS__ACCESS_FIRST__VALID_bp 31
#define GPIO_REGS__ACCESS_FIRST__VALID_bw 1
#define GPIO_REGS__ACCESS_FIRST__VALID_reset 0x0

// reg - gpio_regs::SNAPSHOT_CMD
#define GPIO_REGS__SNAPSHOT_CMD__TRIGGER_bm 0x1
#define GPIO_REGS__SNAPSHOT_CMD__TRIGGER_bp 0
#define GPIO_REGS__SNAPSHOT_CMD__TRIGGER_bw 1
#define GPIO_REGS__SNAPSHOT_CMD__TRIGGER_reset 0x0

// reg - gpio_regs::SNAP_SEQ
#define GPIO_REGS__SNAP_SEQ__VALUE_bm 0xffffffff
#define GPIO_REGS__SNAP_SEQ__VALUE_bp 0
#define GPIO_REGS__SNAP_SEQ__VALUE_bw 32
#define GPIO_REGS__SNAP_SEQ__VALUE_reset 0x0

// reg - gpio_regs::STRAP_VALID
#define GPIO_REGS__STRAP_VALID__VALID_bm 0x1
#define GPIO_REGS__STRAP_VALID__VALID_bp 0
#define GPIO_REGS__STRAP_VALID__VALID_bw 1
#define GPIO_REGS__STRAP_VALID__VALID_reset 0x0

// reg - gpio_regs::LP_STATUS
#define GPIO_REGS__LP_STATUS__SLEEP_ACTIVE_bm 0x1
#define GPIO_REGS__LP_STATUS__SLEEP_ACTIVE_bp 0
#define GPIO_REGS__LP_STATUS__SLEEP_ACTIVE_bw 1
#define GPIO_REGS__LP_STATUS__SLEEP_ACTIVE_reset 0x0
#define GPIO_REGS__LP_STATUS__SAFE_ACTIVE_bm 0x2
#define GPIO_REGS__LP_STATUS__SAFE_ACTIVE_bp 1
#define GPIO_REGS__LP_STATUS__SAFE_ACTIVE_bw 1
#define GPIO_REGS__LP_STATUS__SAFE_ACTIVE_reset 0x0

// reg - gpio_regs::TS_LO
#define GPIO_REGS__TS_LO__VALUE_bm 0xffffffff
#define GPIO_REGS__TS_LO__VALUE_bp 0
#define GPIO_REGS__TS_LO__VALUE_bw 32
#define GPIO_REGS__TS_LO__VALUE_reset 0x0

// reg - gpio_regs::TS_HI
#define GPIO_REGS__TS_HI__VALUE_bm 0xffffffff
#define GPIO_REGS__TS_HI__VALUE_bp 0
#define GPIO_REGS__TS_HI__VALUE_bw 32
#define GPIO_REGS__TS_HI__VALUE_reset 0x0

// reg - gpio_regs::FIFO_CTRL
#define GPIO_REGS__FIFO_CTRL__ENABLE_bm 0x1
#define GPIO_REGS__FIFO_CTRL__ENABLE_bp 0
#define GPIO_REGS__FIFO_CTRL__ENABLE_bw 1
#define GPIO_REGS__FIFO_CTRL__ENABLE_reset 0x0
#define GPIO_REGS__FIFO_CTRL__DMA_ENABLE_bm 0x2
#define GPIO_REGS__FIFO_CTRL__DMA_ENABLE_bp 1
#define GPIO_REGS__FIFO_CTRL__DMA_ENABLE_bw 1
#define GPIO_REGS__FIFO_CTRL__DMA_ENABLE_reset 0x0

// reg - gpio_regs::FIFO_WATERMARK
#define GPIO_REGS__FIFO_WATERMARK__THRESHOLD_bm 0x7f
#define GPIO_REGS__FIFO_WATERMARK__THRESHOLD_bp 0
#define GPIO_REGS__FIFO_WATERMARK__THRESHOLD_bw 7
#define GPIO_REGS__FIFO_WATERMARK__THRESHOLD_reset 0x1

// reg - gpio_regs::FIFO_LEVEL
#define GPIO_REGS__FIFO_LEVEL__VALUE_bm 0xffffffff
#define GPIO_REGS__FIFO_LEVEL__VALUE_bp 0
#define GPIO_REGS__FIFO_LEVEL__VALUE_bw 32
#define GPIO_REGS__FIFO_LEVEL__VALUE_reset 0x0

// reg - gpio_regs::FIFO_LOST
#define GPIO_REGS__FIFO_LOST__VALUE_bm 0xffffffff
#define GPIO_REGS__FIFO_LOST__VALUE_bp 0
#define GPIO_REGS__FIFO_LOST__VALUE_bw 32
#define GPIO_REGS__FIFO_LOST__VALUE_reset 0x0

// reg - gpio_regs::EVENT_HEAD0
#define GPIO_REGS__EVENT_HEAD0__VALUE_bm 0xffffffff
#define GPIO_REGS__EVENT_HEAD0__VALUE_bp 0
#define GPIO_REGS__EVENT_HEAD0__VALUE_bw 32
#define GPIO_REGS__EVENT_HEAD0__VALUE_reset 0x0

// reg - gpio_regs::EVENT_HEAD1
#define GPIO_REGS__EVENT_HEAD1__VALUE_bm 0xffffffff
#define GPIO_REGS__EVENT_HEAD1__VALUE_bp 0
#define GPIO_REGS__EVENT_HEAD1__VALUE_bw 32
#define GPIO_REGS__EVENT_HEAD1__VALUE_reset 0x0

// reg - gpio_regs::EVENT_HEAD2
#define GPIO_REGS__EVENT_HEAD2__VALUE_bm 0xffffffff
#define GPIO_REGS__EVENT_HEAD2__VALUE_bp 0
#define GPIO_REGS__EVENT_HEAD2__VALUE_bw 32
#define GPIO_REGS__EVENT_HEAD2__VALUE_reset 0x0

// reg - gpio_regs::EVENT_HEAD3
#define GPIO_REGS__EVENT_HEAD3__VALUE_bm 0xffffffff
#define GPIO_REGS__EVENT_HEAD3__VALUE_bp 0
#define GPIO_REGS__EVENT_HEAD3__VALUE_bw 32
#define GPIO_REGS__EVENT_HEAD3__VALUE_reset 0x0

// reg - gpio_regs::EVENT_POP
#define GPIO_REGS__EVENT_POP__POP_bm 0x1
#define GPIO_REGS__EVENT_POP__POP_bp 0
#define GPIO_REGS__EVENT_POP__POP_bw 1
#define GPIO_REGS__EVENT_POP__POP_reset 0x0

// reg - gpio_regs::FIFO_CMD
#define GPIO_REGS__FIFO_CMD__FLUSH_bm 0x1
#define GPIO_REGS__FIFO_CMD__FLUSH_bp 0
#define GPIO_REGS__FIFO_CMD__FLUSH_bw 1
#define GPIO_REGS__FIFO_CMD__FLUSH_reset 0x0
#define GPIO_REGS__FIFO_CMD__CLEAR_LOST_bm 0x2
#define GPIO_REGS__FIFO_CMD__CLEAR_LOST_bp 1
#define GPIO_REGS__FIFO_CMD__CLEAR_LOST_bw 1
#define GPIO_REGS__FIFO_CMD__CLEAR_LOST_reset 0x0

// reg - gpio_regs::AON_STATUS
#define GPIO_REGS__AON_STATUS__READY_bm 0x1
#define GPIO_REGS__AON_STATUS__READY_bp 0
#define GPIO_REGS__AON_STATUS__READY_bw 1
#define GPIO_REGS__AON_STATUS__READY_reset 0x0
#define GPIO_REGS__AON_STATUS__BUSY_bm 0x2
#define GPIO_REGS__AON_STATUS__BUSY_bp 1
#define GPIO_REGS__AON_STATUS__BUSY_bw 1
#define GPIO_REGS__AON_STATUS__BUSY_reset 0x0
#define GPIO_REGS__AON_STATUS__DONE_bm 0x4
#define GPIO_REGS__AON_STATUS__DONE_bp 2
#define GPIO_REGS__AON_STATUS__DONE_bw 1
#define GPIO_REGS__AON_STATUS__DONE_reset 0x0
#define GPIO_REGS__AON_STATUS__TIMEOUT_bm 0x8
#define GPIO_REGS__AON_STATUS__TIMEOUT_bp 3
#define GPIO_REGS__AON_STATUS__TIMEOUT_bw 1
#define GPIO_REGS__AON_STATUS__TIMEOUT_reset 0x0
#define GPIO_REGS__AON_STATUS__ERROR_bm 0x10
#define GPIO_REGS__AON_STATUS__ERROR_bp 4
#define GPIO_REGS__AON_STATUS__ERROR_bw 1
#define GPIO_REGS__AON_STATUS__ERROR_reset 0x0
#define GPIO_REGS__AON_STATUS__BANK_bm 0x300
#define GPIO_REGS__AON_STATUS__BANK_bp 8
#define GPIO_REGS__AON_STATUS__BANK_bw 2
#define GPIO_REGS__AON_STATUS__BANK_reset 0x0

// reg - gpio_regs::AON_TIMEOUT
#define GPIO_REGS__AON_TIMEOUT__CYCLES_bm 0xffffff
#define GPIO_REGS__AON_TIMEOUT__CYCLES_bp 0
#define GPIO_REGS__AON_TIMEOUT__CYCLES_bw 24
#define GPIO_REGS__AON_TIMEOUT__CYCLES_reset 0xffff

// reg - gpio_regs::PARITY_INJECT
#define GPIO_REGS__PARITY_INJECT__TRIGGER_bm 0x1
#define GPIO_REGS__PARITY_INJECT__TRIGGER_bp 0
#define GPIO_REGS__PARITY_INJECT__TRIGGER_bw 1
#define GPIO_REGS__PARITY_INJECT__TRIGGER_reset 0x0
#define GPIO_REGS__PARITY_INJECT__BANK_bm 0x300
#define GPIO_REGS__PARITY_INJECT__BANK_bp 8
#define GPIO_REGS__PARITY_INJECT__BANK_bw 2
#define GPIO_REGS__PARITY_INJECT__BANK_reset 0x0

// reg - gpio_regs::bank_type::INPUT_CAP
#define GPIO_REGS__BANK_TYPE__INPUT_CAP__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__INPUT_CAP__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__INPUT_CAP__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__INPUT_CAP__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OUTPUT_CAP
#define GPIO_REGS__BANK_TYPE__OUTPUT_CAP__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OUTPUT_CAP__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OUTPUT_CAP__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OUTPUT_CAP__VALUE_reset 0x0

// reg - gpio_regs::bank_type::IN_SYNC
#define GPIO_REGS__BANK_TYPE__IN_SYNC__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__IN_SYNC__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__IN_SYNC__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__IN_SYNC__VALUE_reset 0x0

// reg - gpio_regs::bank_type::IN_DATA
#define GPIO_REGS__BANK_TYPE__IN_DATA__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__IN_DATA__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__IN_DATA__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__IN_DATA__VALUE_reset 0x0

// reg - gpio_regs::bank_type::IN_VALID
#define GPIO_REGS__BANK_TYPE__IN_VALID__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__IN_VALID__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__IN_VALID__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__IN_VALID__VALUE_reset 0x0

// reg - gpio_regs::bank_type::IN_ENABLE
#define GPIO_REGS__BANK_TYPE__IN_ENABLE__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__IN_ENABLE__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__IN_ENABLE__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__IN_ENABLE__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OUT_DATA
#define GPIO_REGS__BANK_TYPE__OUT_DATA__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OUT_DATA__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OUT_DATA__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OUT_DATA__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OUT_SET
#define GPIO_REGS__BANK_TYPE__OUT_SET__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OUT_SET__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OUT_SET__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OUT_SET__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OUT_CLR
#define GPIO_REGS__BANK_TYPE__OUT_CLR__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OUT_CLR__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OUT_CLR__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OUT_CLR__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OUT_TOGGLE
#define GPIO_REGS__BANK_TYPE__OUT_TOGGLE__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OUT_TOGGLE__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OUT_TOGGLE__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OUT_TOGGLE__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OUT_MASKED_LO
#define GPIO_REGS__BANK_TYPE__OUT_MASKED_LO__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OUT_MASKED_LO__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OUT_MASKED_LO__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OUT_MASKED_LO__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OUT_MASKED_HI
#define GPIO_REGS__BANK_TYPE__OUT_MASKED_HI__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OUT_MASKED_HI__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OUT_MASKED_HI__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OUT_MASKED_HI__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OUT_OE
#define GPIO_REGS__BANK_TYPE__OUT_OE__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OUT_OE__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OUT_OE__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OUT_OE__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OE_SET
#define GPIO_REGS__BANK_TYPE__OE_SET__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OE_SET__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OE_SET__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OE_SET__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OE_CLR
#define GPIO_REGS__BANK_TYPE__OE_CLR__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OE_CLR__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OE_CLR__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OE_CLR__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OE_MASKED_LO
#define GPIO_REGS__BANK_TYPE__OE_MASKED_LO__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OE_MASKED_LO__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OE_MASKED_LO__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OE_MASKED_LO__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OE_MASKED_HI
#define GPIO_REGS__BANK_TYPE__OE_MASKED_HI__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OE_MASKED_HI__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OE_MASKED_HI__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OE_MASKED_HI__VALUE_reset 0x0

// reg - gpio_regs::bank_type::IRQ_DETECT_EN
#define GPIO_REGS__BANK_TYPE__IRQ_DETECT_EN__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__IRQ_DETECT_EN__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__IRQ_DETECT_EN__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__IRQ_DETECT_EN__VALUE_reset 0x0

// reg - gpio_regs::bank_type::IRQ_ENABLE
#define GPIO_REGS__BANK_TYPE__IRQ_ENABLE__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__IRQ_ENABLE__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__IRQ_ENABLE__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__IRQ_ENABLE__VALUE_reset 0x0

// reg - gpio_regs::bank_type::IRQ_PENDING
#define GPIO_REGS__BANK_TYPE__IRQ_PENDING__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__IRQ_PENDING__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__IRQ_PENDING__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__IRQ_PENDING__VALUE_reset 0x0

// reg - gpio_regs::bank_type::IRQ_STATUS
#define GPIO_REGS__BANK_TYPE__IRQ_STATUS__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__IRQ_STATUS__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__IRQ_STATUS__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__IRQ_STATUS__VALUE_reset 0x0

// reg - gpio_regs::bank_type::IRQ_TEST
#define GPIO_REGS__BANK_TYPE__IRQ_TEST__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__IRQ_TEST__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__IRQ_TEST__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__IRQ_TEST__VALUE_reset 0x0

// reg - gpio_regs::bank_type::RISING_PENDING
#define GPIO_REGS__BANK_TYPE__RISING_PENDING__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__RISING_PENDING__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__RISING_PENDING__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__RISING_PENDING__VALUE_reset 0x0

// reg - gpio_regs::bank_type::FALLING_PENDING
#define GPIO_REGS__BANK_TYPE__FALLING_PENDING__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__FALLING_PENDING__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__FALLING_PENDING__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__FALLING_PENDING__VALUE_reset 0x0

// reg - gpio_regs::bank_type::CFG_LOCK
#define GPIO_REGS__BANK_TYPE__CFG_LOCK__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__CFG_LOCK__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__CFG_LOCK__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__CFG_LOCK__VALUE_reset 0x0

// reg - gpio_regs::bank_type::DATA_LOCK
#define GPIO_REGS__BANK_TYPE__DATA_LOCK__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__DATA_LOCK__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__DATA_LOCK__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__DATA_LOCK__VALUE_reset 0x0

// reg - gpio_regs::bank_type::BANK_DEBOUNCE_DIV
#define GPIO_REGS__BANK_TYPE__BANK_DEBOUNCE_DIV__VALUE_bm 0xffff
#define GPIO_REGS__BANK_TYPE__BANK_DEBOUNCE_DIV__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__BANK_DEBOUNCE_DIV__VALUE_bw 16
#define GPIO_REGS__BANK_TYPE__BANK_DEBOUNCE_DIV__VALUE_reset 0x0

// reg - gpio_regs::bank_type::EVENT_ENABLE
#define GPIO_REGS__BANK_TYPE__EVENT_ENABLE__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__EVENT_ENABLE__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__EVENT_ENABLE__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__EVENT_ENABLE__VALUE_reset 0x0

// reg - gpio_regs::bank_type::SNAP_DATA
#define GPIO_REGS__BANK_TYPE__SNAP_DATA__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__SNAP_DATA__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__SNAP_DATA__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__SNAP_DATA__VALUE_reset 0x0

// reg - gpio_regs::bank_type::SNAP_VALID
#define GPIO_REGS__BANK_TYPE__SNAP_VALID__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__SNAP_VALID__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__SNAP_VALID__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__SNAP_VALID__VALUE_reset 0x0

// reg - gpio_regs::bank_type::STRAP_DATA
#define GPIO_REGS__BANK_TYPE__STRAP_DATA__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__STRAP_DATA__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__STRAP_DATA__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__STRAP_DATA__VALUE_reset 0x0

// reg - gpio_regs::bank_type::DIAG_ENABLE
#define GPIO_REGS__BANK_TYPE__DIAG_ENABLE__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__DIAG_ENABLE__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__DIAG_ENABLE__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__DIAG_ENABLE__VALUE_reset 0x0

// reg - gpio_regs::bank_type::DIAG_PENDING
#define GPIO_REGS__BANK_TYPE__DIAG_PENDING__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__DIAG_PENDING__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__DIAG_PENDING__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__DIAG_PENDING__VALUE_reset 0x0

// reg - gpio_regs::bank_type::DIAG_TEST
#define GPIO_REGS__BANK_TYPE__DIAG_TEST__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__DIAG_TEST__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__DIAG_TEST__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__DIAG_TEST__VALUE_reset 0x0

// reg - gpio_regs::bank_type::OUTPUT_OWNED
#define GPIO_REGS__BANK_TYPE__OUTPUT_OWNED__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__OUTPUT_OWNED__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__OUTPUT_OWNED__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__OUTPUT_OWNED__VALUE_reset 0x0

// reg - gpio_regs::bank_type::INPUT_AVAILABLE
#define GPIO_REGS__BANK_TYPE__INPUT_AVAILABLE__VALUE_bm 0xffffffff
#define GPIO_REGS__BANK_TYPE__INPUT_AVAILABLE__VALUE_bp 0
#define GPIO_REGS__BANK_TYPE__INPUT_AVAILABLE__VALUE_bw 32
#define GPIO_REGS__BANK_TYPE__INPUT_AVAILABLE__VALUE_reset 0x0

// regfile - gpio_regs::bank_type
typedef struct __attribute__ ((__packed__)) {
    uint32_t INPUT_CAP;
    uint32_t OUTPUT_CAP;
    uint32_t IN_SYNC;
    uint32_t IN_DATA;
    uint32_t IN_VALID;
    uint32_t IN_ENABLE;
    uint32_t OUT_DATA;
    uint32_t OUT_SET;
    uint32_t OUT_CLR;
    uint32_t OUT_TOGGLE;
    uint32_t OUT_MASKED_LO;
    uint32_t OUT_MASKED_HI;
    uint32_t OUT_OE;
    uint32_t OE_SET;
    uint32_t OE_CLR;
    uint32_t OE_MASKED_LO;
    uint32_t OE_MASKED_HI;
    uint32_t IRQ_DETECT_EN;
    uint32_t IRQ_ENABLE;
    uint32_t IRQ_PENDING;
    uint32_t IRQ_STATUS;
    uint32_t IRQ_TEST;
    uint32_t RISING_PENDING;
    uint32_t FALLING_PENDING;
    uint32_t CFG_LOCK;
    uint32_t DATA_LOCK;
    uint32_t BANK_DEBOUNCE_DIV;
    uint32_t EVENT_ENABLE;
    uint32_t SNAP_DATA;
    uint32_t SNAP_VALID;
    uint32_t STRAP_DATA;
    uint32_t DIAG_ENABLE;
    uint32_t DIAG_PENDING;
    uint32_t DIAG_TEST;
    uint32_t OUTPUT_OWNED;
    uint32_t INPUT_AVAILABLE;
    uint8_t RESERVED_90_ff[0x70];
} gpio_regs__bank_type__stride100_t;

// reg - gpio_regs::pin_type::PIN_CFG
#define GPIO_REGS__PIN_TYPE__PIN_CFG__FILTER_EN_bm 0x1
#define GPIO_REGS__PIN_TYPE__PIN_CFG__FILTER_EN_bp 0
#define GPIO_REGS__PIN_TYPE__PIN_CFG__FILTER_EN_bw 1
#define GPIO_REGS__PIN_TYPE__PIN_CFG__FILTER_EN_reset 0x0
#define GPIO_REGS__PIN_TYPE__PIN_CFG__DEBOUNCE_EN_bm 0x2
#define GPIO_REGS__PIN_TYPE__PIN_CFG__DEBOUNCE_EN_bp 1
#define GPIO_REGS__PIN_TYPE__PIN_CFG__DEBOUNCE_EN_bw 1
#define GPIO_REGS__PIN_TYPE__PIN_CFG__DEBOUNCE_EN_reset 0x0
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IN_INV_bm 0x4
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IN_INV_bp 2
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IN_INV_bw 1
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IN_INV_reset 0x0
#define GPIO_REGS__PIN_TYPE__PIN_CFG__OUT_OD_bm 0x8
#define GPIO_REGS__PIN_TYPE__PIN_CFG__OUT_OD_bp 3
#define GPIO_REGS__PIN_TYPE__PIN_CFG__OUT_OD_bw 1
#define GPIO_REGS__PIN_TYPE__PIN_CFG__OUT_OD_reset 0x0
#define GPIO_REGS__PIN_TYPE__PIN_CFG__OUT_INV_bm 0x10
#define GPIO_REGS__PIN_TYPE__PIN_CFG__OUT_INV_bp 4
#define GPIO_REGS__PIN_TYPE__PIN_CFG__OUT_INV_bw 1
#define GPIO_REGS__PIN_TYPE__PIN_CFG__OUT_INV_reset 0x0
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IRQ_MODE_bm 0xe0
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IRQ_MODE_bp 5
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IRQ_MODE_bw 3
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IRQ_MODE_reset 0x0
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IRQ_GROUP_bm 0x300
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IRQ_GROUP_bp 8
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IRQ_GROUP_bw 2
#define GPIO_REGS__PIN_TYPE__PIN_CFG__IRQ_GROUP_reset 0x0
#define GPIO_REGS__PIN_TYPE__PIN_CFG__SLEEP_MODE_bm 0xc00
#define GPIO_REGS__PIN_TYPE__PIN_CFG__SLEEP_MODE_bp 10
#define GPIO_REGS__PIN_TYPE__PIN_CFG__SLEEP_MODE_bw 2
#define GPIO_REGS__PIN_TYPE__PIN_CFG__SLEEP_MODE_reset 0x0

// reg - gpio_regs::pin_type::FILTER_CFG
#define GPIO_REGS__PIN_TYPE__FILTER_CFG__K_MINUS_ONE_bm 0xff
#define GPIO_REGS__PIN_TYPE__FILTER_CFG__K_MINUS_ONE_bp 0
#define GPIO_REGS__PIN_TYPE__FILTER_CFG__K_MINUS_ONE_bw 8
#define GPIO_REGS__PIN_TYPE__FILTER_CFG__K_MINUS_ONE_reset 0x0

// reg - gpio_regs::pin_type::DEBOUNCE_CFG
#define GPIO_REGS__PIN_TYPE__DEBOUNCE_CFG__D_MINUS_ONE_bm 0xff
#define GPIO_REGS__PIN_TYPE__DEBOUNCE_CFG__D_MINUS_ONE_bp 0
#define GPIO_REGS__PIN_TYPE__DEBOUNCE_CFG__D_MINUS_ONE_bw 8
#define GPIO_REGS__PIN_TYPE__DEBOUNCE_CFG__D_MINUS_ONE_reset 0x0

// reg - gpio_regs::pin_type::DIAG_CFG
#define GPIO_REGS__PIN_TYPE__DIAG_CFG__BLANK_bm 0xffff
#define GPIO_REGS__PIN_TYPE__DIAG_CFG__BLANK_bp 0
#define GPIO_REGS__PIN_TYPE__DIAG_CFG__BLANK_bw 16
#define GPIO_REGS__PIN_TYPE__DIAG_CFG__BLANK_reset 0x4
#define GPIO_REGS__PIN_TYPE__DIAG_CFG__M_MINUS_ONE_bm 0xff0000
#define GPIO_REGS__PIN_TYPE__DIAG_CFG__M_MINUS_ONE_bp 16
#define GPIO_REGS__PIN_TYPE__DIAG_CFG__M_MINUS_ONE_bw 8
#define GPIO_REGS__PIN_TYPE__DIAG_CFG__M_MINUS_ONE_reset 0x0

// regfile - gpio_regs::pin_type
typedef struct __attribute__ ((__packed__)) {
    uint32_t PIN_CFG;
    uint32_t FILTER_CFG;
    uint32_t DEBOUNCE_CFG;
    uint32_t DIAG_CFG;
    uint8_t RESERVED_10_1f[0x10];
} gpio_regs__pin_type__stride20_t;

// reg - gpio_regs::aon_type::WAKE_ENABLE_STAGE
#define GPIO_REGS__AON_TYPE__WAKE_ENABLE_STAGE__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_ENABLE_STAGE__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_ENABLE_STAGE__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_ENABLE_STAGE__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_MODE_STAGE0
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE0__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE0__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE0__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE0__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_MODE_STAGE1
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE1__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE1__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE1__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE1__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_MODE_STAGE2
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE2__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE2__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE2__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_MODE_STAGE2__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_DIV_STAGE
#define GPIO_REGS__AON_TYPE__WAKE_DIV_STAGE__VALUE_bm 0xffff
#define GPIO_REGS__AON_TYPE__WAKE_DIV_STAGE__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_DIV_STAGE__VALUE_bw 16
#define GPIO_REGS__AON_TYPE__WAKE_DIV_STAGE__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_COUNT_STAGE
#define GPIO_REGS__AON_TYPE__WAKE_COUNT_STAGE__VALUE_bm 0xff
#define GPIO_REGS__AON_TYPE__WAKE_COUNT_STAGE__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_COUNT_STAGE__VALUE_bw 8
#define GPIO_REGS__AON_TYPE__WAKE_COUNT_STAGE__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_MASK_STAGE
#define GPIO_REGS__AON_TYPE__WAKE_MASK_STAGE__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_MASK_STAGE__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_MASK_STAGE__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_MASK_STAGE__VALUE_reset 0x0

// reg - gpio_regs::aon_type::AON_CMD
#define GPIO_REGS__AON_TYPE__AON_CMD__COMMANDS_bm 0xf
#define GPIO_REGS__AON_TYPE__AON_CMD__COMMANDS_bp 0
#define GPIO_REGS__AON_TYPE__AON_CMD__COMMANDS_bw 4
#define GPIO_REGS__AON_TYPE__AON_CMD__COMMANDS_reset 0x0

// reg - gpio_regs::aon_type::WAKE_PENDING_READ
#define GPIO_REGS__AON_TYPE__WAKE_PENDING_READ__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_PENDING_READ__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_PENDING_READ__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_PENDING_READ__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_VALID_READ
#define GPIO_REGS__AON_TYPE__WAKE_VALID_READ__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_VALID_READ__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_VALID_READ__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_VALID_READ__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_LOCK_READ
#define GPIO_REGS__AON_TYPE__WAKE_LOCK_READ__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_LOCK_READ__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_LOCK_READ__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_LOCK_READ__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_ENABLE_READ
#define GPIO_REGS__AON_TYPE__WAKE_ENABLE_READ__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_ENABLE_READ__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_ENABLE_READ__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_ENABLE_READ__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_MODE_READ0
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ0__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ0__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ0__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ0__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_MODE_READ1
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ1__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ1__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ1__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ1__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_MODE_READ2
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ2__VALUE_bm 0xffffffff
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ2__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ2__VALUE_bw 32
#define GPIO_REGS__AON_TYPE__WAKE_MODE_READ2__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_DIV_READ
#define GPIO_REGS__AON_TYPE__WAKE_DIV_READ__VALUE_bm 0xffff
#define GPIO_REGS__AON_TYPE__WAKE_DIV_READ__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_DIV_READ__VALUE_bw 16
#define GPIO_REGS__AON_TYPE__WAKE_DIV_READ__VALUE_reset 0x0

// reg - gpio_regs::aon_type::WAKE_COUNT_READ
#define GPIO_REGS__AON_TYPE__WAKE_COUNT_READ__VALUE_bm 0xff
#define GPIO_REGS__AON_TYPE__WAKE_COUNT_READ__VALUE_bp 0
#define GPIO_REGS__AON_TYPE__WAKE_COUNT_READ__VALUE_bw 8
#define GPIO_REGS__AON_TYPE__WAKE_COUNT_READ__VALUE_reset 0x0

// regfile - gpio_regs::aon_type
typedef struct __attribute__ ((__packed__)) {
    uint32_t WAKE_ENABLE_STAGE;
    uint32_t WAKE_MODE_STAGE0;
    uint32_t WAKE_MODE_STAGE1;
    uint32_t WAKE_MODE_STAGE2;
    uint32_t WAKE_DIV_STAGE;
    uint32_t WAKE_COUNT_STAGE;
    uint32_t WAKE_MASK_STAGE;
    uint32_t AON_CMD;
    uint32_t WAKE_PENDING_READ;
    uint32_t WAKE_VALID_READ;
    uint32_t WAKE_LOCK_READ;
    uint32_t WAKE_ENABLE_READ;
    uint32_t WAKE_MODE_READ0;
    uint32_t WAKE_MODE_READ1;
    uint32_t WAKE_MODE_READ2;
    uint32_t WAKE_DIV_READ;
    uint32_t WAKE_COUNT_READ;
    uint8_t RESERVED_44_ff[0xbc];
} gpio_regs__aon_type__stride100_t;

// addrmap - gpio_regs
typedef struct __attribute__ ((__packed__)) {
    uint32_t IP_ID;
    uint32_t VERSION;
    uint32_t FEATURE;
    uint32_t GEOMETRY;
    uint32_t GLOBAL_LOCK;
    uint32_t ACCESS_CFG;
    uint32_t FAULT_STATUS;
    uint32_t FAULT_CLEAR;
    uint32_t FAULT_IRQ_ENABLE;
    uint32_t ACCESS_FIRST;
    uint32_t SNAPSHOT_CMD;
    uint32_t SNAP_SEQ;
    uint32_t STRAP_VALID;
    uint32_t LP_STATUS;
    uint32_t TS_LO;
    uint32_t TS_HI;
    uint32_t FIFO_CTRL;
    uint32_t FIFO_WATERMARK;
    uint32_t FIFO_LEVEL;
    uint32_t FIFO_LOST;
    uint32_t EVENT_HEAD0;
    uint32_t EVENT_HEAD1;
    uint32_t EVENT_HEAD2;
    uint32_t EVENT_HEAD3;
    uint32_t EVENT_POP;
    uint32_t FIFO_CMD;
    uint32_t AON_STATUS;
    uint32_t AON_TIMEOUT;
    uint32_t PARITY_INJECT;
    uint8_t RESERVED_74_ff[0x8c];
    gpio_regs__bank_type__stride100_t bank[4];
    uint8_t RESERVED_500_fff[0xb00];
    gpio_regs__pin_type__stride20_t pin[128];
    uint8_t RESERVED_2000_2fff[0x1000];
    gpio_regs__aon_type__stride100_t aon[4];
} gpio_regs_t;


static_assert(sizeof(gpio_regs_t) == 0x3400, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* GPIO_REGS_H */
