"""Generate the GPIO FuseSoC package from local sources and parameter metadata."""
from pathlib import Path
import yaml


def main():
    root=Path(__file__).resolve().parents[1]
    generated=['rtl/generated/gpio_csr_pkg.sv','rtl/generated/gpio_reg_desc_pkg.sv',
               'rtl/generated/gpio_csr.sv','rtl/generated/gpio_csr_adapter.sv']
    rtl=['rtl/gpio_pkg.sv']+[str(p.relative_to(root)) for p in sorted((root/'rtl').glob('gpio_*.sv')) if p.name!='gpio_pkg.sv']+['rtl/gpio.sv']
    for name in generated+rtl:
        if not (root/name).is_file():raise ValueError('Missing source '+name)
    (root/'rtl/filelist.f').write_text('\n'.join(generated+rtl)+'\n')
    parameters={}
    for param in yaml.safe_load((root/'model/parameter_space.yaml').read_text())['parameters']:
        entry={'datatype':'int','paramtype':'vlogparam','description':param['description']}
        # Let SV evaluate geometry-dependent mask defaults; FuseSoC may override explicitly.
        if param['name'] not in ('INPUT_CAP_MASK','OUTPUT_CAP_MASK','RESET_IN_EN'):
            entry['default']=param['default']
        parameters[param['name']]=entry
    filesets={'generated':{'files':generated,'file_type':'systemVerilogSource'},
              'rtl':{'files':rtl,'file_type':'systemVerilogSource','depend':['aixsilicon:cbb:parity_gen_check:0.1.0']}}
    base={'filesets':['generated','rtl'],'toplevel':'gpio','parameters':list(parameters)}
    filesets['lint_waivers']={'files':['constraints/lint_waivers.tcl'],'file_type':'waiver'}
    filesets['cdc_constraints']={'files':[{'constraints/gpio.sgdc':{'file_type':'user'}},{'constraints/load_cdc.tcl':{'file_type':'tclSource'}}]}
    targets={'default':dict(base),
      'elab':dict(base,default_tool='vcs',tools={'vcs':{'vcs_options':['-full64','-sverilog','-timescale=1ns/1ps','-ntb_opts','uvm-1.2','-l','compile.log']}}),
      'lint':dict(base,filesets=['generated','rtl','lint_waivers'],default_tool='spyglass',tools={'spyglass':{'goals':['lint/lint_rtl'],'spyglass_options':['enableSV yes','handlememory yes']}}),
      'synth':dict(base,default_tool='design_compiler',tools={'design_compiler':{'script_dir':'$::env(IP_ROOT)/scripts/ppa','dc_script':'synth.tcl','report_dir':'reports'}})}
    for stage, goals in {'cdc':['cdc/cdc_setup_check','cdc/cdc_verify_struct'], 'rdc':['rdc/rdc_verify_struct']}.items():
        targets[stage]=dict(base,filesets=['generated','rtl','cdc_constraints'],default_tool='spyglass',tools={'spyglass':{'goals':goals,'spyglass_options':['enableSV yes','handlememory yes']}})
    for test in sorted((root/'verification/unit_test').glob('ut_*.sv')):
        filesets[test.stem]={'files':[str(test.relative_to(root))],'file_type':'systemVerilogSource'}
        targets[test.stem]={'filesets':['generated','rtl',test.stem],'toplevel':test.stem,'default_tool':'vcs',
                           'tools':{'vcs':{'vcs_options':['-full64','-sverilog','-timescale=1ns/1ps','-ntb_opts','uvm-1.2','-l','compile.log']}}}
    package=yaml.safe_load((root/'ip-package.yaml').read_text())
    core={'name':package['vlnv'],'description':'Parameterized GPIO with APB4 and retained AON wake mailbox',
          'parameters':parameters,'filesets':filesets,'targets':targets}
    target=root/'aixsilicon_ip_gpio.core'
    target.write_text('CAPI=2:\n# Generated by scripts/generate_core.py; do not edit.\n'+yaml.safe_dump(core,sort_keys=False,allow_unicode=True))
    print('Generated '+str(target))


if __name__=='__main__':main()
