"""Generate native CSR with simulation-only checks in a separate bind file.

The native exporter template is adapted before rendering, never by editing its
generated RTL. Refuse unknown template changes; preserve both native checks.
"""
from pathlib import Path
import hashlib
import importlib.metadata
import json
import re

import jinja2
import peakrdl_regblock
from peakrdl_regblock import RegblockExporter
from peakrdl_regblock.cpuif.passthrough import PassthroughCpuif
from peakrdl_regblock.udps import ALL_UDPS
from systemrdl import RDLCompiler


def main():
    root = Path(__file__).resolve().parents[1]
    template_path = Path(peakrdl_regblock.__file__).parent / 'module_tmpl.sv'
    original = template_path.read_text()
    pattern = r'            `ifndef SYNTHESIS\n(.*?)            `endif\n'
    matches = list(re.finditer(pattern, original, re.S))
    if len(matches) != 1:
        raise ValueError('review required: native assertion template changed')
    assertions = matches[0].group(1)
    if assertions.count(': assert(') != 2 or not all(name in assertions for name in ('assert_bad_ext_wr_ack', 'assert_bad_ext_rd_ack')):
        raise ValueError('review required: unexpected native assertion inventory')
    adapted = original[:matches[0].start()] + original[matches[0].end():]
    exporter = RegblockExporter()
    exporter.jj_env.loader = jinja2.ChoiceLoader([
        jinja2.DictLoader({'module_tmpl.sv': adapted}), exporter.jj_env.loader])
    compiler = RDLCompiler()
    for definition in ALL_UDPS:
        compiler.register_udp(definition)
    compiler.compile_file(str(root/'regs/gpio.rdl'))
    design = compiler.elaborate()
    exporter.export(design, str(root/'rtl/generated'), cpuif_cls=PassthroughCpuif,
                    module_name='gpio_csr', package_name='gpio_csr_pkg',
                    default_reset_activelow=True, default_reset_async=True,
                    err_if_bad_addr=True)
    target = root/'verification/assertions/gpio_csr_checks.sv'
    target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text('// Generated by scripts/regenerate_native_csr.py; do not edit.\n'
        'module gpio_csr_checks(input logic clk, arst_n, external_wr_ack, external_rd_ack,\n'
        '                       external_pending, decoded_req_is_external);\n'
        '  always @(posedge clk) begin\n    if (arst_n) begin\n'+assertions+
        '    end\n  end\nendmodule\n'
        'bind gpio_csr gpio_csr_checks u_gpio_csr_checks(.*);\n')
    paths=[root/'regs/gpio.rdl',root/'scripts/regenerate_native_csr.py',
           root/'rtl/generated/gpio_csr.sv',root/'rtl/generated/gpio_csr_pkg.sv',target]
    record={'generator':'peakrdl-regblock','version':importlib.metadata.version('peakrdl-regblock'),
            'native_template_sha256':hashlib.sha256(original.encode()).hexdigest(),
            'cpuif':'PassthroughCpuif; the GPIO APB wrapper issues requests only during Access, preserving arbitrary Setup duration.',
            'adaptation':'Move the two simulation-only external ACK assertions to a generated bind checker; native register decode is unchanged.',
            'files':{str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}}
    (root/'rtl/generated/gpio_native_generation.json').write_text(json.dumps(record,indent=2)+'\n')
    print('Generated native CSR and separate ACK assertions')


if __name__ == '__main__':
    main()
