
// This file was autogenerated by PeakRDL-uvm
package watchdog_ral;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - watchdog_regs::IP_ID
    class watchdog_regs__IP_ID extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__IP_ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h57445431, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__IP_ID

    // reg - watchdog_regs::VERSION
    class watchdog_regs__VERSION extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__VERSION");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h10000, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__VERSION

    // reg - watchdog_regs::CAPABILITY0
    class watchdog_regs__CAPABILITY0 extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__CAPABILITY0");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h410000, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__CAPABILITY0

    // reg - watchdog_regs::CAPABILITY1
    class watchdog_regs__CAPABILITY1 extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__CAPABILITY1");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__CAPABILITY1

    // reg - watchdog_regs::CMD_STATUS
    class watchdog_regs__CMD_STATUS extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__CMD_STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__CMD_STATUS

    // reg - watchdog_regs::ISSUED_SEQ
    class watchdog_regs__ISSUED_SEQ extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__ISSUED_SEQ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__ISSUED_SEQ

    // reg - watchdog_regs::DONE_SEQ
    class watchdog_regs__DONE_SEQ extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__DONE_SEQ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__DONE_SEQ

    // reg - watchdog_regs::DONE_INFO
    class watchdog_regs__DONE_INFO extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__DONE_INFO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__DONE_INFO

    // reg - watchdog_regs::IRQ_SUMMARY
    class watchdog_regs__IRQ_SUMMARY extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__IRQ_SUMMARY");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__IRQ_SUMMARY

    // reg - watchdog_regs::FAULT_SUMMARY
    class watchdog_regs__FAULT_SUMMARY extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__FAULT_SUMMARY");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__FAULT_SUMMARY

    // reg - watchdog_regs::RESET_SUMMARY
    class watchdog_regs__RESET_SUMMARY extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__RESET_SUMMARY");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__RESET_SUMMARY

    // reg - watchdog_regs::channel_regs::CTRL_STAGE
    class watchdog_regs__channel_regs__CTRL_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CTRL_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 13, 0, "RW", 0, 'hc, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CTRL_STAGE

    // reg - watchdog_regs::channel_regs::PRESCALE_STAGE
    class watchdog_regs__channel_regs__PRESCALE_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__PRESCALE_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__PRESCALE_STAGE

    // reg - watchdog_regs::channel_regs::WIN_MIN_LO_STAGE
    class watchdog_regs__channel_regs__WIN_MIN_LO_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__WIN_MIN_LO_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__WIN_MIN_LO_STAGE

    // reg - watchdog_regs::channel_regs::WIN_MIN_HI_STAGE
    class watchdog_regs__channel_regs__WIN_MIN_HI_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__WIN_MIN_HI_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__WIN_MIN_HI_STAGE

    // reg - watchdog_regs::channel_regs::TIMEOUT_LO_STAGE
    class watchdog_regs__channel_regs__TIMEOUT_LO_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__TIMEOUT_LO_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h10000, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__TIMEOUT_LO_STAGE

    // reg - watchdog_regs::channel_regs::TIMEOUT_HI_STAGE
    class watchdog_regs__channel_regs__TIMEOUT_HI_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__TIMEOUT_HI_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__TIMEOUT_HI_STAGE

    // reg - watchdog_regs::channel_regs::PRETIMEOUT_LO_STAGE
    class watchdog_regs__channel_regs__PRETIMEOUT_LO_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__PRETIMEOUT_LO_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__PRETIMEOUT_LO_STAGE

    // reg - watchdog_regs::channel_regs::PRETIMEOUT_HI_STAGE
    class watchdog_regs__channel_regs__PRETIMEOUT_HI_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__PRETIMEOUT_HI_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__PRETIMEOUT_HI_STAGE

    // reg - watchdog_regs::channel_regs::BOOT_TIMEOUT_LO_STAGE
    class watchdog_regs__channel_regs__BOOT_TIMEOUT_LO_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__BOOT_TIMEOUT_LO_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h10000, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__BOOT_TIMEOUT_LO_STAGE

    // reg - watchdog_regs::channel_regs::BOOT_TIMEOUT_HI_STAGE
    class watchdog_regs__channel_regs__BOOT_TIMEOUT_HI_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__BOOT_TIMEOUT_HI_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__BOOT_TIMEOUT_HI_STAGE

    // reg - watchdog_regs::channel_regs::SEQ_LIMIT_STAGE
    class watchdog_regs__channel_regs__SEQ_LIMIT_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__SEQ_LIMIT_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h100, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__SEQ_LIMIT_STAGE

    // reg - watchdog_regs::channel_regs::REQUIRE_MASK_STAGE
    class watchdog_regs__channel_regs__REQUIRE_MASK_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__REQUIRE_MASK_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h1, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__REQUIRE_MASK_STAGE

    // reg - watchdog_regs::channel_regs::FAULT_POLICY_STAGE
    class watchdog_regs__channel_regs__FAULT_POLICY_STAGE extends uvm_reg;
        rand uvm_reg_field value_1;

        function new(string name = "watchdog_regs__channel_regs__FAULT_POLICY_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_1 = new("value_1");
            this.value_1.configure(this, 10, 1, "RW", 0, 'h1ef, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FAULT_POLICY_STAGE

    // reg - watchdog_regs::channel_regs::LOCAL_DELAY_STAGE
    class watchdog_regs__channel_regs__LOCAL_DELAY_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__LOCAL_DELAY_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__LOCAL_DELAY_STAGE

    // reg - watchdog_regs::channel_regs::FINAL_DELAY_STAGE
    class watchdog_regs__channel_regs__FINAL_DELAY_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FINAL_DELAY_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FINAL_DELAY_STAGE

    // reg - watchdog_regs::channel_regs::RECOVERY_LIMIT_STAGE
    class watchdog_regs__channel_regs__RECOVERY_LIMIT_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__RECOVERY_LIMIT_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__RECOVERY_LIMIT_STAGE

    // reg - watchdog_regs::channel_regs::UNLOCK
    class watchdog_regs__channel_regs__UNLOCK extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__UNLOCK");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__UNLOCK

    // reg - watchdog_regs::channel_regs::COMMAND
    class watchdog_regs__channel_regs__COMMAND extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__COMMAND");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 8, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__COMMAND

    // reg - watchdog_regs::channel_regs::LOCK_SET
    class watchdog_regs__channel_regs__LOCK_SET extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__LOCK_SET");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 4, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__LOCK_SET

    // reg - watchdog_regs::channel_regs::SERVICE_SELECT
    class watchdog_regs__channel_regs__SERVICE_SELECT extends uvm_reg;
        rand uvm_reg_field value_0;
        rand uvm_reg_field value_8;

        function new(string name = "watchdog_regs__channel_regs__SERVICE_SELECT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 5, 0, "RW", 0, 'h0, 1, 1, 0);
            this.value_8 = new("value_8");
            this.value_8.configure(this, 3, 8, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__SERVICE_SELECT

    // reg - watchdog_regs::channel_regs::SERVICE
    class watchdog_regs__channel_regs__SERVICE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__SERVICE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__SERVICE

    // reg - watchdog_regs::channel_regs::IRQ_ENABLE
    class watchdog_regs__channel_regs__IRQ_ENABLE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__IRQ_ENABLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 19, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__IRQ_ENABLE

    // reg - watchdog_regs::channel_regs::IRQ_CLEAR
    class watchdog_regs__channel_regs__IRQ_CLEAR extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__IRQ_CLEAR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 19, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__IRQ_CLEAR

    // reg - watchdog_regs::channel_regs::IRQ_TEST
    class watchdog_regs__channel_regs__IRQ_TEST extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__IRQ_TEST");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__IRQ_TEST

    // reg - watchdog_regs::channel_regs::DIAG_CLEAR
    class watchdog_regs__channel_regs__DIAG_CLEAR extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__DIAG_CLEAR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 2, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__DIAG_CLEAR

    // reg - watchdog_regs::channel_regs::FAULT_INJECT
    class watchdog_regs__channel_regs__FAULT_INJECT extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FAULT_INJECT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 10, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FAULT_INJECT

    // reg - watchdog_regs::channel_regs::SNAP_META
    class watchdog_regs__channel_regs__SNAP_META extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__SNAP_META");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__SNAP_META

    // reg - watchdog_regs::channel_regs::SNAP_SEQ
    class watchdog_regs__channel_regs__SNAP_SEQ extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__SNAP_SEQ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__SNAP_SEQ

    // reg - watchdog_regs::channel_regs::STATUS_SNAP
    class watchdog_regs__channel_regs__STATUS_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__STATUS_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__STATUS_SNAP

    // reg - watchdog_regs::channel_regs::CFG_VERSION_SNAP
    class watchdog_regs__channel_regs__CFG_VERSION_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CFG_VERSION_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CFG_VERSION_SNAP

    // reg - watchdog_regs::channel_regs::COUNT_LO_SNAP
    class watchdog_regs__channel_regs__COUNT_LO_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__COUNT_LO_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__COUNT_LO_SNAP

    // reg - watchdog_regs::channel_regs::COUNT_HI_SNAP
    class watchdog_regs__channel_regs__COUNT_HI_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__COUNT_HI_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__COUNT_HI_SNAP

    // reg - watchdog_regs::channel_regs::EVENT_RAW_SNAP
    class watchdog_regs__channel_regs__EVENT_RAW_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__EVENT_RAW_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__EVENT_RAW_SNAP

    // reg - watchdog_regs::channel_regs::IRQ_ENABLE_SNAP
    class watchdog_regs__channel_regs__IRQ_ENABLE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__IRQ_ENABLE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__IRQ_ENABLE_SNAP

    // reg - watchdog_regs::channel_regs::SEEN_MASK_SNAP
    class watchdog_regs__channel_regs__SEEN_MASK_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__SEEN_MASK_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__SEEN_MASK_SNAP

    // reg - watchdog_regs::channel_regs::MISSING_MASK_SNAP
    class watchdog_regs__channel_regs__MISSING_MASK_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__MISSING_MASK_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__MISSING_MASK_SNAP

    // reg - watchdog_regs::channel_regs::LAST_SERVICE_SEQ_SNAP
    class watchdog_regs__channel_regs__LAST_SERVICE_SEQ_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__LAST_SERVICE_SEQ_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__LAST_SERVICE_SEQ_SNAP

    // reg - watchdog_regs::channel_regs::FAULT_COUNT_SNAP
    class watchdog_regs__channel_regs__FAULT_COUNT_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FAULT_COUNT_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FAULT_COUNT_SNAP

    // reg - watchdog_regs::channel_regs::RECOVERY_COUNT_SNAP
    class watchdog_regs__channel_regs__RECOVERY_COUNT_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__RECOVERY_COUNT_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__RECOVERY_COUNT_SNAP

    // reg - watchdog_regs::channel_regs::ESC_AGE_SNAP
    class watchdog_regs__channel_regs__ESC_AGE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__ESC_AGE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__ESC_AGE_SNAP

    // reg - watchdog_regs::channel_regs::FIRST_FLAGS_SNAP
    class watchdog_regs__channel_regs__FIRST_FLAGS_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FIRST_FLAGS_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FIRST_FLAGS_SNAP

    // reg - watchdog_regs::channel_regs::FIRST_CAUSE_SNAP
    class watchdog_regs__channel_regs__FIRST_CAUSE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FIRST_CAUSE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FIRST_CAUSE_SNAP

    // reg - watchdog_regs::channel_regs::FIRST_COUNT_LO_SNAP
    class watchdog_regs__channel_regs__FIRST_COUNT_LO_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FIRST_COUNT_LO_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FIRST_COUNT_LO_SNAP

    // reg - watchdog_regs::channel_regs::FIRST_COUNT_HI_SNAP
    class watchdog_regs__channel_regs__FIRST_COUNT_HI_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FIRST_COUNT_HI_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FIRST_COUNT_HI_SNAP

    // reg - watchdog_regs::channel_regs::FIRST_SOURCE_SNAP
    class watchdog_regs__channel_regs__FIRST_SOURCE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FIRST_SOURCE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FIRST_SOURCE_SNAP

    // reg - watchdog_regs::channel_regs::FIRST_CFG_VERSION_SNAP
    class watchdog_regs__channel_regs__FIRST_CFG_VERSION_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FIRST_CFG_VERSION_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FIRST_CFG_VERSION_SNAP

    // reg - watchdog_regs::channel_regs::FIRST_MISSING_SNAP
    class watchdog_regs__channel_regs__FIRST_MISSING_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FIRST_MISSING_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FIRST_MISSING_SNAP

    // reg - watchdog_regs::channel_regs::FIRST_SERVICE_SEQ_SNAP
    class watchdog_regs__channel_regs__FIRST_SERVICE_SEQ_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FIRST_SERVICE_SEQ_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FIRST_SERVICE_SEQ_SNAP

    // reg - watchdog_regs::channel_regs::FIRST_STATE_SNAP
    class watchdog_regs__channel_regs__FIRST_STATE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FIRST_STATE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FIRST_STATE_SNAP

    // reg - watchdog_regs::channel_regs::CTRL_ACTIVE_SNAP
    class watchdog_regs__channel_regs__CTRL_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CTRL_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CTRL_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::PRESCALE_ACTIVE_SNAP
    class watchdog_regs__channel_regs__PRESCALE_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__PRESCALE_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__PRESCALE_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::WIN_MIN_LO_ACTIVE_SNAP
    class watchdog_regs__channel_regs__WIN_MIN_LO_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__WIN_MIN_LO_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__WIN_MIN_LO_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::WIN_MIN_HI_ACTIVE_SNAP
    class watchdog_regs__channel_regs__WIN_MIN_HI_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__WIN_MIN_HI_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__WIN_MIN_HI_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::TIMEOUT_LO_ACTIVE_SNAP
    class watchdog_regs__channel_regs__TIMEOUT_LO_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__TIMEOUT_LO_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__TIMEOUT_LO_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::TIMEOUT_HI_ACTIVE_SNAP
    class watchdog_regs__channel_regs__TIMEOUT_HI_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__TIMEOUT_HI_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__TIMEOUT_HI_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::PRETIMEOUT_LO_ACTIVE_SNAP
    class watchdog_regs__channel_regs__PRETIMEOUT_LO_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__PRETIMEOUT_LO_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__PRETIMEOUT_LO_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::PRETIMEOUT_HI_ACTIVE_SNAP
    class watchdog_regs__channel_regs__PRETIMEOUT_HI_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__PRETIMEOUT_HI_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__PRETIMEOUT_HI_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::BOOT_TIMEOUT_LO_ACTIVE_SNAP
    class watchdog_regs__channel_regs__BOOT_TIMEOUT_LO_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__BOOT_TIMEOUT_LO_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__BOOT_TIMEOUT_LO_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::BOOT_TIMEOUT_HI_ACTIVE_SNAP
    class watchdog_regs__channel_regs__BOOT_TIMEOUT_HI_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__BOOT_TIMEOUT_HI_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__BOOT_TIMEOUT_HI_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::SEQ_LIMIT_ACTIVE_SNAP
    class watchdog_regs__channel_regs__SEQ_LIMIT_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__SEQ_LIMIT_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__SEQ_LIMIT_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::REQUIRE_MASK_ACTIVE_SNAP
    class watchdog_regs__channel_regs__REQUIRE_MASK_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__REQUIRE_MASK_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__REQUIRE_MASK_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::FAULT_POLICY_ACTIVE_SNAP
    class watchdog_regs__channel_regs__FAULT_POLICY_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FAULT_POLICY_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FAULT_POLICY_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::LOCAL_DELAY_ACTIVE_SNAP
    class watchdog_regs__channel_regs__LOCAL_DELAY_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__LOCAL_DELAY_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__LOCAL_DELAY_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::FINAL_DELAY_ACTIVE_SNAP
    class watchdog_regs__channel_regs__FINAL_DELAY_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__FINAL_DELAY_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__FINAL_DELAY_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::RECOVERY_LIMIT_ACTIVE_SNAP
    class watchdog_regs__channel_regs__RECOVERY_LIMIT_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__RECOVERY_LIMIT_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__RECOVERY_LIMIT_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_SELECT
    class watchdog_regs__channel_regs__CLIENT_SELECT extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_SELECT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 5, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_SELECT

    // reg - watchdog_regs::channel_regs::CLIENT_OWNER_STAGE
    class watchdog_regs__channel_regs__CLIENT_OWNER_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_OWNER_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_OWNER_STAGE

    // reg - watchdog_regs::channel_regs::CLIENT_ALIVE_STAGE
    class watchdog_regs__channel_regs__CLIENT_ALIVE_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_ALIVE_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_ALIVE_STAGE

    // reg - watchdog_regs::channel_regs::CLIENT_FLOW_STAGE
    class watchdog_regs__channel_regs__CLIENT_FLOW_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_FLOW_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_FLOW_STAGE

    // reg - watchdog_regs::channel_regs::CLIENT_DEADLINE_MIN_LO_STAGE
    class watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_LO_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_LO_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_LO_STAGE

    // reg - watchdog_regs::channel_regs::CLIENT_DEADLINE_MIN_HI_STAGE
    class watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_HI_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_HI_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_HI_STAGE

    // reg - watchdog_regs::channel_regs::CLIENT_DEADLINE_MAX_LO_STAGE
    class watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_LO_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_LO_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_LO_STAGE

    // reg - watchdog_regs::channel_regs::CLIENT_DEADLINE_MAX_HI_STAGE
    class watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_HI_STAGE extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_HI_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_HI_STAGE

    // reg - watchdog_regs::channel_regs::CLIENT_FLAGS_SNAP
    class watchdog_regs__channel_regs__CLIENT_FLAGS_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_FLAGS_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_FLAGS_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_TOKEN_SNAP
    class watchdog_regs__channel_regs__CLIENT_TOKEN_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_TOKEN_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_TOKEN_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_ALIVE_COUNT_SNAP
    class watchdog_regs__channel_regs__CLIENT_ALIVE_COUNT_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_ALIVE_COUNT_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_ALIVE_COUNT_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_ELAPSED_LO_SNAP
    class watchdog_regs__channel_regs__CLIENT_ELAPSED_LO_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_ELAPSED_LO_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_ELAPSED_LO_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_ELAPSED_HI_SNAP
    class watchdog_regs__channel_regs__CLIENT_ELAPSED_HI_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_ELAPSED_HI_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_ELAPSED_HI_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_OWNER_ACTIVE_SNAP
    class watchdog_regs__channel_regs__CLIENT_OWNER_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_OWNER_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_OWNER_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_ALIVE_ACTIVE_SNAP
    class watchdog_regs__channel_regs__CLIENT_ALIVE_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_ALIVE_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_ALIVE_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_FLOW_ACTIVE_SNAP
    class watchdog_regs__channel_regs__CLIENT_FLOW_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_FLOW_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_FLOW_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP
    class watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP
    class watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP
    class watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP

    // reg - watchdog_regs::channel_regs::CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP
    class watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP extends uvm_reg;
        rand uvm_reg_field value_0;

        function new(string name = "watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value_0 = new("value_0");
            this.value_0.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP

    // regfile - watchdog_regs::channel_regs
    class watchdog_regs__channel_regs extends uvm_reg_block;
        rand watchdog_regs__channel_regs__CTRL_STAGE CTRL_STAGE;
        rand watchdog_regs__channel_regs__PRESCALE_STAGE PRESCALE_STAGE;
        rand watchdog_regs__channel_regs__WIN_MIN_LO_STAGE WIN_MIN_LO_STAGE;
        rand watchdog_regs__channel_regs__WIN_MIN_HI_STAGE WIN_MIN_HI_STAGE;
        rand watchdog_regs__channel_regs__TIMEOUT_LO_STAGE TIMEOUT_LO_STAGE;
        rand watchdog_regs__channel_regs__TIMEOUT_HI_STAGE TIMEOUT_HI_STAGE;
        rand watchdog_regs__channel_regs__PRETIMEOUT_LO_STAGE PRETIMEOUT_LO_STAGE;
        rand watchdog_regs__channel_regs__PRETIMEOUT_HI_STAGE PRETIMEOUT_HI_STAGE;
        rand watchdog_regs__channel_regs__BOOT_TIMEOUT_LO_STAGE BOOT_TIMEOUT_LO_STAGE;
        rand watchdog_regs__channel_regs__BOOT_TIMEOUT_HI_STAGE BOOT_TIMEOUT_HI_STAGE;
        rand watchdog_regs__channel_regs__SEQ_LIMIT_STAGE SEQ_LIMIT_STAGE;
        rand watchdog_regs__channel_regs__REQUIRE_MASK_STAGE REQUIRE_MASK_STAGE;
        rand watchdog_regs__channel_regs__FAULT_POLICY_STAGE FAULT_POLICY_STAGE;
        rand watchdog_regs__channel_regs__LOCAL_DELAY_STAGE LOCAL_DELAY_STAGE;
        rand watchdog_regs__channel_regs__FINAL_DELAY_STAGE FINAL_DELAY_STAGE;
        rand watchdog_regs__channel_regs__RECOVERY_LIMIT_STAGE RECOVERY_LIMIT_STAGE;
        rand watchdog_regs__channel_regs__UNLOCK UNLOCK;
        rand watchdog_regs__channel_regs__COMMAND COMMAND;
        rand watchdog_regs__channel_regs__LOCK_SET LOCK_SET;
        rand watchdog_regs__channel_regs__SERVICE_SELECT SERVICE_SELECT;
        rand watchdog_regs__channel_regs__SERVICE SERVICE;
        rand watchdog_regs__channel_regs__IRQ_ENABLE IRQ_ENABLE;
        rand watchdog_regs__channel_regs__IRQ_CLEAR IRQ_CLEAR;
        rand watchdog_regs__channel_regs__IRQ_TEST IRQ_TEST;
        rand watchdog_regs__channel_regs__DIAG_CLEAR DIAG_CLEAR;
        rand watchdog_regs__channel_regs__FAULT_INJECT FAULT_INJECT;
        rand watchdog_regs__channel_regs__SNAP_META SNAP_META;
        rand watchdog_regs__channel_regs__SNAP_SEQ SNAP_SEQ;
        rand watchdog_regs__channel_regs__STATUS_SNAP STATUS_SNAP;
        rand watchdog_regs__channel_regs__CFG_VERSION_SNAP CFG_VERSION_SNAP;
        rand watchdog_regs__channel_regs__COUNT_LO_SNAP COUNT_LO_SNAP;
        rand watchdog_regs__channel_regs__COUNT_HI_SNAP COUNT_HI_SNAP;
        rand watchdog_regs__channel_regs__EVENT_RAW_SNAP EVENT_RAW_SNAP;
        rand watchdog_regs__channel_regs__IRQ_ENABLE_SNAP IRQ_ENABLE_SNAP;
        rand watchdog_regs__channel_regs__SEEN_MASK_SNAP SEEN_MASK_SNAP;
        rand watchdog_regs__channel_regs__MISSING_MASK_SNAP MISSING_MASK_SNAP;
        rand watchdog_regs__channel_regs__LAST_SERVICE_SEQ_SNAP LAST_SERVICE_SEQ_SNAP;
        rand watchdog_regs__channel_regs__FAULT_COUNT_SNAP FAULT_COUNT_SNAP;
        rand watchdog_regs__channel_regs__RECOVERY_COUNT_SNAP RECOVERY_COUNT_SNAP;
        rand watchdog_regs__channel_regs__ESC_AGE_SNAP ESC_AGE_SNAP;
        rand watchdog_regs__channel_regs__FIRST_FLAGS_SNAP FIRST_FLAGS_SNAP;
        rand watchdog_regs__channel_regs__FIRST_CAUSE_SNAP FIRST_CAUSE_SNAP;
        rand watchdog_regs__channel_regs__FIRST_COUNT_LO_SNAP FIRST_COUNT_LO_SNAP;
        rand watchdog_regs__channel_regs__FIRST_COUNT_HI_SNAP FIRST_COUNT_HI_SNAP;
        rand watchdog_regs__channel_regs__FIRST_SOURCE_SNAP FIRST_SOURCE_SNAP;
        rand watchdog_regs__channel_regs__FIRST_CFG_VERSION_SNAP FIRST_CFG_VERSION_SNAP;
        rand watchdog_regs__channel_regs__FIRST_MISSING_SNAP FIRST_MISSING_SNAP;
        rand watchdog_regs__channel_regs__FIRST_SERVICE_SEQ_SNAP FIRST_SERVICE_SEQ_SNAP;
        rand watchdog_regs__channel_regs__FIRST_STATE_SNAP FIRST_STATE_SNAP;
        rand watchdog_regs__channel_regs__CTRL_ACTIVE_SNAP CTRL_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__PRESCALE_ACTIVE_SNAP PRESCALE_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__WIN_MIN_LO_ACTIVE_SNAP WIN_MIN_LO_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__WIN_MIN_HI_ACTIVE_SNAP WIN_MIN_HI_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__TIMEOUT_LO_ACTIVE_SNAP TIMEOUT_LO_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__TIMEOUT_HI_ACTIVE_SNAP TIMEOUT_HI_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__PRETIMEOUT_LO_ACTIVE_SNAP PRETIMEOUT_LO_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__PRETIMEOUT_HI_ACTIVE_SNAP PRETIMEOUT_HI_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__BOOT_TIMEOUT_LO_ACTIVE_SNAP BOOT_TIMEOUT_LO_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__BOOT_TIMEOUT_HI_ACTIVE_SNAP BOOT_TIMEOUT_HI_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__SEQ_LIMIT_ACTIVE_SNAP SEQ_LIMIT_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__REQUIRE_MASK_ACTIVE_SNAP REQUIRE_MASK_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__FAULT_POLICY_ACTIVE_SNAP FAULT_POLICY_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__LOCAL_DELAY_ACTIVE_SNAP LOCAL_DELAY_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__FINAL_DELAY_ACTIVE_SNAP FINAL_DELAY_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__RECOVERY_LIMIT_ACTIVE_SNAP RECOVERY_LIMIT_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_SELECT CLIENT_SELECT;
        rand watchdog_regs__channel_regs__CLIENT_OWNER_STAGE CLIENT_OWNER_STAGE;
        rand watchdog_regs__channel_regs__CLIENT_ALIVE_STAGE CLIENT_ALIVE_STAGE;
        rand watchdog_regs__channel_regs__CLIENT_FLOW_STAGE CLIENT_FLOW_STAGE;
        rand watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_LO_STAGE CLIENT_DEADLINE_MIN_LO_STAGE;
        rand watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_HI_STAGE CLIENT_DEADLINE_MIN_HI_STAGE;
        rand watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_LO_STAGE CLIENT_DEADLINE_MAX_LO_STAGE;
        rand watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_HI_STAGE CLIENT_DEADLINE_MAX_HI_STAGE;
        rand watchdog_regs__channel_regs__CLIENT_FLAGS_SNAP CLIENT_FLAGS_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_TOKEN_SNAP CLIENT_TOKEN_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_ALIVE_COUNT_SNAP CLIENT_ALIVE_COUNT_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_ELAPSED_LO_SNAP CLIENT_ELAPSED_LO_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_ELAPSED_HI_SNAP CLIENT_ELAPSED_HI_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_OWNER_ACTIVE_SNAP CLIENT_OWNER_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_ALIVE_ACTIVE_SNAP CLIENT_ALIVE_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_FLOW_ACTIVE_SNAP CLIENT_FLOW_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP;
        rand watchdog_regs__channel_regs__CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP;

        function new(string name = "watchdog_regs__channel_regs");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.CTRL_STAGE = new("CTRL_STAGE");
            this.CTRL_STAGE.configure(this);

            this.CTRL_STAGE.build();
            this.default_map.add_reg(this.CTRL_STAGE, 'h0);
            this.PRESCALE_STAGE = new("PRESCALE_STAGE");
            this.PRESCALE_STAGE.configure(this);

            this.PRESCALE_STAGE.build();
            this.default_map.add_reg(this.PRESCALE_STAGE, 'h4);
            this.WIN_MIN_LO_STAGE = new("WIN_MIN_LO_STAGE");
            this.WIN_MIN_LO_STAGE.configure(this);

            this.WIN_MIN_LO_STAGE.build();
            this.default_map.add_reg(this.WIN_MIN_LO_STAGE, 'h8);
            this.WIN_MIN_HI_STAGE = new("WIN_MIN_HI_STAGE");
            this.WIN_MIN_HI_STAGE.configure(this);

            this.WIN_MIN_HI_STAGE.build();
            this.default_map.add_reg(this.WIN_MIN_HI_STAGE, 'hc);
            this.TIMEOUT_LO_STAGE = new("TIMEOUT_LO_STAGE");
            this.TIMEOUT_LO_STAGE.configure(this);

            this.TIMEOUT_LO_STAGE.build();
            this.default_map.add_reg(this.TIMEOUT_LO_STAGE, 'h10);
            this.TIMEOUT_HI_STAGE = new("TIMEOUT_HI_STAGE");
            this.TIMEOUT_HI_STAGE.configure(this);

            this.TIMEOUT_HI_STAGE.build();
            this.default_map.add_reg(this.TIMEOUT_HI_STAGE, 'h14);
            this.PRETIMEOUT_LO_STAGE = new("PRETIMEOUT_LO_STAGE");
            this.PRETIMEOUT_LO_STAGE.configure(this);

            this.PRETIMEOUT_LO_STAGE.build();
            this.default_map.add_reg(this.PRETIMEOUT_LO_STAGE, 'h18);
            this.PRETIMEOUT_HI_STAGE = new("PRETIMEOUT_HI_STAGE");
            this.PRETIMEOUT_HI_STAGE.configure(this);

            this.PRETIMEOUT_HI_STAGE.build();
            this.default_map.add_reg(this.PRETIMEOUT_HI_STAGE, 'h1c);
            this.BOOT_TIMEOUT_LO_STAGE = new("BOOT_TIMEOUT_LO_STAGE");
            this.BOOT_TIMEOUT_LO_STAGE.configure(this);

            this.BOOT_TIMEOUT_LO_STAGE.build();
            this.default_map.add_reg(this.BOOT_TIMEOUT_LO_STAGE, 'h20);
            this.BOOT_TIMEOUT_HI_STAGE = new("BOOT_TIMEOUT_HI_STAGE");
            this.BOOT_TIMEOUT_HI_STAGE.configure(this);

            this.BOOT_TIMEOUT_HI_STAGE.build();
            this.default_map.add_reg(this.BOOT_TIMEOUT_HI_STAGE, 'h24);
            this.SEQ_LIMIT_STAGE = new("SEQ_LIMIT_STAGE");
            this.SEQ_LIMIT_STAGE.configure(this);

            this.SEQ_LIMIT_STAGE.build();
            this.default_map.add_reg(this.SEQ_LIMIT_STAGE, 'h28);
            this.REQUIRE_MASK_STAGE = new("REQUIRE_MASK_STAGE");
            this.REQUIRE_MASK_STAGE.configure(this);

            this.REQUIRE_MASK_STAGE.build();
            this.default_map.add_reg(this.REQUIRE_MASK_STAGE, 'h2c);
            this.FAULT_POLICY_STAGE = new("FAULT_POLICY_STAGE");
            this.FAULT_POLICY_STAGE.configure(this);

            this.FAULT_POLICY_STAGE.build();
            this.default_map.add_reg(this.FAULT_POLICY_STAGE, 'h30);
            this.LOCAL_DELAY_STAGE = new("LOCAL_DELAY_STAGE");
            this.LOCAL_DELAY_STAGE.configure(this);

            this.LOCAL_DELAY_STAGE.build();
            this.default_map.add_reg(this.LOCAL_DELAY_STAGE, 'h34);
            this.FINAL_DELAY_STAGE = new("FINAL_DELAY_STAGE");
            this.FINAL_DELAY_STAGE.configure(this);

            this.FINAL_DELAY_STAGE.build();
            this.default_map.add_reg(this.FINAL_DELAY_STAGE, 'h38);
            this.RECOVERY_LIMIT_STAGE = new("RECOVERY_LIMIT_STAGE");
            this.RECOVERY_LIMIT_STAGE.configure(this);

            this.RECOVERY_LIMIT_STAGE.build();
            this.default_map.add_reg(this.RECOVERY_LIMIT_STAGE, 'h3c);
            this.UNLOCK = new("UNLOCK");
            this.UNLOCK.configure(this);

            this.UNLOCK.build();
            this.default_map.add_reg(this.UNLOCK, 'h40);
            this.COMMAND = new("COMMAND");
            this.COMMAND.configure(this);

            this.COMMAND.build();
            this.default_map.add_reg(this.COMMAND, 'h44);
            this.LOCK_SET = new("LOCK_SET");
            this.LOCK_SET.configure(this);

            this.LOCK_SET.build();
            this.default_map.add_reg(this.LOCK_SET, 'h48);
            this.SERVICE_SELECT = new("SERVICE_SELECT");
            this.SERVICE_SELECT.configure(this);

            this.SERVICE_SELECT.build();
            this.default_map.add_reg(this.SERVICE_SELECT, 'h4c);
            this.SERVICE = new("SERVICE");
            this.SERVICE.configure(this);

            this.SERVICE.build();
            this.default_map.add_reg(this.SERVICE, 'h50);
            this.IRQ_ENABLE = new("IRQ_ENABLE");
            this.IRQ_ENABLE.configure(this);

            this.IRQ_ENABLE.build();
            this.default_map.add_reg(this.IRQ_ENABLE, 'h54);
            this.IRQ_CLEAR = new("IRQ_CLEAR");
            this.IRQ_CLEAR.configure(this);

            this.IRQ_CLEAR.build();
            this.default_map.add_reg(this.IRQ_CLEAR, 'h58);
            this.IRQ_TEST = new("IRQ_TEST");
            this.IRQ_TEST.configure(this);

            this.IRQ_TEST.build();
            this.default_map.add_reg(this.IRQ_TEST, 'h5c);
            this.DIAG_CLEAR = new("DIAG_CLEAR");
            this.DIAG_CLEAR.configure(this);

            this.DIAG_CLEAR.build();
            this.default_map.add_reg(this.DIAG_CLEAR, 'h60);
            this.FAULT_INJECT = new("FAULT_INJECT");
            this.FAULT_INJECT.configure(this);

            this.FAULT_INJECT.build();
            this.default_map.add_reg(this.FAULT_INJECT, 'h64);
            this.SNAP_META = new("SNAP_META");
            this.SNAP_META.configure(this);

            this.SNAP_META.build();
            this.default_map.add_reg(this.SNAP_META, 'h68);
            this.SNAP_SEQ = new("SNAP_SEQ");
            this.SNAP_SEQ.configure(this);

            this.SNAP_SEQ.build();
            this.default_map.add_reg(this.SNAP_SEQ, 'h6c);
            this.STATUS_SNAP = new("STATUS_SNAP");
            this.STATUS_SNAP.configure(this);

            this.STATUS_SNAP.build();
            this.default_map.add_reg(this.STATUS_SNAP, 'h70);
            this.CFG_VERSION_SNAP = new("CFG_VERSION_SNAP");
            this.CFG_VERSION_SNAP.configure(this);

            this.CFG_VERSION_SNAP.build();
            this.default_map.add_reg(this.CFG_VERSION_SNAP, 'h74);
            this.COUNT_LO_SNAP = new("COUNT_LO_SNAP");
            this.COUNT_LO_SNAP.configure(this);

            this.COUNT_LO_SNAP.build();
            this.default_map.add_reg(this.COUNT_LO_SNAP, 'h78);
            this.COUNT_HI_SNAP = new("COUNT_HI_SNAP");
            this.COUNT_HI_SNAP.configure(this);

            this.COUNT_HI_SNAP.build();
            this.default_map.add_reg(this.COUNT_HI_SNAP, 'h7c);
            this.EVENT_RAW_SNAP = new("EVENT_RAW_SNAP");
            this.EVENT_RAW_SNAP.configure(this);

            this.EVENT_RAW_SNAP.build();
            this.default_map.add_reg(this.EVENT_RAW_SNAP, 'h80);
            this.IRQ_ENABLE_SNAP = new("IRQ_ENABLE_SNAP");
            this.IRQ_ENABLE_SNAP.configure(this);

            this.IRQ_ENABLE_SNAP.build();
            this.default_map.add_reg(this.IRQ_ENABLE_SNAP, 'h84);
            this.SEEN_MASK_SNAP = new("SEEN_MASK_SNAP");
            this.SEEN_MASK_SNAP.configure(this);

            this.SEEN_MASK_SNAP.build();
            this.default_map.add_reg(this.SEEN_MASK_SNAP, 'h88);
            this.MISSING_MASK_SNAP = new("MISSING_MASK_SNAP");
            this.MISSING_MASK_SNAP.configure(this);

            this.MISSING_MASK_SNAP.build();
            this.default_map.add_reg(this.MISSING_MASK_SNAP, 'h8c);
            this.LAST_SERVICE_SEQ_SNAP = new("LAST_SERVICE_SEQ_SNAP");
            this.LAST_SERVICE_SEQ_SNAP.configure(this);

            this.LAST_SERVICE_SEQ_SNAP.build();
            this.default_map.add_reg(this.LAST_SERVICE_SEQ_SNAP, 'h90);
            this.FAULT_COUNT_SNAP = new("FAULT_COUNT_SNAP");
            this.FAULT_COUNT_SNAP.configure(this);

            this.FAULT_COUNT_SNAP.build();
            this.default_map.add_reg(this.FAULT_COUNT_SNAP, 'h94);
            this.RECOVERY_COUNT_SNAP = new("RECOVERY_COUNT_SNAP");
            this.RECOVERY_COUNT_SNAP.configure(this);

            this.RECOVERY_COUNT_SNAP.build();
            this.default_map.add_reg(this.RECOVERY_COUNT_SNAP, 'h98);
            this.ESC_AGE_SNAP = new("ESC_AGE_SNAP");
            this.ESC_AGE_SNAP.configure(this);

            this.ESC_AGE_SNAP.build();
            this.default_map.add_reg(this.ESC_AGE_SNAP, 'h9c);
            this.FIRST_FLAGS_SNAP = new("FIRST_FLAGS_SNAP");
            this.FIRST_FLAGS_SNAP.configure(this);

            this.FIRST_FLAGS_SNAP.build();
            this.default_map.add_reg(this.FIRST_FLAGS_SNAP, 'ha0);
            this.FIRST_CAUSE_SNAP = new("FIRST_CAUSE_SNAP");
            this.FIRST_CAUSE_SNAP.configure(this);

            this.FIRST_CAUSE_SNAP.build();
            this.default_map.add_reg(this.FIRST_CAUSE_SNAP, 'ha4);
            this.FIRST_COUNT_LO_SNAP = new("FIRST_COUNT_LO_SNAP");
            this.FIRST_COUNT_LO_SNAP.configure(this);

            this.FIRST_COUNT_LO_SNAP.build();
            this.default_map.add_reg(this.FIRST_COUNT_LO_SNAP, 'ha8);
            this.FIRST_COUNT_HI_SNAP = new("FIRST_COUNT_HI_SNAP");
            this.FIRST_COUNT_HI_SNAP.configure(this);

            this.FIRST_COUNT_HI_SNAP.build();
            this.default_map.add_reg(this.FIRST_COUNT_HI_SNAP, 'hac);
            this.FIRST_SOURCE_SNAP = new("FIRST_SOURCE_SNAP");
            this.FIRST_SOURCE_SNAP.configure(this);

            this.FIRST_SOURCE_SNAP.build();
            this.default_map.add_reg(this.FIRST_SOURCE_SNAP, 'hb0);
            this.FIRST_CFG_VERSION_SNAP = new("FIRST_CFG_VERSION_SNAP");
            this.FIRST_CFG_VERSION_SNAP.configure(this);

            this.FIRST_CFG_VERSION_SNAP.build();
            this.default_map.add_reg(this.FIRST_CFG_VERSION_SNAP, 'hb4);
            this.FIRST_MISSING_SNAP = new("FIRST_MISSING_SNAP");
            this.FIRST_MISSING_SNAP.configure(this);

            this.FIRST_MISSING_SNAP.build();
            this.default_map.add_reg(this.FIRST_MISSING_SNAP, 'hb8);
            this.FIRST_SERVICE_SEQ_SNAP = new("FIRST_SERVICE_SEQ_SNAP");
            this.FIRST_SERVICE_SEQ_SNAP.configure(this);

            this.FIRST_SERVICE_SEQ_SNAP.build();
            this.default_map.add_reg(this.FIRST_SERVICE_SEQ_SNAP, 'hbc);
            this.FIRST_STATE_SNAP = new("FIRST_STATE_SNAP");
            this.FIRST_STATE_SNAP.configure(this);

            this.FIRST_STATE_SNAP.build();
            this.default_map.add_reg(this.FIRST_STATE_SNAP, 'hc0);
            this.CTRL_ACTIVE_SNAP = new("CTRL_ACTIVE_SNAP");
            this.CTRL_ACTIVE_SNAP.configure(this);

            this.CTRL_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.CTRL_ACTIVE_SNAP, 'h100);
            this.PRESCALE_ACTIVE_SNAP = new("PRESCALE_ACTIVE_SNAP");
            this.PRESCALE_ACTIVE_SNAP.configure(this);

            this.PRESCALE_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.PRESCALE_ACTIVE_SNAP, 'h104);
            this.WIN_MIN_LO_ACTIVE_SNAP = new("WIN_MIN_LO_ACTIVE_SNAP");
            this.WIN_MIN_LO_ACTIVE_SNAP.configure(this);

            this.WIN_MIN_LO_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.WIN_MIN_LO_ACTIVE_SNAP, 'h108);
            this.WIN_MIN_HI_ACTIVE_SNAP = new("WIN_MIN_HI_ACTIVE_SNAP");
            this.WIN_MIN_HI_ACTIVE_SNAP.configure(this);

            this.WIN_MIN_HI_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.WIN_MIN_HI_ACTIVE_SNAP, 'h10c);
            this.TIMEOUT_LO_ACTIVE_SNAP = new("TIMEOUT_LO_ACTIVE_SNAP");
            this.TIMEOUT_LO_ACTIVE_SNAP.configure(this);

            this.TIMEOUT_LO_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.TIMEOUT_LO_ACTIVE_SNAP, 'h110);
            this.TIMEOUT_HI_ACTIVE_SNAP = new("TIMEOUT_HI_ACTIVE_SNAP");
            this.TIMEOUT_HI_ACTIVE_SNAP.configure(this);

            this.TIMEOUT_HI_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.TIMEOUT_HI_ACTIVE_SNAP, 'h114);
            this.PRETIMEOUT_LO_ACTIVE_SNAP = new("PRETIMEOUT_LO_ACTIVE_SNAP");
            this.PRETIMEOUT_LO_ACTIVE_SNAP.configure(this);

            this.PRETIMEOUT_LO_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.PRETIMEOUT_LO_ACTIVE_SNAP, 'h118);
            this.PRETIMEOUT_HI_ACTIVE_SNAP = new("PRETIMEOUT_HI_ACTIVE_SNAP");
            this.PRETIMEOUT_HI_ACTIVE_SNAP.configure(this);

            this.PRETIMEOUT_HI_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.PRETIMEOUT_HI_ACTIVE_SNAP, 'h11c);
            this.BOOT_TIMEOUT_LO_ACTIVE_SNAP = new("BOOT_TIMEOUT_LO_ACTIVE_SNAP");
            this.BOOT_TIMEOUT_LO_ACTIVE_SNAP.configure(this);

            this.BOOT_TIMEOUT_LO_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.BOOT_TIMEOUT_LO_ACTIVE_SNAP, 'h120);
            this.BOOT_TIMEOUT_HI_ACTIVE_SNAP = new("BOOT_TIMEOUT_HI_ACTIVE_SNAP");
            this.BOOT_TIMEOUT_HI_ACTIVE_SNAP.configure(this);

            this.BOOT_TIMEOUT_HI_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.BOOT_TIMEOUT_HI_ACTIVE_SNAP, 'h124);
            this.SEQ_LIMIT_ACTIVE_SNAP = new("SEQ_LIMIT_ACTIVE_SNAP");
            this.SEQ_LIMIT_ACTIVE_SNAP.configure(this);

            this.SEQ_LIMIT_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.SEQ_LIMIT_ACTIVE_SNAP, 'h128);
            this.REQUIRE_MASK_ACTIVE_SNAP = new("REQUIRE_MASK_ACTIVE_SNAP");
            this.REQUIRE_MASK_ACTIVE_SNAP.configure(this);

            this.REQUIRE_MASK_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.REQUIRE_MASK_ACTIVE_SNAP, 'h12c);
            this.FAULT_POLICY_ACTIVE_SNAP = new("FAULT_POLICY_ACTIVE_SNAP");
            this.FAULT_POLICY_ACTIVE_SNAP.configure(this);

            this.FAULT_POLICY_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.FAULT_POLICY_ACTIVE_SNAP, 'h130);
            this.LOCAL_DELAY_ACTIVE_SNAP = new("LOCAL_DELAY_ACTIVE_SNAP");
            this.LOCAL_DELAY_ACTIVE_SNAP.configure(this);

            this.LOCAL_DELAY_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.LOCAL_DELAY_ACTIVE_SNAP, 'h134);
            this.FINAL_DELAY_ACTIVE_SNAP = new("FINAL_DELAY_ACTIVE_SNAP");
            this.FINAL_DELAY_ACTIVE_SNAP.configure(this);

            this.FINAL_DELAY_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.FINAL_DELAY_ACTIVE_SNAP, 'h138);
            this.RECOVERY_LIMIT_ACTIVE_SNAP = new("RECOVERY_LIMIT_ACTIVE_SNAP");
            this.RECOVERY_LIMIT_ACTIVE_SNAP.configure(this);

            this.RECOVERY_LIMIT_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.RECOVERY_LIMIT_ACTIVE_SNAP, 'h13c);
            this.CLIENT_SELECT = new("CLIENT_SELECT");
            this.CLIENT_SELECT.configure(this);

            this.CLIENT_SELECT.build();
            this.default_map.add_reg(this.CLIENT_SELECT, 'h140);
            this.CLIENT_OWNER_STAGE = new("CLIENT_OWNER_STAGE");
            this.CLIENT_OWNER_STAGE.configure(this);

            this.CLIENT_OWNER_STAGE.build();
            this.default_map.add_reg(this.CLIENT_OWNER_STAGE, 'h144);
            this.CLIENT_ALIVE_STAGE = new("CLIENT_ALIVE_STAGE");
            this.CLIENT_ALIVE_STAGE.configure(this);

            this.CLIENT_ALIVE_STAGE.build();
            this.default_map.add_reg(this.CLIENT_ALIVE_STAGE, 'h148);
            this.CLIENT_FLOW_STAGE = new("CLIENT_FLOW_STAGE");
            this.CLIENT_FLOW_STAGE.configure(this);

            this.CLIENT_FLOW_STAGE.build();
            this.default_map.add_reg(this.CLIENT_FLOW_STAGE, 'h14c);
            this.CLIENT_DEADLINE_MIN_LO_STAGE = new("CLIENT_DEADLINE_MIN_LO_STAGE");
            this.CLIENT_DEADLINE_MIN_LO_STAGE.configure(this);

            this.CLIENT_DEADLINE_MIN_LO_STAGE.build();
            this.default_map.add_reg(this.CLIENT_DEADLINE_MIN_LO_STAGE, 'h150);
            this.CLIENT_DEADLINE_MIN_HI_STAGE = new("CLIENT_DEADLINE_MIN_HI_STAGE");
            this.CLIENT_DEADLINE_MIN_HI_STAGE.configure(this);

            this.CLIENT_DEADLINE_MIN_HI_STAGE.build();
            this.default_map.add_reg(this.CLIENT_DEADLINE_MIN_HI_STAGE, 'h154);
            this.CLIENT_DEADLINE_MAX_LO_STAGE = new("CLIENT_DEADLINE_MAX_LO_STAGE");
            this.CLIENT_DEADLINE_MAX_LO_STAGE.configure(this);

            this.CLIENT_DEADLINE_MAX_LO_STAGE.build();
            this.default_map.add_reg(this.CLIENT_DEADLINE_MAX_LO_STAGE, 'h158);
            this.CLIENT_DEADLINE_MAX_HI_STAGE = new("CLIENT_DEADLINE_MAX_HI_STAGE");
            this.CLIENT_DEADLINE_MAX_HI_STAGE.configure(this);

            this.CLIENT_DEADLINE_MAX_HI_STAGE.build();
            this.default_map.add_reg(this.CLIENT_DEADLINE_MAX_HI_STAGE, 'h15c);
            this.CLIENT_FLAGS_SNAP = new("CLIENT_FLAGS_SNAP");
            this.CLIENT_FLAGS_SNAP.configure(this);

            this.CLIENT_FLAGS_SNAP.build();
            this.default_map.add_reg(this.CLIENT_FLAGS_SNAP, 'h180);
            this.CLIENT_TOKEN_SNAP = new("CLIENT_TOKEN_SNAP");
            this.CLIENT_TOKEN_SNAP.configure(this);

            this.CLIENT_TOKEN_SNAP.build();
            this.default_map.add_reg(this.CLIENT_TOKEN_SNAP, 'h184);
            this.CLIENT_ALIVE_COUNT_SNAP = new("CLIENT_ALIVE_COUNT_SNAP");
            this.CLIENT_ALIVE_COUNT_SNAP.configure(this);

            this.CLIENT_ALIVE_COUNT_SNAP.build();
            this.default_map.add_reg(this.CLIENT_ALIVE_COUNT_SNAP, 'h188);
            this.CLIENT_ELAPSED_LO_SNAP = new("CLIENT_ELAPSED_LO_SNAP");
            this.CLIENT_ELAPSED_LO_SNAP.configure(this);

            this.CLIENT_ELAPSED_LO_SNAP.build();
            this.default_map.add_reg(this.CLIENT_ELAPSED_LO_SNAP, 'h18c);
            this.CLIENT_ELAPSED_HI_SNAP = new("CLIENT_ELAPSED_HI_SNAP");
            this.CLIENT_ELAPSED_HI_SNAP.configure(this);

            this.CLIENT_ELAPSED_HI_SNAP.build();
            this.default_map.add_reg(this.CLIENT_ELAPSED_HI_SNAP, 'h190);
            this.CLIENT_OWNER_ACTIVE_SNAP = new("CLIENT_OWNER_ACTIVE_SNAP");
            this.CLIENT_OWNER_ACTIVE_SNAP.configure(this);

            this.CLIENT_OWNER_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.CLIENT_OWNER_ACTIVE_SNAP, 'h1a0);
            this.CLIENT_ALIVE_ACTIVE_SNAP = new("CLIENT_ALIVE_ACTIVE_SNAP");
            this.CLIENT_ALIVE_ACTIVE_SNAP.configure(this);

            this.CLIENT_ALIVE_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.CLIENT_ALIVE_ACTIVE_SNAP, 'h1a4);
            this.CLIENT_FLOW_ACTIVE_SNAP = new("CLIENT_FLOW_ACTIVE_SNAP");
            this.CLIENT_FLOW_ACTIVE_SNAP.configure(this);

            this.CLIENT_FLOW_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.CLIENT_FLOW_ACTIVE_SNAP, 'h1a8);
            this.CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP = new("CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP");
            this.CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP.configure(this);

            this.CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.CLIENT_DEADLINE_MIN_LO_ACTIVE_SNAP, 'h1ac);
            this.CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP = new("CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP");
            this.CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP.configure(this);

            this.CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.CLIENT_DEADLINE_MIN_HI_ACTIVE_SNAP, 'h1b0);
            this.CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP = new("CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP");
            this.CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP.configure(this);

            this.CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.CLIENT_DEADLINE_MAX_LO_ACTIVE_SNAP, 'h1b4);
            this.CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP = new("CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP");
            this.CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP.configure(this);

            this.CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP.build();
            this.default_map.add_reg(this.CLIENT_DEADLINE_MAX_HI_ACTIVE_SNAP, 'h1b8);
        endfunction : build
    endclass : watchdog_regs__channel_regs

    // addrmap - watchdog_regs
    class watchdog_regs extends uvm_reg_block;
        rand watchdog_regs__IP_ID IP_ID;
        rand watchdog_regs__VERSION VERSION;
        rand watchdog_regs__CAPABILITY0 CAPABILITY0;
        rand watchdog_regs__CAPABILITY1 CAPABILITY1;
        rand watchdog_regs__CMD_STATUS CMD_STATUS;
        rand watchdog_regs__ISSUED_SEQ ISSUED_SEQ;
        rand watchdog_regs__DONE_SEQ DONE_SEQ;
        rand watchdog_regs__DONE_INFO DONE_INFO;
        rand watchdog_regs__IRQ_SUMMARY IRQ_SUMMARY;
        rand watchdog_regs__FAULT_SUMMARY FAULT_SUMMARY;
        rand watchdog_regs__RESET_SUMMARY RESET_SUMMARY;
        rand watchdog_regs__channel_regs ch[16];

        function new(string name = "watchdog_regs");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.IP_ID = new("IP_ID");
            this.IP_ID.configure(this);

            this.IP_ID.build();
            this.default_map.add_reg(this.IP_ID, 'h0);
            this.VERSION = new("VERSION");
            this.VERSION.configure(this);

            this.VERSION.build();
            this.default_map.add_reg(this.VERSION, 'h4);
            this.CAPABILITY0 = new("CAPABILITY0");
            this.CAPABILITY0.configure(this);

            this.CAPABILITY0.build();
            this.default_map.add_reg(this.CAPABILITY0, 'h8);
            this.CAPABILITY1 = new("CAPABILITY1");
            this.CAPABILITY1.configure(this);

            this.CAPABILITY1.build();
            this.default_map.add_reg(this.CAPABILITY1, 'hc);
            this.CMD_STATUS = new("CMD_STATUS");
            this.CMD_STATUS.configure(this);

            this.CMD_STATUS.build();
            this.default_map.add_reg(this.CMD_STATUS, 'h10);
            this.ISSUED_SEQ = new("ISSUED_SEQ");
            this.ISSUED_SEQ.configure(this);

            this.ISSUED_SEQ.build();
            this.default_map.add_reg(this.ISSUED_SEQ, 'h14);
            this.DONE_SEQ = new("DONE_SEQ");
            this.DONE_SEQ.configure(this);

            this.DONE_SEQ.build();
            this.default_map.add_reg(this.DONE_SEQ, 'h18);
            this.DONE_INFO = new("DONE_INFO");
            this.DONE_INFO.configure(this);

            this.DONE_INFO.build();
            this.default_map.add_reg(this.DONE_INFO, 'h1c);
            this.IRQ_SUMMARY = new("IRQ_SUMMARY");
            this.IRQ_SUMMARY.configure(this);

            this.IRQ_SUMMARY.build();
            this.default_map.add_reg(this.IRQ_SUMMARY, 'h20);
            this.FAULT_SUMMARY = new("FAULT_SUMMARY");
            this.FAULT_SUMMARY.configure(this);

            this.FAULT_SUMMARY.build();
            this.default_map.add_reg(this.FAULT_SUMMARY, 'h24);
            this.RESET_SUMMARY = new("RESET_SUMMARY");
            this.RESET_SUMMARY.configure(this);

            this.RESET_SUMMARY.build();
            this.default_map.add_reg(this.RESET_SUMMARY, 'h28);
            foreach(this.ch[i0]) begin
                this.ch[i0] = new($sformatf("ch[%0d]", i0));
                this.ch[i0].configure(this);
                this.ch[i0].build();
                this.default_map.add_submap(this.ch[i0].default_map, 'h1000 + i0*'h400);
            end
        endfunction : build
    endclass : watchdog_regs

endpackage: watchdog_ral
