
// This file was autogenerated by PeakRDL-uvm
package gpio_ral_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - gpio_regs::IP_ID
    class gpio_regs__IP_ID extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__IP_ID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h4750494f, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__IP_ID

    // reg - gpio_regs::VERSION
    class gpio_regs__VERSION extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__VERSION");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h10000, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__VERSION

    // reg - gpio_regs::FEATURE
    class gpio_regs__FEATURE extends uvm_reg;
        rand uvm_reg_field features;

        function new(string name = "gpio_regs__FEATURE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.features = new("features");
            this.features.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__FEATURE

    // reg - gpio_regs::GEOMETRY
    class gpio_regs__GEOMETRY extends uvm_reg;
        rand uvm_reg_field n_gpio;
        rand uvm_reg_field n_bank;
        rand uvm_reg_field n_irq_groups;
        rand uvm_reg_field sync_stages;

        function new(string name = "gpio_regs__GEOMETRY");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.n_gpio = new("n_gpio");
            this.n_gpio.configure(this, 8, 0, "RO", 1, 'h80, 1, 1, 0);
            this.n_bank = new("n_bank");
            this.n_bank.configure(this, 8, 8, "RO", 1, 'h4, 1, 1, 0);
            this.n_irq_groups = new("n_irq_groups");
            this.n_irq_groups.configure(this, 8, 16, "RO", 1, 'h1, 1, 1, 0);
            this.sync_stages = new("sync_stages");
            this.sync_stages.configure(this, 8, 24, "RO", 1, 'h2, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__GEOMETRY

    // reg - gpio_regs::GLOBAL_LOCK
    class gpio_regs__GLOBAL_LOCK extends uvm_reg;
        rand uvm_reg_field locked;

        function new(string name = "gpio_regs__GLOBAL_LOCK");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.locked = new("locked");
            this.locked.configure(this, 1, 0, "W1S", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__GLOBAL_LOCK

    // reg - gpio_regs::ACCESS_CFG
    class gpio_regs__ACCESS_CFG extends uvm_reg;
        rand uvm_reg_field secure_only;
        rand uvm_reg_field priv_only;

        function new(string name = "gpio_regs__ACCESS_CFG");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.secure_only = new("secure_only");
            this.secure_only.configure(this, 1, 0, "RW", 1, 'h1, 1, 1, 0);
            this.priv_only = new("priv_only");
            this.priv_only.configure(this, 1, 1, "RW", 1, 'h1, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__ACCESS_CFG

    // reg - gpio_regs::FAULT_STATUS
    class gpio_regs__FAULT_STATUS extends uvm_reg;
        rand uvm_reg_field sources;

        function new(string name = "gpio_regs__FAULT_STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.sources = new("sources");
            this.sources.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__FAULT_STATUS

    // reg - gpio_regs::FAULT_CLEAR
    class gpio_regs__FAULT_CLEAR extends uvm_reg;
        rand uvm_reg_field clear;

        function new(string name = "gpio_regs__FAULT_CLEAR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.clear = new("clear");
            this.clear.configure(this, 8, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__FAULT_CLEAR

    // reg - gpio_regs::FAULT_IRQ_ENABLE
    class gpio_regs__FAULT_IRQ_ENABLE extends uvm_reg;
        rand uvm_reg_field enable;

        function new(string name = "gpio_regs__FAULT_IRQ_ENABLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.enable = new("enable");
            this.enable.configure(this, 8, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__FAULT_IRQ_ENABLE

    // reg - gpio_regs::ACCESS_FIRST
    class gpio_regs__ACCESS_FIRST extends uvm_reg;
        rand uvm_reg_field address;
        rand uvm_reg_field pprot;
        rand uvm_reg_field write;
        rand uvm_reg_field valid;

        function new(string name = "gpio_regs__ACCESS_FIRST");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.address = new("address");
            this.address.configure(this, 14, 0, "RO", 1, 'h0, 1, 1, 0);
            this.pprot = new("pprot");
            this.pprot.configure(this, 3, 16, "RO", 1, 'h0, 1, 1, 0);
            this.write = new("write");
            this.write.configure(this, 1, 19, "RO", 1, 'h0, 1, 1, 0);
            this.valid = new("valid");
            this.valid.configure(this, 1, 31, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__ACCESS_FIRST

    // reg - gpio_regs::SNAPSHOT_CMD
    class gpio_regs__SNAPSHOT_CMD extends uvm_reg;
        rand uvm_reg_field trigger;

        function new(string name = "gpio_regs__SNAPSHOT_CMD");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.trigger = new("trigger");
            this.trigger.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__SNAPSHOT_CMD

    // reg - gpio_regs::SNAP_SEQ
    class gpio_regs__SNAP_SEQ extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__SNAP_SEQ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__SNAP_SEQ

    // reg - gpio_regs::STRAP_VALID
    class gpio_regs__STRAP_VALID extends uvm_reg;
        rand uvm_reg_field valid;

        function new(string name = "gpio_regs__STRAP_VALID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.valid = new("valid");
            this.valid.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__STRAP_VALID

    // reg - gpio_regs::LP_STATUS
    class gpio_regs__LP_STATUS extends uvm_reg;
        rand uvm_reg_field sleep_active;
        rand uvm_reg_field safe_active;

        function new(string name = "gpio_regs__LP_STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.sleep_active = new("sleep_active");
            this.sleep_active.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.safe_active = new("safe_active");
            this.safe_active.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__LP_STATUS

    // reg - gpio_regs::TS_LO
    class gpio_regs__TS_LO extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__TS_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__TS_LO

    // reg - gpio_regs::TS_HI
    class gpio_regs__TS_HI extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__TS_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__TS_HI

    // reg - gpio_regs::FIFO_CTRL
    class gpio_regs__FIFO_CTRL extends uvm_reg;
        rand uvm_reg_field enable;
        rand uvm_reg_field dma_enable;

        function new(string name = "gpio_regs__FIFO_CTRL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.enable = new("enable");
            this.enable.configure(this, 1, 0, "RW", 1, 'h0, 1, 1, 0);
            this.dma_enable = new("dma_enable");
            this.dma_enable.configure(this, 1, 1, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__FIFO_CTRL

    // reg - gpio_regs::FIFO_WATERMARK
    class gpio_regs__FIFO_WATERMARK extends uvm_reg;
        rand uvm_reg_field threshold;

        function new(string name = "gpio_regs__FIFO_WATERMARK");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.threshold = new("threshold");
            this.threshold.configure(this, 7, 0, "RW", 1, 'h1, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__FIFO_WATERMARK

    // reg - gpio_regs::FIFO_LEVEL
    class gpio_regs__FIFO_LEVEL extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__FIFO_LEVEL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__FIFO_LEVEL

    // reg - gpio_regs::FIFO_LOST
    class gpio_regs__FIFO_LOST extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__FIFO_LOST");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__FIFO_LOST

    // reg - gpio_regs::EVENT_HEAD0
    class gpio_regs__EVENT_HEAD0 extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__EVENT_HEAD0");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__EVENT_HEAD0

    // reg - gpio_regs::EVENT_HEAD1
    class gpio_regs__EVENT_HEAD1 extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__EVENT_HEAD1");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__EVENT_HEAD1

    // reg - gpio_regs::EVENT_HEAD2
    class gpio_regs__EVENT_HEAD2 extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__EVENT_HEAD2");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__EVENT_HEAD2

    // reg - gpio_regs::EVENT_HEAD3
    class gpio_regs__EVENT_HEAD3 extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__EVENT_HEAD3");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__EVENT_HEAD3

    // reg - gpio_regs::EVENT_POP
    class gpio_regs__EVENT_POP extends uvm_reg;
        rand uvm_reg_field pop;

        function new(string name = "gpio_regs__EVENT_POP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.pop = new("pop");
            this.pop.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__EVENT_POP

    // reg - gpio_regs::FIFO_CMD
    class gpio_regs__FIFO_CMD extends uvm_reg;
        rand uvm_reg_field flush;
        rand uvm_reg_field clear_lost;

        function new(string name = "gpio_regs__FIFO_CMD");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.flush = new("flush");
            this.flush.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
            this.clear_lost = new("clear_lost");
            this.clear_lost.configure(this, 1, 1, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__FIFO_CMD

    // reg - gpio_regs::AON_STATUS
    class gpio_regs__AON_STATUS extends uvm_reg;
        rand uvm_reg_field ready;
        rand uvm_reg_field busy;
        rand uvm_reg_field done;
        rand uvm_reg_field timeout;
        rand uvm_reg_field error;
        rand uvm_reg_field bank;

        function new(string name = "gpio_regs__AON_STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ready = new("ready");
            this.ready.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.busy = new("busy");
            this.busy.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            this.done = new("done");
            this.done.configure(this, 1, 2, "RO", 1, 'h0, 1, 1, 0);
            this.timeout = new("timeout");
            this.timeout.configure(this, 1, 3, "RO", 1, 'h0, 1, 1, 0);
            this.error = new("error");
            this.error.configure(this, 1, 4, "RO", 1, 'h0, 1, 1, 0);
            this.bank = new("bank");
            this.bank.configure(this, 2, 8, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__AON_STATUS

    // reg - gpio_regs::AON_TIMEOUT
    class gpio_regs__AON_TIMEOUT extends uvm_reg;
        rand uvm_reg_field cycles;

        function new(string name = "gpio_regs__AON_TIMEOUT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.cycles = new("cycles");
            this.cycles.configure(this, 24, 0, "RW", 1, 'hffff, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__AON_TIMEOUT

    // reg - gpio_regs::PARITY_INJECT
    class gpio_regs__PARITY_INJECT extends uvm_reg;
        rand uvm_reg_field trigger;
        rand uvm_reg_field bank;

        function new(string name = "gpio_regs__PARITY_INJECT");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.trigger = new("trigger");
            this.trigger.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
            this.bank = new("bank");
            this.bank.configure(this, 2, 8, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__PARITY_INJECT

    // reg - gpio_regs::bank_type::INPUT_CAP
    class gpio_regs__bank_type__INPUT_CAP extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__INPUT_CAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__INPUT_CAP

    // reg - gpio_regs::bank_type::OUTPUT_CAP
    class gpio_regs__bank_type__OUTPUT_CAP extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OUTPUT_CAP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OUTPUT_CAP

    // reg - gpio_regs::bank_type::IN_SYNC
    class gpio_regs__bank_type__IN_SYNC extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__IN_SYNC");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__IN_SYNC

    // reg - gpio_regs::bank_type::IN_DATA
    class gpio_regs__bank_type__IN_DATA extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__IN_DATA");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__IN_DATA

    // reg - gpio_regs::bank_type::IN_VALID
    class gpio_regs__bank_type__IN_VALID extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__IN_VALID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__IN_VALID

    // reg - gpio_regs::bank_type::IN_ENABLE
    class gpio_regs__bank_type__IN_ENABLE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__IN_ENABLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__IN_ENABLE

    // reg - gpio_regs::bank_type::OUT_DATA
    class gpio_regs__bank_type__OUT_DATA extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OUT_DATA");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OUT_DATA

    // reg - gpio_regs::bank_type::OUT_SET
    class gpio_regs__bank_type__OUT_SET extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OUT_SET");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OUT_SET

    // reg - gpio_regs::bank_type::OUT_CLR
    class gpio_regs__bank_type__OUT_CLR extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OUT_CLR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OUT_CLR

    // reg - gpio_regs::bank_type::OUT_TOGGLE
    class gpio_regs__bank_type__OUT_TOGGLE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OUT_TOGGLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OUT_TOGGLE

    // reg - gpio_regs::bank_type::OUT_MASKED_LO
    class gpio_regs__bank_type__OUT_MASKED_LO extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OUT_MASKED_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OUT_MASKED_LO

    // reg - gpio_regs::bank_type::OUT_MASKED_HI
    class gpio_regs__bank_type__OUT_MASKED_HI extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OUT_MASKED_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OUT_MASKED_HI

    // reg - gpio_regs::bank_type::OUT_OE
    class gpio_regs__bank_type__OUT_OE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OUT_OE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OUT_OE

    // reg - gpio_regs::bank_type::OE_SET
    class gpio_regs__bank_type__OE_SET extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OE_SET");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OE_SET

    // reg - gpio_regs::bank_type::OE_CLR
    class gpio_regs__bank_type__OE_CLR extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OE_CLR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OE_CLR

    // reg - gpio_regs::bank_type::OE_MASKED_LO
    class gpio_regs__bank_type__OE_MASKED_LO extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OE_MASKED_LO");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OE_MASKED_LO

    // reg - gpio_regs::bank_type::OE_MASKED_HI
    class gpio_regs__bank_type__OE_MASKED_HI extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OE_MASKED_HI");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OE_MASKED_HI

    // reg - gpio_regs::bank_type::IRQ_DETECT_EN
    class gpio_regs__bank_type__IRQ_DETECT_EN extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__IRQ_DETECT_EN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__IRQ_DETECT_EN

    // reg - gpio_regs::bank_type::IRQ_ENABLE
    class gpio_regs__bank_type__IRQ_ENABLE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__IRQ_ENABLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__IRQ_ENABLE

    // reg - gpio_regs::bank_type::IRQ_PENDING
    class gpio_regs__bank_type__IRQ_PENDING extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__IRQ_PENDING");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__IRQ_PENDING

    // reg - gpio_regs::bank_type::IRQ_STATUS
    class gpio_regs__bank_type__IRQ_STATUS extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__IRQ_STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__IRQ_STATUS

    // reg - gpio_regs::bank_type::IRQ_TEST
    class gpio_regs__bank_type__IRQ_TEST extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__IRQ_TEST");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__IRQ_TEST

    // reg - gpio_regs::bank_type::RISING_PENDING
    class gpio_regs__bank_type__RISING_PENDING extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__RISING_PENDING");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__RISING_PENDING

    // reg - gpio_regs::bank_type::FALLING_PENDING
    class gpio_regs__bank_type__FALLING_PENDING extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__FALLING_PENDING");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__FALLING_PENDING

    // reg - gpio_regs::bank_type::CFG_LOCK
    class gpio_regs__bank_type__CFG_LOCK extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__CFG_LOCK");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "W1S", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__CFG_LOCK

    // reg - gpio_regs::bank_type::DATA_LOCK
    class gpio_regs__bank_type__DATA_LOCK extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__DATA_LOCK");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "W1S", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__DATA_LOCK

    // reg - gpio_regs::bank_type::BANK_DEBOUNCE_DIV
    class gpio_regs__bank_type__BANK_DEBOUNCE_DIV extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__BANK_DEBOUNCE_DIV");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__BANK_DEBOUNCE_DIV

    // reg - gpio_regs::bank_type::EVENT_ENABLE
    class gpio_regs__bank_type__EVENT_ENABLE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__EVENT_ENABLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__EVENT_ENABLE

    // reg - gpio_regs::bank_type::SNAP_DATA
    class gpio_regs__bank_type__SNAP_DATA extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__SNAP_DATA");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__SNAP_DATA

    // reg - gpio_regs::bank_type::SNAP_VALID
    class gpio_regs__bank_type__SNAP_VALID extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__SNAP_VALID");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__SNAP_VALID

    // reg - gpio_regs::bank_type::STRAP_DATA
    class gpio_regs__bank_type__STRAP_DATA extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__STRAP_DATA");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__STRAP_DATA

    // reg - gpio_regs::bank_type::DIAG_ENABLE
    class gpio_regs__bank_type__DIAG_ENABLE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__DIAG_ENABLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__DIAG_ENABLE

    // reg - gpio_regs::bank_type::DIAG_PENDING
    class gpio_regs__bank_type__DIAG_PENDING extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__DIAG_PENDING");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__DIAG_PENDING

    // reg - gpio_regs::bank_type::DIAG_TEST
    class gpio_regs__bank_type__DIAG_TEST extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__DIAG_TEST");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__DIAG_TEST

    // reg - gpio_regs::bank_type::OUTPUT_OWNED
    class gpio_regs__bank_type__OUTPUT_OWNED extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__OUTPUT_OWNED");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__OUTPUT_OWNED

    // reg - gpio_regs::bank_type::INPUT_AVAILABLE
    class gpio_regs__bank_type__INPUT_AVAILABLE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__bank_type__INPUT_AVAILABLE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__bank_type__INPUT_AVAILABLE

    // regfile - gpio_regs::bank_type
    class gpio_regs__bank_type extends uvm_reg_block;
        rand gpio_regs__bank_type__INPUT_CAP INPUT_CAP;
        rand gpio_regs__bank_type__OUTPUT_CAP OUTPUT_CAP;
        rand gpio_regs__bank_type__IN_SYNC IN_SYNC;
        rand gpio_regs__bank_type__IN_DATA IN_DATA;
        rand gpio_regs__bank_type__IN_VALID IN_VALID;
        rand gpio_regs__bank_type__IN_ENABLE IN_ENABLE;
        rand gpio_regs__bank_type__OUT_DATA OUT_DATA;
        rand gpio_regs__bank_type__OUT_SET OUT_SET;
        rand gpio_regs__bank_type__OUT_CLR OUT_CLR;
        rand gpio_regs__bank_type__OUT_TOGGLE OUT_TOGGLE;
        rand gpio_regs__bank_type__OUT_MASKED_LO OUT_MASKED_LO;
        rand gpio_regs__bank_type__OUT_MASKED_HI OUT_MASKED_HI;
        rand gpio_regs__bank_type__OUT_OE OUT_OE;
        rand gpio_regs__bank_type__OE_SET OE_SET;
        rand gpio_regs__bank_type__OE_CLR OE_CLR;
        rand gpio_regs__bank_type__OE_MASKED_LO OE_MASKED_LO;
        rand gpio_regs__bank_type__OE_MASKED_HI OE_MASKED_HI;
        rand gpio_regs__bank_type__IRQ_DETECT_EN IRQ_DETECT_EN;
        rand gpio_regs__bank_type__IRQ_ENABLE IRQ_ENABLE;
        rand gpio_regs__bank_type__IRQ_PENDING IRQ_PENDING;
        rand gpio_regs__bank_type__IRQ_STATUS IRQ_STATUS;
        rand gpio_regs__bank_type__IRQ_TEST IRQ_TEST;
        rand gpio_regs__bank_type__RISING_PENDING RISING_PENDING;
        rand gpio_regs__bank_type__FALLING_PENDING FALLING_PENDING;
        rand gpio_regs__bank_type__CFG_LOCK CFG_LOCK;
        rand gpio_regs__bank_type__DATA_LOCK DATA_LOCK;
        rand gpio_regs__bank_type__BANK_DEBOUNCE_DIV BANK_DEBOUNCE_DIV;
        rand gpio_regs__bank_type__EVENT_ENABLE EVENT_ENABLE;
        rand gpio_regs__bank_type__SNAP_DATA SNAP_DATA;
        rand gpio_regs__bank_type__SNAP_VALID SNAP_VALID;
        rand gpio_regs__bank_type__STRAP_DATA STRAP_DATA;
        rand gpio_regs__bank_type__DIAG_ENABLE DIAG_ENABLE;
        rand gpio_regs__bank_type__DIAG_PENDING DIAG_PENDING;
        rand gpio_regs__bank_type__DIAG_TEST DIAG_TEST;
        rand gpio_regs__bank_type__OUTPUT_OWNED OUTPUT_OWNED;
        rand gpio_regs__bank_type__INPUT_AVAILABLE INPUT_AVAILABLE;

        function new(string name = "gpio_regs__bank_type");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.INPUT_CAP = new("INPUT_CAP");
            this.INPUT_CAP.configure(this);

            this.INPUT_CAP.build();
            this.default_map.add_reg(this.INPUT_CAP, 'h0);
            this.OUTPUT_CAP = new("OUTPUT_CAP");
            this.OUTPUT_CAP.configure(this);

            this.OUTPUT_CAP.build();
            this.default_map.add_reg(this.OUTPUT_CAP, 'h4);
            this.IN_SYNC = new("IN_SYNC");
            this.IN_SYNC.configure(this);

            this.IN_SYNC.build();
            this.default_map.add_reg(this.IN_SYNC, 'h8);
            this.IN_DATA = new("IN_DATA");
            this.IN_DATA.configure(this);

            this.IN_DATA.build();
            this.default_map.add_reg(this.IN_DATA, 'hc);
            this.IN_VALID = new("IN_VALID");
            this.IN_VALID.configure(this);

            this.IN_VALID.build();
            this.default_map.add_reg(this.IN_VALID, 'h10);
            this.IN_ENABLE = new("IN_ENABLE");
            this.IN_ENABLE.configure(this);

            this.IN_ENABLE.build();
            this.default_map.add_reg(this.IN_ENABLE, 'h14);
            this.OUT_DATA = new("OUT_DATA");
            this.OUT_DATA.configure(this);

            this.OUT_DATA.build();
            this.default_map.add_reg(this.OUT_DATA, 'h18);
            this.OUT_SET = new("OUT_SET");
            this.OUT_SET.configure(this);

            this.OUT_SET.build();
            this.default_map.add_reg(this.OUT_SET, 'h1c);
            this.OUT_CLR = new("OUT_CLR");
            this.OUT_CLR.configure(this);

            this.OUT_CLR.build();
            this.default_map.add_reg(this.OUT_CLR, 'h20);
            this.OUT_TOGGLE = new("OUT_TOGGLE");
            this.OUT_TOGGLE.configure(this);

            this.OUT_TOGGLE.build();
            this.default_map.add_reg(this.OUT_TOGGLE, 'h24);
            this.OUT_MASKED_LO = new("OUT_MASKED_LO");
            this.OUT_MASKED_LO.configure(this);

            this.OUT_MASKED_LO.build();
            this.default_map.add_reg(this.OUT_MASKED_LO, 'h28);
            this.OUT_MASKED_HI = new("OUT_MASKED_HI");
            this.OUT_MASKED_HI.configure(this);

            this.OUT_MASKED_HI.build();
            this.default_map.add_reg(this.OUT_MASKED_HI, 'h2c);
            this.OUT_OE = new("OUT_OE");
            this.OUT_OE.configure(this);

            this.OUT_OE.build();
            this.default_map.add_reg(this.OUT_OE, 'h30);
            this.OE_SET = new("OE_SET");
            this.OE_SET.configure(this);

            this.OE_SET.build();
            this.default_map.add_reg(this.OE_SET, 'h34);
            this.OE_CLR = new("OE_CLR");
            this.OE_CLR.configure(this);

            this.OE_CLR.build();
            this.default_map.add_reg(this.OE_CLR, 'h38);
            this.OE_MASKED_LO = new("OE_MASKED_LO");
            this.OE_MASKED_LO.configure(this);

            this.OE_MASKED_LO.build();
            this.default_map.add_reg(this.OE_MASKED_LO, 'h3c);
            this.OE_MASKED_HI = new("OE_MASKED_HI");
            this.OE_MASKED_HI.configure(this);

            this.OE_MASKED_HI.build();
            this.default_map.add_reg(this.OE_MASKED_HI, 'h40);
            this.IRQ_DETECT_EN = new("IRQ_DETECT_EN");
            this.IRQ_DETECT_EN.configure(this);

            this.IRQ_DETECT_EN.build();
            this.default_map.add_reg(this.IRQ_DETECT_EN, 'h44);
            this.IRQ_ENABLE = new("IRQ_ENABLE");
            this.IRQ_ENABLE.configure(this);

            this.IRQ_ENABLE.build();
            this.default_map.add_reg(this.IRQ_ENABLE, 'h48);
            this.IRQ_PENDING = new("IRQ_PENDING");
            this.IRQ_PENDING.configure(this);

            this.IRQ_PENDING.build();
            this.default_map.add_reg(this.IRQ_PENDING, 'h4c);
            this.IRQ_STATUS = new("IRQ_STATUS");
            this.IRQ_STATUS.configure(this);

            this.IRQ_STATUS.build();
            this.default_map.add_reg(this.IRQ_STATUS, 'h50);
            this.IRQ_TEST = new("IRQ_TEST");
            this.IRQ_TEST.configure(this);

            this.IRQ_TEST.build();
            this.default_map.add_reg(this.IRQ_TEST, 'h54);
            this.RISING_PENDING = new("RISING_PENDING");
            this.RISING_PENDING.configure(this);

            this.RISING_PENDING.build();
            this.default_map.add_reg(this.RISING_PENDING, 'h58);
            this.FALLING_PENDING = new("FALLING_PENDING");
            this.FALLING_PENDING.configure(this);

            this.FALLING_PENDING.build();
            this.default_map.add_reg(this.FALLING_PENDING, 'h5c);
            this.CFG_LOCK = new("CFG_LOCK");
            this.CFG_LOCK.configure(this);

            this.CFG_LOCK.build();
            this.default_map.add_reg(this.CFG_LOCK, 'h60);
            this.DATA_LOCK = new("DATA_LOCK");
            this.DATA_LOCK.configure(this);

            this.DATA_LOCK.build();
            this.default_map.add_reg(this.DATA_LOCK, 'h64);
            this.BANK_DEBOUNCE_DIV = new("BANK_DEBOUNCE_DIV");
            this.BANK_DEBOUNCE_DIV.configure(this);

            this.BANK_DEBOUNCE_DIV.build();
            this.default_map.add_reg(this.BANK_DEBOUNCE_DIV, 'h68);
            this.EVENT_ENABLE = new("EVENT_ENABLE");
            this.EVENT_ENABLE.configure(this);

            this.EVENT_ENABLE.build();
            this.default_map.add_reg(this.EVENT_ENABLE, 'h6c);
            this.SNAP_DATA = new("SNAP_DATA");
            this.SNAP_DATA.configure(this);

            this.SNAP_DATA.build();
            this.default_map.add_reg(this.SNAP_DATA, 'h70);
            this.SNAP_VALID = new("SNAP_VALID");
            this.SNAP_VALID.configure(this);

            this.SNAP_VALID.build();
            this.default_map.add_reg(this.SNAP_VALID, 'h74);
            this.STRAP_DATA = new("STRAP_DATA");
            this.STRAP_DATA.configure(this);

            this.STRAP_DATA.build();
            this.default_map.add_reg(this.STRAP_DATA, 'h78);
            this.DIAG_ENABLE = new("DIAG_ENABLE");
            this.DIAG_ENABLE.configure(this);

            this.DIAG_ENABLE.build();
            this.default_map.add_reg(this.DIAG_ENABLE, 'h7c);
            this.DIAG_PENDING = new("DIAG_PENDING");
            this.DIAG_PENDING.configure(this);

            this.DIAG_PENDING.build();
            this.default_map.add_reg(this.DIAG_PENDING, 'h80);
            this.DIAG_TEST = new("DIAG_TEST");
            this.DIAG_TEST.configure(this);

            this.DIAG_TEST.build();
            this.default_map.add_reg(this.DIAG_TEST, 'h84);
            this.OUTPUT_OWNED = new("OUTPUT_OWNED");
            this.OUTPUT_OWNED.configure(this);

            this.OUTPUT_OWNED.build();
            this.default_map.add_reg(this.OUTPUT_OWNED, 'h88);
            this.INPUT_AVAILABLE = new("INPUT_AVAILABLE");
            this.INPUT_AVAILABLE.configure(this);

            this.INPUT_AVAILABLE.build();
            this.default_map.add_reg(this.INPUT_AVAILABLE, 'h8c);
        endfunction : build
    endclass : gpio_regs__bank_type

    // reg - gpio_regs::pin_type::PIN_CFG
    class gpio_regs__pin_type__PIN_CFG extends uvm_reg;
        rand uvm_reg_field filter_en;
        rand uvm_reg_field debounce_en;
        rand uvm_reg_field in_inv;
        rand uvm_reg_field out_od;
        rand uvm_reg_field out_inv;
        rand uvm_reg_field irq_mode;
        rand uvm_reg_field irq_group;
        rand uvm_reg_field sleep_mode;

        function new(string name = "gpio_regs__pin_type__PIN_CFG");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.filter_en = new("filter_en");
            this.filter_en.configure(this, 1, 0, "RW", 1, 'h0, 1, 1, 0);
            this.debounce_en = new("debounce_en");
            this.debounce_en.configure(this, 1, 1, "RW", 1, 'h0, 1, 1, 0);
            this.in_inv = new("in_inv");
            this.in_inv.configure(this, 1, 2, "RW", 1, 'h0, 1, 1, 0);
            this.out_od = new("out_od");
            this.out_od.configure(this, 1, 3, "RW", 1, 'h0, 1, 1, 0);
            this.out_inv = new("out_inv");
            this.out_inv.configure(this, 1, 4, "RW", 1, 'h0, 1, 1, 0);
            this.irq_mode = new("irq_mode");
            this.irq_mode.configure(this, 3, 5, "RW", 1, 'h0, 1, 1, 0);
            this.irq_group = new("irq_group");
            this.irq_group.configure(this, 2, 8, "RW", 1, 'h0, 1, 1, 0);
            this.sleep_mode = new("sleep_mode");
            this.sleep_mode.configure(this, 2, 10, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__pin_type__PIN_CFG

    // reg - gpio_regs::pin_type::FILTER_CFG
    class gpio_regs__pin_type__FILTER_CFG extends uvm_reg;
        rand uvm_reg_field k_minus_one;

        function new(string name = "gpio_regs__pin_type__FILTER_CFG");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.k_minus_one = new("k_minus_one");
            this.k_minus_one.configure(this, 8, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__pin_type__FILTER_CFG

    // reg - gpio_regs::pin_type::DEBOUNCE_CFG
    class gpio_regs__pin_type__DEBOUNCE_CFG extends uvm_reg;
        rand uvm_reg_field d_minus_one;

        function new(string name = "gpio_regs__pin_type__DEBOUNCE_CFG");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.d_minus_one = new("d_minus_one");
            this.d_minus_one.configure(this, 8, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__pin_type__DEBOUNCE_CFG

    // reg - gpio_regs::pin_type::DIAG_CFG
    class gpio_regs__pin_type__DIAG_CFG extends uvm_reg;
        rand uvm_reg_field blank;
        rand uvm_reg_field m_minus_one;

        function new(string name = "gpio_regs__pin_type__DIAG_CFG");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.blank = new("blank");
            this.blank.configure(this, 16, 0, "RW", 1, 'h4, 1, 1, 0);
            this.m_minus_one = new("m_minus_one");
            this.m_minus_one.configure(this, 8, 16, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__pin_type__DIAG_CFG

    // regfile - gpio_regs::pin_type
    class gpio_regs__pin_type extends uvm_reg_block;
        rand gpio_regs__pin_type__PIN_CFG PIN_CFG;
        rand gpio_regs__pin_type__FILTER_CFG FILTER_CFG;
        rand gpio_regs__pin_type__DEBOUNCE_CFG DEBOUNCE_CFG;
        rand gpio_regs__pin_type__DIAG_CFG DIAG_CFG;

        function new(string name = "gpio_regs__pin_type");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.PIN_CFG = new("PIN_CFG");
            this.PIN_CFG.configure(this);

            this.PIN_CFG.build();
            this.default_map.add_reg(this.PIN_CFG, 'h0);
            this.FILTER_CFG = new("FILTER_CFG");
            this.FILTER_CFG.configure(this);

            this.FILTER_CFG.build();
            this.default_map.add_reg(this.FILTER_CFG, 'h4);
            this.DEBOUNCE_CFG = new("DEBOUNCE_CFG");
            this.DEBOUNCE_CFG.configure(this);

            this.DEBOUNCE_CFG.build();
            this.default_map.add_reg(this.DEBOUNCE_CFG, 'h8);
            this.DIAG_CFG = new("DIAG_CFG");
            this.DIAG_CFG.configure(this);

            this.DIAG_CFG.build();
            this.default_map.add_reg(this.DIAG_CFG, 'hc);
        endfunction : build
    endclass : gpio_regs__pin_type

    // reg - gpio_regs::aon_type::WAKE_ENABLE_STAGE
    class gpio_regs__aon_type__WAKE_ENABLE_STAGE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_ENABLE_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_ENABLE_STAGE

    // reg - gpio_regs::aon_type::WAKE_MODE_STAGE0
    class gpio_regs__aon_type__WAKE_MODE_STAGE0 extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_MODE_STAGE0");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_MODE_STAGE0

    // reg - gpio_regs::aon_type::WAKE_MODE_STAGE1
    class gpio_regs__aon_type__WAKE_MODE_STAGE1 extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_MODE_STAGE1");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_MODE_STAGE1

    // reg - gpio_regs::aon_type::WAKE_MODE_STAGE2
    class gpio_regs__aon_type__WAKE_MODE_STAGE2 extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_MODE_STAGE2");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_MODE_STAGE2

    // reg - gpio_regs::aon_type::WAKE_DIV_STAGE
    class gpio_regs__aon_type__WAKE_DIV_STAGE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_DIV_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_DIV_STAGE

    // reg - gpio_regs::aon_type::WAKE_COUNT_STAGE
    class gpio_regs__aon_type__WAKE_COUNT_STAGE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_COUNT_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 8, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_COUNT_STAGE

    // reg - gpio_regs::aon_type::WAKE_MASK_STAGE
    class gpio_regs__aon_type__WAKE_MASK_STAGE extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_MASK_STAGE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_MASK_STAGE

    // reg - gpio_regs::aon_type::AON_CMD
    class gpio_regs__aon_type__AON_CMD extends uvm_reg;
        rand uvm_reg_field commands;

        function new(string name = "gpio_regs__aon_type__AON_CMD");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.commands = new("commands");
            this.commands.configure(this, 4, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__AON_CMD

    // reg - gpio_regs::aon_type::WAKE_PENDING_READ
    class gpio_regs__aon_type__WAKE_PENDING_READ extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_PENDING_READ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_PENDING_READ

    // reg - gpio_regs::aon_type::WAKE_VALID_READ
    class gpio_regs__aon_type__WAKE_VALID_READ extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_VALID_READ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_VALID_READ

    // reg - gpio_regs::aon_type::WAKE_LOCK_READ
    class gpio_regs__aon_type__WAKE_LOCK_READ extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_LOCK_READ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_LOCK_READ

    // reg - gpio_regs::aon_type::WAKE_ENABLE_READ
    class gpio_regs__aon_type__WAKE_ENABLE_READ extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_ENABLE_READ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_ENABLE_READ

    // reg - gpio_regs::aon_type::WAKE_MODE_READ0
    class gpio_regs__aon_type__WAKE_MODE_READ0 extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_MODE_READ0");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_MODE_READ0

    // reg - gpio_regs::aon_type::WAKE_MODE_READ1
    class gpio_regs__aon_type__WAKE_MODE_READ1 extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_MODE_READ1");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_MODE_READ1

    // reg - gpio_regs::aon_type::WAKE_MODE_READ2
    class gpio_regs__aon_type__WAKE_MODE_READ2 extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_MODE_READ2");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_MODE_READ2

    // reg - gpio_regs::aon_type::WAKE_DIV_READ
    class gpio_regs__aon_type__WAKE_DIV_READ extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_DIV_READ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 16, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_DIV_READ

    // reg - gpio_regs::aon_type::WAKE_COUNT_READ
    class gpio_regs__aon_type__WAKE_COUNT_READ extends uvm_reg;
        rand uvm_reg_field value;

        function new(string name = "gpio_regs__aon_type__WAKE_COUNT_READ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.value = new("value");
            this.value.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : gpio_regs__aon_type__WAKE_COUNT_READ

    // regfile - gpio_regs::aon_type
    class gpio_regs__aon_type extends uvm_reg_block;
        rand gpio_regs__aon_type__WAKE_ENABLE_STAGE WAKE_ENABLE_STAGE;
        rand gpio_regs__aon_type__WAKE_MODE_STAGE0 WAKE_MODE_STAGE0;
        rand gpio_regs__aon_type__WAKE_MODE_STAGE1 WAKE_MODE_STAGE1;
        rand gpio_regs__aon_type__WAKE_MODE_STAGE2 WAKE_MODE_STAGE2;
        rand gpio_regs__aon_type__WAKE_DIV_STAGE WAKE_DIV_STAGE;
        rand gpio_regs__aon_type__WAKE_COUNT_STAGE WAKE_COUNT_STAGE;
        rand gpio_regs__aon_type__WAKE_MASK_STAGE WAKE_MASK_STAGE;
        rand gpio_regs__aon_type__AON_CMD AON_CMD;
        rand gpio_regs__aon_type__WAKE_PENDING_READ WAKE_PENDING_READ;
        rand gpio_regs__aon_type__WAKE_VALID_READ WAKE_VALID_READ;
        rand gpio_regs__aon_type__WAKE_LOCK_READ WAKE_LOCK_READ;
        rand gpio_regs__aon_type__WAKE_ENABLE_READ WAKE_ENABLE_READ;
        rand gpio_regs__aon_type__WAKE_MODE_READ0 WAKE_MODE_READ0;
        rand gpio_regs__aon_type__WAKE_MODE_READ1 WAKE_MODE_READ1;
        rand gpio_regs__aon_type__WAKE_MODE_READ2 WAKE_MODE_READ2;
        rand gpio_regs__aon_type__WAKE_DIV_READ WAKE_DIV_READ;
        rand gpio_regs__aon_type__WAKE_COUNT_READ WAKE_COUNT_READ;

        function new(string name = "gpio_regs__aon_type");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.WAKE_ENABLE_STAGE = new("WAKE_ENABLE_STAGE");
            this.WAKE_ENABLE_STAGE.configure(this);

            this.WAKE_ENABLE_STAGE.build();
            this.default_map.add_reg(this.WAKE_ENABLE_STAGE, 'h0);
            this.WAKE_MODE_STAGE0 = new("WAKE_MODE_STAGE0");
            this.WAKE_MODE_STAGE0.configure(this);

            this.WAKE_MODE_STAGE0.build();
            this.default_map.add_reg(this.WAKE_MODE_STAGE0, 'h4);
            this.WAKE_MODE_STAGE1 = new("WAKE_MODE_STAGE1");
            this.WAKE_MODE_STAGE1.configure(this);

            this.WAKE_MODE_STAGE1.build();
            this.default_map.add_reg(this.WAKE_MODE_STAGE1, 'h8);
            this.WAKE_MODE_STAGE2 = new("WAKE_MODE_STAGE2");
            this.WAKE_MODE_STAGE2.configure(this);

            this.WAKE_MODE_STAGE2.build();
            this.default_map.add_reg(this.WAKE_MODE_STAGE2, 'hc);
            this.WAKE_DIV_STAGE = new("WAKE_DIV_STAGE");
            this.WAKE_DIV_STAGE.configure(this);

            this.WAKE_DIV_STAGE.build();
            this.default_map.add_reg(this.WAKE_DIV_STAGE, 'h10);
            this.WAKE_COUNT_STAGE = new("WAKE_COUNT_STAGE");
            this.WAKE_COUNT_STAGE.configure(this);

            this.WAKE_COUNT_STAGE.build();
            this.default_map.add_reg(this.WAKE_COUNT_STAGE, 'h14);
            this.WAKE_MASK_STAGE = new("WAKE_MASK_STAGE");
            this.WAKE_MASK_STAGE.configure(this);

            this.WAKE_MASK_STAGE.build();
            this.default_map.add_reg(this.WAKE_MASK_STAGE, 'h18);
            this.AON_CMD = new("AON_CMD");
            this.AON_CMD.configure(this);

            this.AON_CMD.build();
            this.default_map.add_reg(this.AON_CMD, 'h1c);
            this.WAKE_PENDING_READ = new("WAKE_PENDING_READ");
            this.WAKE_PENDING_READ.configure(this);

            this.WAKE_PENDING_READ.build();
            this.default_map.add_reg(this.WAKE_PENDING_READ, 'h20);
            this.WAKE_VALID_READ = new("WAKE_VALID_READ");
            this.WAKE_VALID_READ.configure(this);

            this.WAKE_VALID_READ.build();
            this.default_map.add_reg(this.WAKE_VALID_READ, 'h24);
            this.WAKE_LOCK_READ = new("WAKE_LOCK_READ");
            this.WAKE_LOCK_READ.configure(this);

            this.WAKE_LOCK_READ.build();
            this.default_map.add_reg(this.WAKE_LOCK_READ, 'h28);
            this.WAKE_ENABLE_READ = new("WAKE_ENABLE_READ");
            this.WAKE_ENABLE_READ.configure(this);

            this.WAKE_ENABLE_READ.build();
            this.default_map.add_reg(this.WAKE_ENABLE_READ, 'h2c);
            this.WAKE_MODE_READ0 = new("WAKE_MODE_READ0");
            this.WAKE_MODE_READ0.configure(this);

            this.WAKE_MODE_READ0.build();
            this.default_map.add_reg(this.WAKE_MODE_READ0, 'h30);
            this.WAKE_MODE_READ1 = new("WAKE_MODE_READ1");
            this.WAKE_MODE_READ1.configure(this);

            this.WAKE_MODE_READ1.build();
            this.default_map.add_reg(this.WAKE_MODE_READ1, 'h34);
            this.WAKE_MODE_READ2 = new("WAKE_MODE_READ2");
            this.WAKE_MODE_READ2.configure(this);

            this.WAKE_MODE_READ2.build();
            this.default_map.add_reg(this.WAKE_MODE_READ2, 'h38);
            this.WAKE_DIV_READ = new("WAKE_DIV_READ");
            this.WAKE_DIV_READ.configure(this);

            this.WAKE_DIV_READ.build();
            this.default_map.add_reg(this.WAKE_DIV_READ, 'h3c);
            this.WAKE_COUNT_READ = new("WAKE_COUNT_READ");
            this.WAKE_COUNT_READ.configure(this);

            this.WAKE_COUNT_READ.build();
            this.default_map.add_reg(this.WAKE_COUNT_READ, 'h40);
        endfunction : build
    endclass : gpio_regs__aon_type

    // addrmap - gpio_regs
    class gpio_regs extends uvm_reg_block;
        rand gpio_regs__IP_ID IP_ID;
        rand gpio_regs__VERSION VERSION;
        rand gpio_regs__FEATURE FEATURE;
        rand gpio_regs__GEOMETRY GEOMETRY;
        rand gpio_regs__GLOBAL_LOCK GLOBAL_LOCK;
        rand gpio_regs__ACCESS_CFG ACCESS_CFG;
        rand gpio_regs__FAULT_STATUS FAULT_STATUS;
        rand gpio_regs__FAULT_CLEAR FAULT_CLEAR;
        rand gpio_regs__FAULT_IRQ_ENABLE FAULT_IRQ_ENABLE;
        rand gpio_regs__ACCESS_FIRST ACCESS_FIRST;
        rand gpio_regs__SNAPSHOT_CMD SNAPSHOT_CMD;
        rand gpio_regs__SNAP_SEQ SNAP_SEQ;
        rand gpio_regs__STRAP_VALID STRAP_VALID;
        rand gpio_regs__LP_STATUS LP_STATUS;
        rand gpio_regs__TS_LO TS_LO;
        rand gpio_regs__TS_HI TS_HI;
        rand gpio_regs__FIFO_CTRL FIFO_CTRL;
        rand gpio_regs__FIFO_WATERMARK FIFO_WATERMARK;
        rand gpio_regs__FIFO_LEVEL FIFO_LEVEL;
        rand gpio_regs__FIFO_LOST FIFO_LOST;
        rand gpio_regs__EVENT_HEAD0 EVENT_HEAD0;
        rand gpio_regs__EVENT_HEAD1 EVENT_HEAD1;
        rand gpio_regs__EVENT_HEAD2 EVENT_HEAD2;
        rand gpio_regs__EVENT_HEAD3 EVENT_HEAD3;
        rand gpio_regs__EVENT_POP EVENT_POP;
        rand gpio_regs__FIFO_CMD FIFO_CMD;
        rand gpio_regs__AON_STATUS AON_STATUS;
        rand gpio_regs__AON_TIMEOUT AON_TIMEOUT;
        rand gpio_regs__PARITY_INJECT PARITY_INJECT;
        rand gpio_regs__bank_type bank[4];
        rand gpio_regs__pin_type pin[128];
        rand gpio_regs__aon_type aon[4];

        function new(string name = "gpio_regs");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.IP_ID = new("IP_ID");
            this.IP_ID.configure(this);

            this.IP_ID.build();
            this.default_map.add_reg(this.IP_ID, 'h0);
            this.VERSION = new("VERSION");
            this.VERSION.configure(this);

            this.VERSION.build();
            this.default_map.add_reg(this.VERSION, 'h4);
            this.FEATURE = new("FEATURE");
            this.FEATURE.configure(this);

            this.FEATURE.build();
            this.default_map.add_reg(this.FEATURE, 'h8);
            this.GEOMETRY = new("GEOMETRY");
            this.GEOMETRY.configure(this);

            this.GEOMETRY.build();
            this.default_map.add_reg(this.GEOMETRY, 'hc);
            this.GLOBAL_LOCK = new("GLOBAL_LOCK");
            this.GLOBAL_LOCK.configure(this);

            this.GLOBAL_LOCK.build();
            this.default_map.add_reg(this.GLOBAL_LOCK, 'h10);
            this.ACCESS_CFG = new("ACCESS_CFG");
            this.ACCESS_CFG.configure(this);

            this.ACCESS_CFG.build();
            this.default_map.add_reg(this.ACCESS_CFG, 'h14);
            this.FAULT_STATUS = new("FAULT_STATUS");
            this.FAULT_STATUS.configure(this);

            this.FAULT_STATUS.build();
            this.default_map.add_reg(this.FAULT_STATUS, 'h18);
            this.FAULT_CLEAR = new("FAULT_CLEAR");
            this.FAULT_CLEAR.configure(this);

            this.FAULT_CLEAR.build();
            this.default_map.add_reg(this.FAULT_CLEAR, 'h1c);
            this.FAULT_IRQ_ENABLE = new("FAULT_IRQ_ENABLE");
            this.FAULT_IRQ_ENABLE.configure(this);

            this.FAULT_IRQ_ENABLE.build();
            this.default_map.add_reg(this.FAULT_IRQ_ENABLE, 'h20);
            this.ACCESS_FIRST = new("ACCESS_FIRST");
            this.ACCESS_FIRST.configure(this);

            this.ACCESS_FIRST.build();
            this.default_map.add_reg(this.ACCESS_FIRST, 'h24);
            this.SNAPSHOT_CMD = new("SNAPSHOT_CMD");
            this.SNAPSHOT_CMD.configure(this);

            this.SNAPSHOT_CMD.build();
            this.default_map.add_reg(this.SNAPSHOT_CMD, 'h28);
            this.SNAP_SEQ = new("SNAP_SEQ");
            this.SNAP_SEQ.configure(this);

            this.SNAP_SEQ.build();
            this.default_map.add_reg(this.SNAP_SEQ, 'h2c);
            this.STRAP_VALID = new("STRAP_VALID");
            this.STRAP_VALID.configure(this);

            this.STRAP_VALID.build();
            this.default_map.add_reg(this.STRAP_VALID, 'h30);
            this.LP_STATUS = new("LP_STATUS");
            this.LP_STATUS.configure(this);

            this.LP_STATUS.build();
            this.default_map.add_reg(this.LP_STATUS, 'h34);
            this.TS_LO = new("TS_LO");
            this.TS_LO.configure(this);

            this.TS_LO.build();
            this.default_map.add_reg(this.TS_LO, 'h38);
            this.TS_HI = new("TS_HI");
            this.TS_HI.configure(this);

            this.TS_HI.build();
            this.default_map.add_reg(this.TS_HI, 'h3c);
            this.FIFO_CTRL = new("FIFO_CTRL");
            this.FIFO_CTRL.configure(this);

            this.FIFO_CTRL.build();
            this.default_map.add_reg(this.FIFO_CTRL, 'h40);
            this.FIFO_WATERMARK = new("FIFO_WATERMARK");
            this.FIFO_WATERMARK.configure(this);

            this.FIFO_WATERMARK.build();
            this.default_map.add_reg(this.FIFO_WATERMARK, 'h44);
            this.FIFO_LEVEL = new("FIFO_LEVEL");
            this.FIFO_LEVEL.configure(this);

            this.FIFO_LEVEL.build();
            this.default_map.add_reg(this.FIFO_LEVEL, 'h48);
            this.FIFO_LOST = new("FIFO_LOST");
            this.FIFO_LOST.configure(this);

            this.FIFO_LOST.build();
            this.default_map.add_reg(this.FIFO_LOST, 'h4c);
            this.EVENT_HEAD0 = new("EVENT_HEAD0");
            this.EVENT_HEAD0.configure(this);

            this.EVENT_HEAD0.build();
            this.default_map.add_reg(this.EVENT_HEAD0, 'h50);
            this.EVENT_HEAD1 = new("EVENT_HEAD1");
            this.EVENT_HEAD1.configure(this);

            this.EVENT_HEAD1.build();
            this.default_map.add_reg(this.EVENT_HEAD1, 'h54);
            this.EVENT_HEAD2 = new("EVENT_HEAD2");
            this.EVENT_HEAD2.configure(this);

            this.EVENT_HEAD2.build();
            this.default_map.add_reg(this.EVENT_HEAD2, 'h58);
            this.EVENT_HEAD3 = new("EVENT_HEAD3");
            this.EVENT_HEAD3.configure(this);

            this.EVENT_HEAD3.build();
            this.default_map.add_reg(this.EVENT_HEAD3, 'h5c);
            this.EVENT_POP = new("EVENT_POP");
            this.EVENT_POP.configure(this);

            this.EVENT_POP.build();
            this.default_map.add_reg(this.EVENT_POP, 'h60);
            this.FIFO_CMD = new("FIFO_CMD");
            this.FIFO_CMD.configure(this);

            this.FIFO_CMD.build();
            this.default_map.add_reg(this.FIFO_CMD, 'h64);
            this.AON_STATUS = new("AON_STATUS");
            this.AON_STATUS.configure(this);

            this.AON_STATUS.build();
            this.default_map.add_reg(this.AON_STATUS, 'h68);
            this.AON_TIMEOUT = new("AON_TIMEOUT");
            this.AON_TIMEOUT.configure(this);

            this.AON_TIMEOUT.build();
            this.default_map.add_reg(this.AON_TIMEOUT, 'h6c);
            this.PARITY_INJECT = new("PARITY_INJECT");
            this.PARITY_INJECT.configure(this);

            this.PARITY_INJECT.build();
            this.default_map.add_reg(this.PARITY_INJECT, 'h70);
            foreach(this.bank[i0]) begin
                this.bank[i0] = new($sformatf("bank[%0d]", i0));
                this.bank[i0].configure(this);
                this.bank[i0].build();
                this.default_map.add_submap(this.bank[i0].default_map, 'h100 + i0*'h100);
            end
            foreach(this.pin[i0]) begin
                this.pin[i0] = new($sformatf("pin[%0d]", i0));
                this.pin[i0].configure(this);
                this.pin[i0].build();
                this.default_map.add_submap(this.pin[i0].default_map, 'h1000 + i0*'h20);
            end
            foreach(this.aon[i0]) begin
                this.aon[i0] = new($sformatf("aon[%0d]", i0));
                this.aon[i0].configure(this);
                this.aon[i0].build();
                this.default_map.add_submap(this.aon[i0].default_map, 'h3000 + i0*'h100);
            end
        endfunction : build
    endclass : gpio_regs

endpackage: gpio_ral_pkg
