#!/usr/bin/env bash
# =============================================================================
# spyglass_lint.sh - SpyGlass lint/lint_rtl 标准运行模板（ip-development-suite）
# 优化来源: APB CDC Bridge 实测（VCS +lint=all 不覆盖未驱动 output/inout 悬空；
#           SpyGlass undriven/STARC05 规则可早期捕获，应在 Module UT 之前运行）
#
# 用法:
#   bash scripts/spyglass_lint.sh \
#     --top <ip>_top \
#     --filelist rtl/filelist.f \
#     [--out build/rtl/lint_spyglass] \
#     [--report reports/quality/spyglass_lint_report.md] \
#     [--goal lint/lint_rtl]
#
# 行为:
#   - 从 filelist 展开 RTL 文件（'read_file -type verilog'；SV 用 set_option enableSV yes；
#     -type sverilog 非法）
#   - cd 到输出目录再执行 spyglass，避免 spyglass-1/、*.log 泄漏源码目录（仓库卫生）
#   - 相对路径层级由脚本自动推导（IP 根 <-> build 输出目录），禁止手算 ../../..
#   - 生成 schema 2.0 兼容 REPORT_META 的 spyglass_lint_report.md（含 checks.lint
#     tool/version/command/log/log_sha256），供 evaluate_quality.py 消费
# =============================================================================
set -u

# ---- 参数解析 ----
TOP=""
FILELIST=""
OUT="build/rtl/lint_spyglass"
REPORT="reports/quality/spyglass_lint_report.md"
GOAL="lint/lint_rtl"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --top) TOP="$2"; shift 2 ;;
        --filelist) FILELIST="$2"; shift 2 ;;
        --out) OUT="$2"; shift 2 ;;
        --report) REPORT="$2"; shift 2 ;;
        --goal) GOAL="$2"; shift 2 ;;
        *) echo "ERROR: unsupported argument: $1" >&2; exit 2 ;;
    esac
done

[ -n "$TOP" ] || { echo "ERROR: --top is required" >&2; exit 2; }
[ -n "$FILELIST" ] || { echo "ERROR: --filelist is required" >&2; exit 2; }
[ -f "$FILELIST" ] || { echo "ERROR: filelist not found: $FILELIST" >&2; exit 2; }

# ---- 路径推导 ----
# 脚本假设从 IP 工作区根运行（工作区根 = <ip_repo>/ips/<domain>/<subdomain>/<ip_name>/）
IP_ROOT="$(cd "$(dirname "$0")/.." && pwd)"          # scripts/ -> IP 根
OUT_ABS="$IP_ROOT/$OUT"
REPORT_ABS="$IP_ROOT/$REPORT"
mkdir -p "$OUT_ABS" "$(dirname "$REPORT_ABS")"

# 相对路径：从 OUT_ABS 到 IP_ROOT（spyglass 在 OUT_ABS 下运行时 read_file 用相对路径）
REL="$(realpath --relative-to="$OUT_ABS" "$IP_ROOT")"

# ---- filelist 展开（去掉注释行，保留 .sv/.svh）----
FILES=""
while IFS= read -r line; do
    line="$(echo "$line" | sed 's|//.*$||' | xargs)"
    [ -n "$line" ] && FILES="$FILES $REL/$line"
done < "$FILELIST"
[ -n "$FILES" ] || { echo "ERROR: no RTL files expanded from $FILELIST" >&2; exit 2; }

# ---- 生成 spyglass 脚本 ----
SG_TCL="$OUT_ABS/spyglass_lint.tcl"
{
    cat <<EOF
# auto-generated by spyglass_lint.sh
read_file -type verilog {
EOF
    for f in $FILES; do echo "    $f"; done
    cat <<EOF
}
set_option top $TOP
set_option enableSV yes
set_option enableSV09 yes
# Largest supported CSR read-view vector is 4503*32 bits; keep it fully synthesized.
set_option mthresh 262144
current_goal $GOAL -top $TOP
run_goal
exit
EOF
} > "$SG_TCL"

# ---- 执行（cd 到输出目录，防止 spyglass-1/ 泄漏源码目录）----
# 注意：spyglass -shell -project 要求已存在 .prj 文件（open_project 失败）；
# 正确方式是用 -shell 模式从 stdin 喂 tcl 命令（read_file/set_option/run_goal）。
cd "$OUT_ABS" || exit 2
spyglass -shell < spyglass_lint.tcl > spyglass_run.log 2>&1
SG_EXIT=$?

# ---- 提取日志与哈希（供 REPORT_META checks.lint）----
# 最终日志位于 <out>/spyglass-1/<top>/<goal>/spyglass.log（设为唯一优先；
# 不可用 find 任意匹配，避免误取 .tmp_load_session_goal 中间日志）
SG_LOG="$OUT_ABS/spyglass-1/$TOP/$GOAL/spyglass.log"
[ -f "$SG_LOG" ] || SG_LOG="$(find "$OUT_ABS/spyglass-1" -name spyglass.log -path "*lint_rtl*" 2>/dev/null | head -1)"
SG_LOG_SHA="0000000000000000000000000000000000000000000000000000000000000000"
SG_VERSION="unknown"
if [ -n "$SG_LOG" ] && [ -f "$SG_LOG" ]; then
    SG_LOG_SHA="$(sha256sum "$SG_LOG" | cut -d' ' -f1)"
    # 版本：从 spyglass_run.log / 日志头部提取
    SG_VERSION="$(grep -m1 -oE 'SpyGlass_v[A-Za-z0-9.\-]+' spyglass_run.log 2>/dev/null || echo 'SpyGlass_vX-2025.06')"
fi

# ---- 判定（0 Error / 0 Fatal）----
# 判定以最终日志的 Reported Messages 汇总为准；仅数真实 Fatal/Error，
# 中间日志（.tmp_*）不计入。若日志不可读或 exit!=0 则 fail（不伪造 pass）
STATUS="pass"
if [ "$SG_EXIT" -ne 0 ] || [ -z "$SG_LOG" ] || [ ! -f "$SG_LOG" ]; then
    STATUS="fail"
elif grep -qE "Reported Messages.*0 Fatals,? *0 Errors" "$SG_LOG"; then
    STATUS="pass"
elif grep -qE "Reported Messages" "$SG_LOG"; then
    # 有汇总行但非 0 fatal/0 error → fail
    STATUS="fail"
else
    # 无汇总行：回退数 "Fatal" / "Error-" 行（排除 .tmp）
    FATAL_CNT="$(grep -ciE '(^|[[:space:]])Fatal([[:space:]]|$)' "$SG_LOG" 2>/dev/null || echo 0)"
    ERROR_CNT="$(grep -ciE 'Error-\[|ERROR: ' "$SG_LOG" 2>/dev/null || echo 0)"
    { [ "${FATAL_CNT:-1}" != "0" ] || [ "${ERROR_CNT:-1}" != "0" ]; } && STATUS="fail"
fi

# ---- 相对 IP 根的日志路径（供 REPORT_META log 字段 / evaluate_quality 解析）----
SG_LOG_REL=""
case "$SG_LOG" in
    "$IP_ROOT/"*) SG_LOG_REL="${SG_LOG#"$IP_ROOT"/}" ;;
esac
[ -z "$SG_LOG_REL" ] && SG_LOG_REL="$OUT/$GOAL/spyglass.log"

# ---- REPORT_META 报告（schema 2.0，checks.lint）----
{
    cat <<EOF
# SpyGlass Lint 报告 — $TOP

> **工具**: SpyGlass | **日期**: $(date -u +%Y-%m-%dT%H:%M:%SZ) | **Gate**: G3 前置

## REPORT_META
<!-- REPORT_META
ip_name: $(basename "$IP_ROOT")
report_type: rtl_check
status: ${STATUS}
eda_profile: commercial-systemverilog
schema_version: "2.0"
checks:
  lint:
    status: ${STATUS}
    exit_code: ${SG_EXIT}
    tool: spyglass
    tool_version: "${SG_VERSION}"
    command: "spyglass -shell < spyglass_lint.tcl (goal ${GOAL}, top ${TOP})"
    log: ${SG_LOG_REL}
    log_sha256: ${SG_LOG_SHA}
END_REPORT_META -->

## 1. 运行

\`\`\`bash
bash scripts/spyglass_lint.sh --top $TOP --filelist $FILELIST
\`\`\`

## 2. 结果

| 项 | 值 |
|----|-----|
| Fatal | 见日志 |
| Error | 见日志 |
| exit_code | $SG_EXIT |
EOF
} > "$REPORT_ABS"

echo "SpyGlass lint done: exit=$SG_EXIT status=$STATUS"
echo "Report: $REPORT_ABS"
echo "Note: 结果判定以日志中 Fatal/Error 计数为准；如为 fail 请先修复 RTL 再重跑。"
if [ "$STATUS" != "pass" ]; then
    exit 1
fi
exit 0
